### ISSUE TITLE
add targetPlatform for freebsd in install.rdf

### ISSUE THREAD

**Issue by antxxxx** [luckyrat/KeeFox#144]
Hi
   Can you add this to install.rdf

    <em:targetPlatform>FreeBSD</em:targetPlatform>

   so it can be installed in freebsd. The plugin works on freebsd when you copy the dll files to the KeePass directory and start KeePass using mono

   Thanks

Anthony

**Comment by luckyrat** [comment]
I'm going to keep this as a beta version only for the foreseeable future since there's no way of me verifying that it works in a stable version.
