### ISSUE TITLE
Keefox Plugin incompatible with Keepass2?

### ISSUE THREAD

**Issue by Shuro** [luckyrat/KeeFox#148]
Hi there, i try to get KeyPass & KeyFox running under Linux (Linux Mint 12).

Installed the Debian / Ubuntu package without Problem 

<pre>keepass2 2.20.1+dfsg-0ubuntu1~ppa1~precise1</pre>

Also installed KeyFox Stable without Problem 

<pre>https://addons.mozilla.org/en-US/firefox/addon/keefox/?src=external-kforg-download</pre>

Now i tried to copy the plugin from 

<pre>
/home/userhome/.mozilla/firefox/1234.default/extensions/keefox@chris.tomlinson/deps/KeePassRPC.plgx
</pre>

to

<pre>
/usr/lib/keepass2/
</pre>

Now on startup of keypass2 it comes the follow message

<pre>The following plugin is incompatible with the current KeePass version:
/usr/lib/keepass2/KeePassRPC.plgx
Have a look at the plugin's website for an appropriate version.
</pre>

Did someone have an idea where the problem is? On the KeePass-Page is the KeeFox Plugin labled as 2.x compatible

Edit: Added image from keepass2 --debug
![2013_02_06_-_Auswahl_001](https://f.cloud.github.com/assets/944030/131595/24219c9c-7064-11e2-94df-8c0994b9134f.png)

**Comment by webwake** [comment]
was searching for this and was able to fix it on my computer by installing the latest version of mono and the mono-complete. Not an expert so might have been overkill but it worked.
```

#source: http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get install mono-complete
sudo apt-get update
```
