### ISSUE TITLE
Expose formActionURL in KeePass user interface

### ISSUE THREAD

**Issue by elieux** [luckyrat/KeeFox#168]
I would like to see/change the formActionURL field without digging into the KeePassRPC JSON field.

**Comment by luckyrat** [comment]
From KeeFox 1.5 onwards, the form action URL is no longer considered a useful factor in establishing entry match relevance. It's already ignored when KeePassRPC decides which entries to return to KeeFox so there are very few scenarios it would be useful anyway. In the unlikely event that KeeFox 1.5 does cause a problem as a result of this change, please open a new issue so we can evaluate what alternative approach might work for that specific scenario.
