### ISSUE TITLE
Thunderbird sometimes doesn't fill passwords, says I'm logged out or locked

### ISSUE THREAD

**Issue by elieux** [luckyrat/KeeFox#171]
Lately (for 2 weeks or so) I've been noticing that Thunderbird sometimes refuses to connect(?) to KeePass. The behavior seems to be different between my two laptops:
- slower one (Windows 8) doesn't fill passwords at all, I have to auto-type all my passwords
- faster one (Windows 7) sometimes start filling passwords, but not always in the first password dialog

Thunderbird, KeePass, my profile and my databases are synchronized between the computers, so there should be no differences. All my databases are loaded and unlocked before I start Thunderbird. I have Lightning installed with several online calendars (updating them on startup blocks Thunderbird for a while). I have _Options > Advanced > Network & Disk Space > Offline... > Ask me for online state on startup_ enabled.

UPDATE: When I put the slower computer to sleep, woke it up and unlocked databases, Thunderbird (the one that has been running for some time and didn't want to fill passwords) filled a password when I sent an email.

Is there some kind of timeout that would prevent KeeFox from connecting correctly?

**Comment by dlech** [comment]
I was finally able to reproduce this - and thanks to some other recent changes in KeeFox, I was able to fix it!
