### ISSUE TITLE
Does not work on the Hungarian version of Thunderbird

### ISSUE THREAD

**Issue by indivisible** [luckyrat/KeeFox#229]
Does not fill the dialogs in the Hungarian localization of Thunderbird 24.1.1.

The issue seems to be that the dialogs' strings contain parentheses (like " a(z) ").

Should work after adding some basic sanitization.

**Comment by dlech** [comment]
This patch broke pop3, so we need to revert it and try again. See #351.

**Comment by dlech** [comment]
I managed to fix it without reverting in e92f18f9738c7de18399d643786e245c793cf6d9.
