### ISSUE TITLE
Allow multiple saved connection keys (migrating profiles)

### ISSUE THREAD

**Issue by elieux** [luckyrat/KeeFox#235]
I use KeePassRPC/KeeFox on three computers with shared (synced) configuration files (including Fx and Tb profiles) and I have to re-authorize Firefox and Thunderbird everytime I switch computers.

I'm not sure what causes this, but it seems like a "hash collision" -- I assume that the connection identifier contains less information than what is used for the key decryption. I use the same logon name and password on each computer, but the SIDs are different.

**Comment by luckyrat** [comment]
In case it's of any help to anyone hunting for the best way to manage these config and sync issues, note that KeePass 2.29 has a potentially useful new feature:

"The path of the local configuration file can now be changed using the '-cfg-local:' command line parameter."

**Comment by dmak** [comment]
I have the problem which is somehow related to above. I have several Firefox installations running on different PCs, all having synchronization enabled (former Weave project). The problem is that once I start Firefox on one PC, Keefox asks to enter secure code. I do so, but after I restart Firefox on another PC, their the secure code is asked again. I enter it, and then it happens on the 1st PC. So I am entering security codes again and again in this endless carousel. I have copied `extensions.keefox@chris.tomlinson.KPRPC*` keys in FF profile + `logins.json` and `KeePassRPC.Key.*` keys in `KeePass.config.xml` from 1st PC to 2nd PC (with FF and Keypass shutdown). It did not help. What should be the right strategy?

**Comment by elieux** [comment]
I don't think there's a solution for that, assuming that Firefox Sync transfers preferences.

**Comment by dmak** [comment]
I can't really understand what bits of information need to be copied and what is being updated. I had an idea that I can shutdown all FF and Keepass instances, copy the security information, and start them again. Am I looking into right direction?

**Comment by elieux** [comment]
Your synchronization is probably working fine; too well, in fact. The problem, as explained in [a previous comment by Chris](https://github.com/luckyrat/KeeFox/issues/235#issuecomment-31886343) is that a key created on one machine is not valid for other machines (it's user accounts, to be more specific).

The solution for me was to exclude the KPRPC keys and usernames from synchronization. I have no idea if Firefox Sync can be set in a similar way.

**Comment by luckyrat** [comment]
Firefox should not be Syncing the `extensions.keefox@chris.tomlinson...` config properties. If it is, they must have changed the sync behaviour at some point without announcing it.

**Comment by elieux** [comment]
@luckyrat, depends on how old your information is. Could it have changed in Firefox 29, when the Sync migrated to Firefox Accounts?

**Comment by dmak** [comment]
@elieux: Where the key is actually stored in FF? I believe the stopper is not UUID in `extensions.keefox@chris.tomlinson.KPRPC*` properties – it simply refers the section in `KeePass.config.xml`. But where the security key value is stored on FF side? Maybe I miss something, but if FF knows only UUID and provided that `KeePass.config.xml` is "local" (not synced), then there should be no problem to have different encrypted keys in `KeePass.config.xml` on each PC with the same UUID "reference". At least I see that UUID is not re-generated in each re-authentication attempt.

Also I have a feeling it worked OK in FF v34, but then it started to show the warning that I need to update to never FF which will use new synchronization infrastructure (see [Transitioning Legacy Sync users to Firefox Accounts](https://blog.mozilla.org/services/2015/02/03/legacy-sync-migration/)), and that is when the problem has started. Perhaps that my observation is not relative, as this very thread was launched far earlier then FF v34 (released on 2014.11.26).

For my information only: is `extensions.keefox@chris.tomlinson.KPRPCStoredKey-xxx` legacy and can it be safely removed?

**Comment by elieux** [comment]
> Where the key is actually stored in FF?

Although it's not very obvious from the text, the [technical description of the KeePassRPC protocol](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Technical-%7C-KeePassRPC-detail) mentions a shared key, which means the key is stored on both sides. The page features this table, relevant to your question:

> The table below explains where the secret key is stored.
> 
> <table>
> <th>
> <td><b>KeeFox (Firefox)</b></td><td><b>KeePassRPC (KeePass)</b></td>
> </th>
> <tr><td><b>High</b></td>
> <td>Not stored</td>
> <td>Not stored*</td></tr>
> 
> <tr><td><b>Medium</b></td>
> <td>Firefox password storage file (may be unencrypted)**</td>
> <td>KeePass config file (encrypted - strength depends on your windows logon password)</td></tr>
> <tr><td><b>Low</b></td>
> <td>about:config (unencrypted)</td>
> <td>KeePass config file (unencrypted)</td></tr>
> </table>

> Also I have a feeling it worked OK in FF v34

I think it's because the new Sync transfers all user preferences (and the older one didn't). But that's just a speculation based on your observations.

> Perhaps that my observation is not relative as this very thread was launched far earlier then FF v34 (released on 2014.11.26), e.g. users have experienced problems before migration to Firefox Accounts.

The problems that were discussed in this issue/thread are the result of synchronizing Firefox profiles using external file-based sync tools, which certainly do transfer all user preferences. (I don't think the choice of syncing or not syncing the KeePass config file has any real effect on this problem.)

It's possible our user.js trick will work for you, too, if Firefox Sync is clever enough to exclude these preferences from its processes. Can you try it?

Technical note: One could theoretically keep just one key in Firefox and have that key paired with multiple KeePass installations, where each KeePass stores the same key, just encrypted with different Windows user account information. Everything would work correctly, but this situation is not achievable without source code modification or without doing some complex computations "by hand". See Chris's explanation in point (2) in this comment: https://github.com/luckyrat/KeeFox/issues/235#issuecomment-32725723

**Comment by dmak** [comment]
Thanks for your comment. Finally it seems that the proposed solution with `user.js` worked. I have few more observations:
* It seems like removing the preferences from `prefs.js` is not necessary as they will anyway be copied back, see [Preferences Saving](https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences#saving).
* In my FF options on [Sync tab](about:preferences#sync) I have no checkbox next to "Preferences". So preferences should not be synced. But I have checkbox next to "Passwords" and that perhaps was causing the problem (`logins.json` password storage was synchronized).

Thanks for everyone for comments – after I have learned more details about KeePassRPC authentication, I understood what I was doing wrong.
