### ISSUE TITLE
Firefox displays two master password dialogs

### ISSUE THREAD

**Issue by elieux** [luckyrat/KeeFox#239]
Firefox v26, KeeFox v1.3.0b1, KeePassRPC v1.3, KeePass v2.24.

I created a master password in Firefox and it asks me for it twice during start. Once in a modal dialog and once in a dialog window with a taskbar button.

A quick Internet search didn't show any relevant results, so it doesn't seem like a Firefox issue. Maybe add-ons?

**Comment by luckyrat** [comment]
I don't think there's anything we can/should do here but feel free to re-open if there is still an issue with KeeFox 1.5

**Comment by elieux** [comment]
I've recently seen a colleague's Thunderbird showing three master password prompts, so I guess this isn't exactly an issue with KeeFox. I, personally, am still using StartupMaster and I had no problems since.
