### ISSUE TITLE
Thunderbird does not fill in Passwords in all of my e-mail accounts (I miss password fill in for my gmx-account)

### ISSUE THREAD

**Issue by VEisch** [luckyrat/KeeFox#240]
Hello!
Has somebody of you an idea, why Thunderbird does not fill in the Password for both of my gmx accounts? For all other account is works fine! I cecked every thing over xx hours but could not find the reason. Today I deinstalled keepass and keefox but no success either and I tried all different types of URLs and user names. 
When I try to lock in my account, I always get the message: "No matching with keepass"!
Please give me an idea how to solve this problem.

THANK YOU!

**Comment by dlech** [comment]
We made some changes in KeeFox v1.4.6 that I think should fix this issue. Can you please test and close this issue if it works now?

**Comment by luckyrat** [comment]
Any news on this @VEisch ?

**Comment by dlech** [comment]
Closing due to no response.
