### ISSUE TITLE
KeeFox Thunderbird, some notes about usability

### ISSUE THREAD

**Issue by neniuideo** [luckyrat/KeeFox#246]
Just found it, nice, i like it :)

Some notes... only to inform you about that. Maybe you are interested in what the users are missing. I do not know how important this thinks are, i leave it to you to decide.

- gContactSync http://www.pirules.org/addons/gcontactsync/index.php
  store the Password (In this case the access Token) in Thunderbird as "chrome://gContactSync". This do not work with KeeFox.

- For gmail i use an App Password. It is stored inside the Google Entry as an User string called "email Laptop". Maybe KeeFox could handle this cases (Password not stored in the password field)? Sure, it is possible to and an second entry in KeePass to handle this.

- I would be great if KeeFox Support also Password Entry in Web Pages opened in Thunderbird (like KeeFox do it in Firefox).

- more than one mailbox at one provider (same server) may not work? If i understand it right only the server name is used to find the right entry!?

- For some reason "pop.safe-mail.net" are not working.

cu

**Comment by dlech** [comment]
> For some reason "pop.safe-mail.net" are not working.

There are changes in KeeFox v1.4.6 that may fix this. Please give it a try and report back on #240.

I am going to close this issue since it is too many ideas in one issue. These are all good suggestions, so if you would like these to be considered, please open one new issue per suggestion. Thanks.
