### ISSUE TITLE
KeeFox in Thunderbird disables status bar

### ISSUE THREAD

**Issue by sputtene** [luckyrat/KeeFox#250]
With KeeFox installed and active in Thunderbird, messages such as "connected to" and "receiving message 1 of 7" are no longer displayed, nor are the URLs of links when I hover the mouse over a link.
When I disable KeeFox from the Add-ons menu and restart TB, the status bar works again. Re-enabling KF and restarting TB makes the status bar behave badly again.

There are other extensions that have the same bug, like AdBlock Plus (see https://adblockplus.org/forum/viewtopic.php?f=11&t=20570&p=91124 for example).

I'm using Thunderbird 24.3.0 on Ubuntu 13.10, with KeeFox 1.2.7.

**Comment by luckyrat** [comment]
Is this still a problem with the latest Thunderbird + KeeFox 1.5?

**Comment by sputtene** [comment]
Sorry for not reporting back on this issue.

The problem disappeared some time ago (I think about 2 months ago), but I don't know whether that was because of a Thunderbird upgrade or a KeeFox upgrade.

I'm using Thunderbird 38.2.0 and KeeFox 1.5.3 now.
