### ISSUE TITLE
I have to authorise every time Firefox starts up

### ISSUE THREAD

**Issue by ikmail1** [luckyrat/KeeFox#252]
You write one has to authorise once every year at the standard settings, but every time Firefox starts up, I get the 'authorise a new connection' window

**Comment by HotShadow** [comment]
Thanks for this solution, same behaviour happened to me in Ubuntu 15.04 and FF37! :)

**Comment by edouard-lopez** [comment]
Solve for following config:
* `Linux`Mint 17.1` Rebecca
* Firefox `39.0~b7+build1-0ubuntu0.14.04.1`
* Keepass2 `2.25+dfsg-1ubuntu0.1`
* Keefox `1.4.8.1-signed`

**Comment by joce** [comment]
Sorry to revive this, but I recently started experiencing this issue. I'm running on Windows, so the keypairs fix does not apply.

I have the following config:
* Windows 10
* Firefox 41.0 (Was also an issue with FF 40.x)
* KeePass 2.3
* Keefox 1.5.3

In KeePass, the KeeFox options authorize the client for one year minus one day, yet, if I close and open FF, I will be asked to reenter the authorization code.

**Comment by justposted** [comment]
Have you tried my solution above (install KeePass somewhere off your C drive)?

**Comment by joce** [comment]
@justposted I would like to avoid that as much as possible.

**Comment by justposted** [comment]
Fair enough. Might be worth trying it by just copying your KeePass folder somewhere (maybe a USB drive) and pointing KeeFox at it. Then at least you'll know if the problem is with permissions on your C drive.

**Comment by joce** [comment]
I tried to put it somewhere else on my C: drive, and I got the same result. 
I then tried putting it on a USB drive and... same result.
Wherever I put it, I'm asked to reauthenticate.

**Comment by joce** [comment]
Anyone? @luckyrat ?

**Comment by luckyrat** [comment]
Have you tried everything in https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting#keepassrpc-authorisation ?

**Comment by joce** [comment]
fuuuuuuuu.... It was the "saved passwords" from the clear history that was checked.
All is good now. 
Thanks @luckyrat and sorry for the noise!
