### ISSUE TITLE
Matched login keyboard shortcut should focus on logins rather than search box

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#267]
I think it would be more intuitive if when the panel is displayed via the keyboard shortcut for displaying multiple matched logins, the keyboard focus is set on the first matched login rather than the search box.

However, the current workaround of pressing the down arrow once is not exactly onerous!

**Comment by nsubiron** [comment]
Also while searching, focus best match. That way just ctrl+shift+1, type part of the name and press enter to go to the site.

**Comment by luckyrat** [comment]
That wouldn't work because we can never know when the "part of the name" is finished. As soon as we focus on the best match, you can no longer refine the search further.

**Comment by luckyrat** [comment]
This feature is implemented in KeeFox 1.5

**Comment by nsubiron** [comment]
Yes sorry, I guess the focus should be at the search box but somehow highlight the best match. I was thinking in the kind of functionality like for instance Sublime Text or Atom have in their search. While typing, the current best match is highlighted but you can keep typing, pressing enter accepts the current highlighted entry. The only difference would be that you don't need to press the down arrow to go to the best match.
