### ISSUE TITLE
Single-click login capability with new UI

### ISSUE THREAD

**Issue by DanCech** [luckyrat/KeeFox#272]
I've been using the new UI for a little while and been very pleased with it.  The one thing I miss from the old UI is the ability to log in with a single click when there is a single matching password.  Where previously it was possible to simply click the favicon of the matched login, it's now necessary to first click the toolbar button, then move the mouse down to the login itself and click again (if I'm just missing an existing shortcut please let me know!)

A thought that comes to mind would be to adopt the toolbar button format used by Firebug, which divides the button into 2 parts.

![firebugtoolbar](https://cloud.githubusercontent.com/assets/1443603/2852242/35338dcc-d131-11e3-8f40-ef172dcd2d04.png)

The right-hand side would always open the menu as clicking the button does today, but the left-hand side would be able to expose the one-click login behavior of the past by displaying the login's favicon and performing the login with a single click.

If multiple logins were found the left-hand side would show the current "logins available" icon and open the menu when clicked.  This concept does also open the door to additional one-click commands such as unlocking when the workspace is locked.

**Comment by luckyrat** [comment]
I'm not intending to add this feature but if you feel strongly enough about it to write the code to enable it, please discuss here and we could re-open it.
