### ISSUE TITLE
Error 403 from dropbox when selecting from matched logins list

### ISSUE THREAD

**Issue by scwalla** [luckyrat/KeeFox#295]
Arch Linux, Firefox 30.0, KeePass 2.26, KeeFox 1.4.2.
I have also tried this from Windows 7 with same error.

I have multiple Dropbox accounts set-up.  All of the entries work fine when automatically filled in by KeeFox.  If I select an entry from the matched login list then Dropbox fails to login correctly and I get a webpage showing error 403 from Dropbox server.

**Comment by JushyoCoshyo** [comment]
Similar issue here.
Firefox 35
Keefox 1.4.6
Windows 7

**Comment by luckyrat** [comment]
Dropbox are intentionally preventing automatic form submissions so it's unlikely we can do anything about this.

**Comment by luckyrat** [comment]
This will work in KeeFox 1.5 (thanks to an improvement in the way KeeFox works out which button to automatically press when submitting a form).
