### ISSUE TITLE
No scrolling in Notification settings

### ISSUE THREAD

**Issue by e3roll** [luckyrat/KeeFox#296]
The "pop up" window for "Notification settings" is bigger than my screen. This pop-up window is not resizable and not scrollable. So, when trying to change the frequency of the tips or notificactions, the buttons "Done"/"OK" and "Cancel" are not visible, only the "Reset to default" button is visible.

For a better understanding:
![1](https://cloud.githubusercontent.com/assets/7842271/3367566/0bd76280-fb63-11e3-9264-ee38dfed5fab.JPG)
![2](https://cloud.githubusercontent.com/assets/7842271/3367567/12955a78-fb63-11e3-90d0-14909791da0a.JPG)

A workaround is to change the screen orientation from landscape to portrait, then change the settings and click "OK". Finally, change the screen orientation back to landscape.

Useful info: I'm using Firefox 30, Keefox 1.4.2, Windows 7 SP1 x64 and the native screen resolution is 1366x768.

**Comment by luckyrat** [comment]
The OK and cancel buttons are out of KeeFox's control but I'll make the panel wider which will reduce the number of lines of text and therefore reduce the vertical height and solve this problem. The fix will be included in KeeFox 1.5
