### ISSUE TITLE
KeeFox fails to fill username field for Ally Bank login

### ISSUE THREAD

**Issue by scwalla** [luckyrat/KeeFox#299]
Windows 7, KeePass 2.26, KeeFox 1.4.2

Ally Bank splits username and password into two pages.  The URL and title are exactly the same for both username and password entry screens.

The URL is: "https://secure.ally.com/allyWebClient/login.do"
The title is: "Ally: Bank Login"

The entry in KeePass has the correct title and URL.  KeePass auto-type correctly fills the username and password fields.  KeeFox correctly fills the password field on the second screen but does not recognize the username field.

Inspecting the username field shows:
`<input name="userNamePvtEncrypt" maxlength="20" size="30" value="" id="userNamePvtEncrypt" class="txt" type="text">`

Debug Log file shows the following when I select "Detect Forms" from KeeFox menu:

Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: fillCurrentDocument start
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: panel setLogins started
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: Removing all matched logins
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: setupButton_ready start
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: Setting widget status
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: setupButton_ready end
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: setupButton_ready start
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: Setting widget status
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: setupButton_ready end
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: _fillAllFrames start
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  Filling document. Initial page load: false
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  attempting document fill
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: Returning configuration from cache
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: fillDocument processing 1 forms
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: about to get form fields
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: text
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: proccessing...
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: button
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: domtype: hidden
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: usernameIndex: -1
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: actualUsernameIndex: 0
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: otherFields.length:1
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: no password field found in this form
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: Filling 1 sub frames
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: _fillAllFrames start
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  Filling document. Initial page load: false
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  attempting document fill
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  No forms found on this page
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: Filling 2 sub frames
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: _fillAllFrames start
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  Filling document. Initial page load: false
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  attempting document fill
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  No forms found on this page
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: _fillAllFrames start
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  Filling document. Initial page load: false
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  attempting document fill
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):INFO:  No forms found on this page
Mon Jun 30 2014 11:04:10 GMT-0400 (Eastern Standard Time):DEBUG: panel showSearchResults started

**Comment by luckyrat** [comment]
Looks like they've changed their site. Works for me with the latest version of KeeFox (although I think you need to force KeeFox to look for the login form when it eventually loads)
