### ISSUE TITLE
Authorise a new connection problem

### ISSUE THREAD

**Issue by krbvroc1** [luckyrat/KeeFox#304]
Running recent 2.27 KeePass (released 7/6/2014) and KeeFox 1.4.2 on Firefox 30.

All of a sudden I keep getting Authorise a new connection dialogs. The odd thing is that the dialog seems unnecessary. There is no where to enter the code. KeeFox and KeePass allows login to KeePass and usage of login data/form filling. The dialog has no minimize or close button so it stays on the screen. I have been hesitant to click 'Deny this request' since things appear to be working. I wonder if this is related to 2.27 KeePass?

**Comment by bobvines** [comment]
I just allowed Forefox to update to version 56.0 (64-bit) and when it restarted, a "KeePass "Authorise a new connection" window" keeps popping up, even though KeePass is already running.  I have no other FireFox or Thunderbird instances running on this computer.
