### ISSUE TITLE
New installations don't always connect correctly with the first attempt

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#306]
When KeeFox and KeePass are being installed for the first time and the user chooses to create a new KeePass database, the KeePass "enable update notifications" dialog prevents KeePassRPC from notifying KeeFox that a database has been opened/saved.

Hence KeeFox continues to report to the user that no KeePass database is open.

Force saving the database in KeePass (and probably various other operations) triggers the state to get updated correctly but that's a clunky workaround so it would be good to find a proper solution.

**Comment by luckyrat** [comment]
I don't understand this bug so it's likely to be punted to v1.6 or closed unless I can somehow find a way to reproduce it reliably when testing fresh installs at a later date.

I've just gone through a test of establishing a link to a fresh install of KeePass and KeePassRPC (from an existing KeeFox install) while the "enable update notifications" dialog is open and can't find any problem.

I don't understand why that dialog being open would cause a problem. Either it does not, or it really is only a problem after a clean install of KeeFox (can't imagine how the Firefox profile state could affect KeePass dialogs though). I suspect that *if* there is an ongoing problem with the initial install, it's caused by some other bug, not the presence of this dialog.

**Comment by luckyrat** [comment]
Can't reproduce.

**Comment by Salomanuel** [comment]
New user, for 3 weeks keefox worked just great, but now I'm currently experiencing it too (and hating it, it was so nice before).
