### ISSUE TITLE
[BUG?] new button dosent work if dragged to non toolbar menus (menu bar, bookmark bar etc)

### ISSUE THREAD

**Issue by zeltak** [luckyrat/KeeFox#316]
Hi

Just reporting that it seems to me the new button dosent work if dragged to non toolbar menus (menu bar, bookmark bar etc)

using arch linux with latest firefox

let me know if any other info is needed as i would be very happy to help try debug this

z

**Comment by luckyrat** [comment]
Is this still a problem?

I'm hoping that Mozilla fixed most of the bugs relating to the new button already but if not we can take a closer look in case there's anything we can do to fix or work around it.

**Comment by luckyrat** [comment]
Not reproducible.
