### ISSUE TITLE
Don't make menu disappear on "Detect forms"

### ISSUE THREAD

**Issue by agrajaghh** [luckyrat/KeeFox#318]
Sometimes KeeFox isn't filling out the forms directly. I have to click on "Detect forms" and then I have to click again on the found entry in the menu. But after clicking on "Detect form" the menu disappears, So I have to open it again. I think it would be good if the menu just stays open, so you can click directly on the entry.

**Comment by luckyrat** [comment]
Closing because the underlying behaviour is baked into Firefox so any change is only possible from a wholesale add-on rewrite when/if Mozilla deem that is necessary.
