### ISSUE TITLE
Allow save to update an existing entry

### ISSUE THREAD

**Issue by nniesen** [luckyrat/KeeFox#319]
Please add an update button, or allow the save button, to update an existing entry instead of always creating new entries (e.g., allow me to pick a Login entry to update the login and KeeFox information). It's extremely annoying that you can only save to a new entry. I have a lot of existing KeePass entries, I keep notes and other information in many of them, and it is not easy to copy data between the old and new entries.

**Comment by nniesen** [comment]
I'd be happy with "allow me to pick a Login entry to update the login and KeeFox information" like the current list that is displayed when the "Logins" button is clicked to choose a login for form completion. I'm not sure why selecting one to update would be that much different than saving a new one but I don't know what you have to work with for APIs. By the way, when I say update I really just need it to associate the existing Keepass entry with the login form I just completed (i.e., add the KPRPC stuff and the KeeFox URL and form fields). I don't really need it to update the password. I just want to bind the login page with an existing Keepass entry.

**Comment by luckyrat** [comment]
> I just want to bind the login page with an existing Keepass entry.

If you are referring purely to binding the URL then that is what's covered in that related issue, #109. If not...

Does saving a new entry and manually deleting the old one from KeePass give the desired result for you? If not (i.e. if you have other data in the existing KeePass entry) you might be able to manually copy and paste the "KPRPC JSON" advanced string from a newly saved "temporary" entry and then delete that new entry.

It gets more complicated with the fields that are not specific to KeeFox (i.e. username, password, URL). I think everyone will have different ideas about what they want to happen, which fields should be updated and which left the same as well as different opinions on the relative priority of implementing those features and different edge cases that they'd need to be able to override.

Sure, there are APIs involved (both unchangeable ones such as the KeePass plugin API and those under our control - principally KeePassRPC) but I think the bigger question is what we want the APIs to support, whether they actually can support that can be answered later. I am always thinking about how to better support modification of existing entries so if I do see any opportunities to make some progress towards better support here I'll do it, but it just might be quite a while before all the pieces fall into place.

**Comment by nniesen** [comment]
Yes, #109 is what I was originally after. Copying the KPRPC, although not ideal, should help for most entries.

**Comment by luckyrat** [comment]
I'm experimenting with some ideas to add this feature. It's unlikely to result in an imminent implementation but I'll keep it updated with any progress I make.

**Comment by luckyrat** [comment]
Made some great progress. I'm alpha testing it in 1.4.103a1 at the moment.

**Comment by solhuebner** [comment]
Great news
