### ISSUE TITLE
improving the "generate new password" function

### ISSUE THREAD

**Issue by jbber** [luckyrat/KeeFox#321]
Hello,

The button "Generate new password" saves the password to the clipboard. This is great, but shouldn't it also create a new entry in the active keepass database?

Here's the problem: yesterday, I generated a password when creating an account on a friend's private website. I was interrupted, and I forgot to save the login/password to my keepass database (I think the dialog box "do you want to save the password to keepass" did not appear when I finished the registration, I don't know why). Then, I started to work on something else, emptying the clipboard in the process. 

So, my account was created, but the generated password was no longer stored anywhere. I didn't notice it until I tried to connect again to the website. As my friend had not implemented yet a "forgot password?" function on his private website, I had no way of retrieving my password! 

Obviously, a part of the problem is that the account creation process wasn't totally well designed on this website, but I'm wondering if keefox should not prevent this kind of problem by adding automatically an entry in the keepass database, instead of just storing the password in the clipboard.

Regards (and btw, thanks for this great plugin!)

**Comment by rolodato** [comment]
I came across this issue from Google, sorry if it's too old.

I had this same problem, and I like LastPass' approach to it. When saving a password, they give you the option of saving it as a new entry or replacing an existing one:

![untitled](https://cloud.githubusercontent.com/assets/829698/6693463/6267532c-cc90-11e4-89e8-cc74b3cc8350.png)

In any case, generated passwords are always saved as `Generated password for example.com`, which I assume is to prevent situations like these. I think it's a helpful option that should be enabled by default.

**Comment by luckyrat** [comment]
#577 is the closest we can ever get to this functionality with KeeFox - it ticks enough of the boxes for this to be considered a duplicate issue I think.
