### ISSUE TITLE
KeeFox option windows to smal in KeeFox 1.4.3

### ISSUE THREAD

**Issue by Siggi0904** [luckyrat/KeeFox#325]
Hi luckyrat,

the size of the option windows in keefox 1.4.3 is not changeable or to small.
Btw it has to many space between the options.

Some of the options aren't shown or not selectable.

I'm using the german translated version.
Here are some screens of the german translated option window.

![keefox 1 4 3 option-window - 01](https://cloud.githubusercontent.com/assets/4992106/4263744/868f3eb4-3bfd-11e4-8e0f-9fe5b56d6851.png)
![keefox 1 4 3 option-window - 02](https://cloud.githubusercontent.com/assets/4992106/4263745/86a75a76-3bfd-11e4-9679-be5df58de79d.png)

**Comment by luckyrat** [comment]
I've reduced vertical space in several places for KeeFox 1.5. Once a beta is available, we can test with German to verify it's fixed this issue.

**Comment by luckyrat** [comment]
In case you missed it, the v1.5 beta is now available at https://addons.mozilla.org/en-US/firefox/addon/keefox/#beta-channel

Please let us know if it's working as expected.
