### ISSUE TITLE
KEEFOX_CHECKED_FLAG_TRUE inserted randomly in fields

### ISSUE THREAD

**Issue by brainfoolong** [luckyrat/KeeFox#332]
Hi,

the string "KEEFOX_CHECKED_FLAG_TRUE" something get randomly set in some fields.
Especially when you are on a "profile editing" form with many profile information on it this is problematic because you maybe don't see that KeeFox replaces a field with this string.
Example when you register a account here: http://forum.nusphere.com/profile.php?mode=editprofile

**Comment by luckyrat** [comment]
I had to make lots of changes to the form selection and filling code to enable KeeFox 1.5 to work with the new multi-process version of Firefox (e10s). In doing so I have verified that checkbox values will no longer be inserted into non-checkbox fields.
