### ISSUE TITLE
Can't save NTLM auth passwords

### ISSUE THREAD

**Issue by datr** [luckyrat/KeeFox#334]
Hi,

I'm using KeeFox on Ubuntu and when I enter a password on a site which uses ntlm authentication I see the bar drop down asking me if I want to save my password. However, clicking on the save password buttons doesn't do anything and my KeePass database is never updated to include the entry.

**Comment by dlech** [comment]
FWIW, I just tested this with KeeFox v1.4.7b3 on Ubuntu 14.04, Firefox 36.0, KeePass 2.28 and it is working.

**Comment by luckyrat** [comment]
I can't replicate this problem but please feel free to re-open if you can explain how to reproduce in KeeFox v1.5.3+
