### ISSUE TITLE
KeePass is already listening for connections Error

### ISSUE THREAD

**Issue by aPollO2k** [luckyrat/KeeFox#335]
Hello,

since the last update i got always an error (see screenshot). KeePass says that KeePassRPC is already listening for connections on the specific ports 12536 and 12566. But there is no other programm or instance who can listen on these ports. 
Netstat says that mono is the tool who listen on this ports. If i close Keepass the ports closed, too. 
I have no idea. It looks like KeePassRPC listen on the ports and detect his own connection as connection from another tool and block itself. 

KeeFox dont get any connection to KeePass.

Im running KeeFox and KeePass with Linux Mint 17 Qiana.
![bildschirmfoto vom 2014-11-07 10 19 25](https://cloud.githubusercontent.com/assets/5796295/4950812/1995874a-6660-11e4-9d14-2c26e366baf2.png)

**Comment by ljgww** [comment]
Worked for me. I had several .plgx files, when I left only one the message disappeared. 
Perhaps changing an extension (of backup versions) could help ?!?
