### ISSUE TITLE
Thunderbird does not find stored passwords

### ISSUE THREAD

**Issue by farkass** [luckyrat/KeeFox#341]
Nowadays ( for 2-3 weeks now) Thunderbird does not find passwords in Keepass.
I have about 10 passwords to load.
Starting Keepass, then starting thunderbird.
The first half of accounts not identified, neither the Keepass connection detected - i have tested this by starting thunderbird first, then only 6-th or 7-th password dialog asked me about starting keepass.
Running KeeFox 1.4.4 , Thunderbird 31.2.0 and KeePass 2.28

Thanks!

**Comment by farkass** [comment]
Keefox 1.4.5 with KeePass 2.28 not retrieveing pop3 passwords with en-US locale.

**Comment by farkass** [comment]
Found the workaroung of applying 1.4.6b2 in other issue.
This has solved my problem.
How should I get new version of it when published?
Will it auto upgrade to any 1.4.6.x or 1.4.7?

**Comment by luckyrat** [comment]
@farkass Best thing to do is install 1.4.6b2 from AMO now that I've uploaded it there: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/

You'll then definitely get automatic updates on the beta channel. If you do nothing it might upgrade automatically to the stable channel but that behaviour has been inconsistent over the years so I'm not sure what Mozilla's current policy is (and it may even differ between Firefox and Thunderbird).

If you want to switch to the stable channel once 1.4.6 is released just install it from AMO once it appears there.

**Comment by farkass** [comment]
Thanks!
