### ISSUE TITLE
KeeFox wants to save new entries for already existing sites

### ISSUE THREAD

**Issue by dfherr** [luckyrat/KeeFox#343]
KeeFox sometimes wants to save a new entry for an already existing website. I'm not sure if this is related to #324 because these website tend to have pretty exhaustive query strings where i encounter these bugs.

Can't really reproduce it reliably. An webiste i encounter this problem often is amazon singin.

**Comment by luckyrat** [comment]
Closing because it's not specific enough (and may have been mostly resolved in v1.5 anyway)
