### ISSUE TITLE
KeePass2 asking the authorization code everytime I start firefox

### ISSUE THREAD

**Issue by franperr** [luckyrat/KeeFox#346]
Since some months, everytime I start firefox, keepass ask for the authorization code. After entering it, it works normally, but there is no authorized client in KeePass > Tools KeePass RPC (KeeFox) options.
I'm using xubuntu 14.04 i386, with keepass2 from the repositories (version 2.25+dfsg-1ubuntu0.1), firefox from the repositories ( version 34.0+build2-0ubuntu0.14.04.1) and keefox 1.4.4.
I've tried to uninstall, cleaning all the config files of keefox and keepass, install again and no luck. I've also check that firefox was not deleting password following issue #252.
The weird thing is that I have another computer running ubuntu gnome 14.04 and it works perfectly.

**Comment by dkebler** [comment]
I'm having the same issue.  But it was not resolved by following advice at #263.  See my post at that issue.
