### ISSUE TITLE
Not working with Firefox 34 OSX

### ISSUE THREAD

**Issue by nedson** [luckyrat/KeeFox#347]
Does not work with Firefox 34.0 OSX 10.10.1. 

Diaglog says Keefox cannot install because of incompatibility with Firefox 34.0 when attempting to install from the official Firefox Addons site.

**Comment by luckyrat** [comment]
The build here should work now: https://github.com/luckyrat/KeeFox/releases/tag/v1.4.5b1

**Comment by nedson** [comment]
cheers!
