### ISSUE TITLE
Make it work with e10s

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#350]
We need to make sure KeeFox will work with the new [multi-process Firefox](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox).

I've been trying to understand e10s and what it means for KeeFox for a while now but have no idea how to fix individual error messages without making large scale changes to the addon's architecture. So I'll start looking into the latter soon and perhaps come across some quick wins that will allow me to make some targeted changes to enable e10s support despite the incompatible architecture.

The nature and potential scale of this work means it's impossible to make any estimates of when it might be complete (or even what form "complete" will take) so my first task will be experimenting with some ideas in order to learn more about e10s and how KeeFox will be expected to interact with it.

I'll keep this issue updated with progress but I won't be looking at compatibility issues with non-Firefox applications until much later in the process.

@dlech I don't suppose you know anything about Thunderbird and e10s? I couldn't find much information when I looked but it feels as though something this fundamental has the potential to cause some serious cross-application compatibility problems.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1067615

**Comment by dlech** [comment]
Nope, sorry I don't know anything about e10s at all really. But from looking at it, I would guess that given the current state of Thunderbird development that it will not be used/turned on in Thunderbird.

**Comment by luckyrat** [comment]
That's my guess too (I can't really see how Thunderbird would benefit significantly from it anyway). Apparently Firefox has had support for splitting scripts into (and then messaging between) chrome and frame (content) since v4, albeit with bugs until v19. If that support has made it into Thunderbird it should make this task a lot easier.

**Comment by luckyrat** [comment]
I'm making progress on this but have been at it nearly full time for the past couple of weeks and still don't think I'm that close to understanding it! Looks like it will be a huge amount of work which I will hopefully have time to do before e10s is released but it's such a large scale change that I can't guarantee I'll be able to complete it, especially now I have the more imminent #356 to worry about too.

I saw a hint that Mozilla might not get around to releasing e10s to the stable channel until December. If that's the case we have a better chance but the last official word was that it would be at least 6 months earlier than that.

I'm working on a separate branch which I'll push as soon as I have at least one feature working and am sure that the new architecture is going to work as I've planned.

The positive that I'm desperately clinging to is that after all this work we should have better form detection, or at least be in a position where improving it would be much easier than it currently is.

**Comment by luckyrat** [comment]
I've now pushed up an e10s branch which contains a whole host of changes. Most of these were required in order to allow KeeFox to work with e10s; some changes are just better ways to do things since I didn't want to re-implement an old way when it could be improved with little or no extra work.

There's still work to do before it's ready to use but I've finally got it to the stage where I think I understand everything that needs to be done and can roughly estimate we need another 100-150 hours to get it to a stable state. I'm not even using it myself yet so we're still a while away from beta testing but I wanted to get it pushed up mainly since 500 hours of work is a lot to lose and it's probably in a state that someone else could finish the work if I get hit by a bus.

There are definitely regressions but also some improvements in form filling accuracy and more to come. I expect it will be impossible to exactly recreate all useful behaviours but by the time I get it to beta I think the number of improvements will vastly outweigh the occasional regression.

Since nearly every line of every file has been changed, I can't expect any automated or manual review process to pick out the actual changes and I've therefore taken the opportunity to normalise line endings and space/tabs too (I think - git is a little confusing in that regard!) Anyway, the scope of architectural changes that were required make it pretty pointless to review the diff to master (92 files; 35K additions and deletions so far).

I've chucked the XPI into Thunderbird and it (unsurprisingly) does not work. One clue is a complaint in the error console about "aCallback.apply is not a function" from within Timer.jsm. I guess that means we're passing some invalid function reference when starting the timer to check for KeePass' logged-in state. Haven't had a chance to investigate further yet but maybe the fact we made changes in this area on master while I was working on this e10s branch has led me to apply a bad git merge. Hopefully it's a fairly simple fix.

The main thunderbird implications I'm aware of are:
* Removed old toolbar system (pre-Australis) - In theory that's quite isolated from the modal dialog popups used in TB.
* Made commonDialog.js run in strict mode - now all files are "use strict" so the Mozilla reviewers will be happy.
    * I had to tweak the definitions of the Cc, Ci and Cu shortcuts so there might be some side effects there - I remember they caused us some problems a few years back.
* Removed the FF3-era notification bar (save password notifications, FAMS messages, sensitive logging warning, etc.) since it can't be called from a frame script (where all the form detection happens now). It would therefore be good to remove KFUI.js:_getNotifyBox() if it's not used but maybe TB still has a use for it?

In the coming weeks I'll spend a while updating github issues with what I've discovered in the past few months and try to get the code up to scratch (particularly the notifications and a few form detection issues).

I'll post another update once I think it's safe and complete enough to use for everyday browsing.

**Comment by dlech** [comment]
In Thunderbird, the only thing that has ever worked is the commonDialog stuff and the options. There is no toolbar button, no FAMS or other notifications, etc. So, really the only implications are the "use strict" and Cc/u/i changes.

**Comment by dlech** [comment]
Given the extent of the changes you are making here, perhaps you should call it version 2.0 instead of 1.5. :wink:

If there are any specific tasks you would like help with, let me know, otherwise I will take a look at Thunderbird and whatever else tickles my fancy when you are a bit farther along.

**Comment by luckyrat** [comment]
> Given the extent of the changes you are making here, perhaps you should call it version 2.0 instead of 1.5. :wink:

I might yet; I've been tempted but I'm not sure it's justifiable from the point of view of the end users... although maybe if magically all form filling, etc. is noticeably better it could be worth considering. It depends a lot on how much time I have before Mozilla drop the e10s bomb towards the release channel.

Thanks for the offer of help. If I can spend most of the next couple of weeks on it we should be in a better place to pick and choose the priority tasks to get it to a beta release. I've got a good idea how to implement most of the issues that are on the cards for 1.5 so if anything takes your fancy but you're wondering about the best way to approach it just give me a shout (as usual, I'll do my best to assign myself to anything I am working on so everything else is fair game!)

**Comment by mscrivo** [comment]
FYI Firefox Developer Edition (to be released this week) is going to have e10s enabled by default.  Would it make sense to maintain beta builds of this branch for people wanting to test?

**Comment by luckyrat** [comment]
Unfortunately this branch is not suitable for beta testing yet. I've been running it the past few days on my daily Firefox (38) to begin assessing its suitability for alpha testing (i.e. download via github releases rather than AMO) and hope to merge this branch into master within a week and then it'll be easier to evaluate how much more work is needed before we can package up a release for alpha testing (the list of outstanding issues is difficult to filter on at the moment - lots will be resolved once this branch merges into master).

I thought that e10s was still too buggy to be enabled by default outside of Nightly so they were going to prompt users to enable it rather than force it on everyone but either way, it would be great to get a working KeeFox build for early adopters ASAP.

**Comment by luckyrat** [comment]
The e10s branch is now merged to master. 24 issues remain but lots of them should be fairly quick to address and some can be punted to a later version if the Firefox e10s progresses towards release too quickly.

We won't need to have addressed them all before releasing an experimental build but we do need to make a bit more progress and I need to review those areas that might result in version compatibility problems as people up/downgrade. Obviously we'll need to be even closer to completion for a beta build.

#363 and #358 would probably be fairly quick fixes for @dlech to take a look at if you've got time. Otherwise, feel free to tackle anything on the 1.5 milestone list that grabs you as long as I've not already assigned it to myself.

**Comment by mscrivo** [comment]
Thanks Chris.  I'm trying it out now, but I'm running into a bit of an issue.  I've successfully built KeepassRPC.plgx and placed it in the plugins folder.  Version shows as 1.4.100.0.  I also built the XPI and installed it in my Firefox Dev Edition 40 (x64) and that went fine, version shows as 1.4.99a1.  However it doesn't seem to be communicating with Keepass.  When I click the keefox icon, I try clicking on "Login to Keepass", which brings up the Keepass login form, but after logging in, it's not connected, I still see "Login to Keepass" in the keefox menu.  Any idea what I'm doing wrong?

**Comment by kulmegil** [comment]
Can some1 share a build for e10s? At least binary part (need new .plgx)?

**Comment by luckyrat** [comment]
@mscrivo: Try the latest version. There was a bug where databases which did not contain KeeFox tutorial sample entries would never be seen by KeeFox.

@kulmegil: It's not ready yet but soon.

**Comment by luckyrat** [comment]
An experimental build is now available: https://github.com/luckyrat/KeeFox/releases/tag/v1.4.101a1

Please read the associated release notes.

**Comment by luckyrat** [comment]
Updated build with new features and bug fixes: https://github.com/luckyrat/KeeFox/releases/tag/v1.4.103a1

There's not much holding up a beta release now. @dlech: Do you think you'll have time to take a look at Thunderbird support in the next week or two? (#363 and #358 would be handy too but they don't have to be done before a beta release).

**Comment by mscrivo** [comment]
The 103a1 build is working very well for me so far.  I'll let you know if I run into any issues.  The UI changes look great too!

**Comment by dlech** [comment]
Yes, I should be able to set aside some time.

**Comment by luckyrat** [comment]
In the absence of any information to the contrary despite a few weeks of public beta testing, I'm going to assume that this task is finished. Hooray!

**Comment by dlech** [comment]
*Gives @luckyrat a handshake, a high-five and a big pat on the back for all of the many hours that this took*
