### ISSUE TITLE
Firefox 35

### ISSUE THREAD

**Issue by GHuzrB** [luckyrat/KeeFox#355]
Using WinXP & KeeFox 1.3.1 (prefer 3 button ver. to new 1 button). Just updated Firefox from 34.0.5 (KeeFox worked fine) to Firefox 35.0. Now % showing up in buttons, in the KeeFox button drop-down, and in the options area. The other two buttons are grayed out. KeeFox not loading properly? Still working fine with Thunderbird 31.4.0. Joined Zoho forum, but no way to post new topic. Now trying GitHub.
Thanks for any help and thanks for creating such a useful extension.

**Comment by luckyrat** [comment]
Yeah, % showing up in buttons indicates KeeFox isn't loading. Generally that would be down to a conflicting add-on but when you're running an old version of KeeFox on an unsupported OS it is very likely that you've just hit the end of the road. I'm not sure exactly why 1.3.1 would have stopped working but unfortunately I don't have time to investigate or fix it.

You're welcome to try yourself but I know for a fact that KeeFox will get much slower in 12 weeks (Firefox 37) and will break entirely whenever Mozilla release the next big Firefox update (scheduled for summer but I expect it will slip to later in the year). There will be no way to monkey-patch older versions of KeeFox into working with those new versions so even if you can get 1.3.1 working on FF35 and 36, you're not buying yourself much time.

If there is anything in particular you'd like changed to the new version that isn't already covered in a feature request, feel free to ask but given the massive Firefox changes that are quickly approaching, I'm afraid there is close to a 100% chance that I won't get around to focussing on any other improvements for many months.

**Comment by luckyrat** [comment]
I don't think there's anything specific to KeeFox I can do here at the moment but I'm wondering about the problem you had asking for help on Zoho. I occasionally get anonymous messages saying someone couldn't find the "new topic" button but I never have that problem and plenty of other people manage to post topics so I've started wondering if there is an addon like adblock plus which is breaking the Zoho site for some users.

I see a "New Topic" button immediately to the left of the search box in the top right of the page. Does it appear for you now?

Thanks.
