### ISSUE TITLE
KeeFox is slow in Firefox 37+

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#356]
All communication with KeePass will be roughly 10x slower according to the timing tests I performed in #221 as a result of Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1080262

I have no idea how or if it is possible to work around that bug. My best guess is that we'll have to throw the data backwards and forwards between JS and C memory spaces, potentially converting between binary and chars at some point too - but I doubt that process will be fast enough to make it a worthwhile workaround.

One possibility is to switch to using the WebCrypto API instead of NSS ctypes but that API is not exactly aimed at such low-level crypto requirements so there is no guarantee it will be a suitable replacement.

**Comment by luckyrat** [comment]
I have a solution in the works (https://github.com/luckyrat/KeeFox/tree/KPRPCWebCrypto).

### In brief

I'll swap out the ctypes AES decryption algorithm for a WebCrypto AES decryption algorithm. Users of Firefox 37+ will find KeeFox is a bit faster with large password databases. Users of older Firefox versions may notice a slight slow down but it should be imperceptible on FF35 and FF36.

### More detail

I will completely remove the ctypes implementation for the next KeeFox release. In recent Firefox versions that "10x faster" implementation has got at least twice as slow as when I initially implemented it and the pure Javascript implementation has increased in speed so the difference even on FF35 and FF36 should be negligible.

Firefox 37 contains performance regressions that make the "fast" implementation now significantly slower than the old Javascript-only algorithm, as well as the previously referenced Firefox bug that causes the process to fail before completing decryption. That means with the current version of KeeFox there is a 400% penalty applied in FF37 for the failed use of ctypes compared to the 10% penalty that was found when ctypes failed with earlier Firefox versions.

Balanced against a 4x penalty, the roughly 1.5x penalty of removing ctypes on FF35 and FF36 has to be taken on the chin. It's possible the cost will be higher for users that have still not upgraded to the latest Firefox version but since it will top out at about a 10x penalty on very old Firefox versions I think it's manageable and certainly nowhere near the level of slow down we'd need to see to disadvantage users of modern Firefox versions.

A side-effect of this change is a slight increase in minimum supported version to v22. That's still much further back than we're committed to supporting so no big deal.

However, we have to use promises which are only supported in v29+ so if it turns out that older versions of Firefox baulk at having that syntax available in unexecuted functions we'll have to bump to 29. That's a bigger issue since ESR 24 has only been unsupported for a few months, although it's still justifiable if we have to do it.

NB: Support for e10s is likely to require a significant jump in minimum version support (possibly even breaking support of ESR 31) but that'll be dealt with in #350.

### Benchmark data

* Averaged over 5 runs
* Figures in ms for decryption time of database with 3000 entries (~2.5MB of encrypted data over KPRPC)
* It's on a fast PC with hardware AES support so it's quite feasible to see similar delays with much smaller databases on older hardware.

Firefox version | Javascript (sjcl) | ctypes | WebCrypto
------------ | ------------- | ------------ | -------------
36 | 645.7 | 537.4 | FAIL
37 | 618.6 | 2296.4 then FAIL | 166.2
38 (e10s disabled) | NOT BENCHMARKED | NOT BENCHMARKED | 159.8

### Comment

The slow performance of ctypes before it reaches the failed line of code is interesting because it indicates a serious performance regression in Firefox. The affected part is just creating and copying ArrayBuffers so it should be pretty simple shifting data around memory but it's at least an order of magnitude slower on 37 vs 36.

Thankfully this is now just of academic interest but it is a shame that our previously fast solution has actually got so much slower that even without the failure it would have been 5x slower than the original "slow" Javascript implementation. Quite an odd state of affairs given how much performance regression testing gets automatically thrown at Firefox for every build - I can only assume that there are some gaps in the test coverage of TypedArrays.

**Comment by luckyrat** [comment]
Fixed by #362

**Comment by Noitidart** [comment]
Awesome topic! Thanks for sharing your research on those timings!
