### ISSUE TITLE
KeeFox - Missing KeePass Arguments (Keyfile)

### ISSUE THREAD

**Issue by lycano** [luckyrat/KeeFox#357]
When using a database with a keyfile KeeFox does only load the database but the field "Key File" is set to "none" after clicking "Run Keypass" from within keepass.

**Comment by luckyrat** [comment]
I can't replicate this. Are you sure you haven't disabled the KeePass advanced option "Remember key sources"?

If that option is enabled, please provide exact step-by-step instructions to create this problem and tell us about your system, versions, etc.

**Comment by lycano** [comment]
I was expecting that the list of Keyfiles in the KeePass dialog is the same as when starting KeePass via KeeFox manually but instead I had to locate the keyfile manually. After selecting the keyfile this information stays there whenever i use run KeyPass command. Seems to me this is a user error. Closing.
