### ISSUE TITLE
Version check breaks interoperability with Thunderbird builds

### ISSUE THREAD

**Issue by ThoriumPrime** [luckyrat/KeeFox#360]
Version check currently being done in:
https://github.com/luckyrat/KeeFox/blob/master/Firefox%20addon/KeeFox/chrome/content/commonDialog.js#L116

The version check is done to work around the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=551919

The version check breaks (and can be expected to continue to break) interoperabillity with certain special builds of Thunderbird. For instance Fossamail x64 version 25 will break, while v 24.7 still works fine. 

We need to detect the difference between using string and numeric identifiers in some other manner, for instance using try/catch to try reading a string identifier. If it throws an exception, it is a numeric identifiers. (Thanks to David Lechner for the helpful suggestions).

**Comment by luckyrat** [comment]
Note that the next release of KeeFox (~February) will up the minimum version to 22 (see #356).

I don't see any problem with upping it to 25 for Thunderbird while Firefox stays at 22. It looks like that would simplify this issue significantly?

CC @dlech

**Comment by dlech** [comment]
Due to Thunderbird's slower release cycle these days, I think lots of people will still be on TB24. Also, the version in this issue reports itself as 25 even though internally it is 24, so it would still be broken. I think this issue is simple enough to just fix.
