### ISSUE TITLE
Cannot choose "Never" option for entry-specific auto-fill behavior

### ISSUE THREAD

**Issue by tgp1994** [luckyrat/KeeFox#363]
There's a particular site that has a lot of username/password fields, which are unfortunately mistaken for the real login form for logging in. Thus it would make sense to me to disable auto-filling on this site, however, in the KeeFox tab for the particular site entry, I cannot change the Auto-fill behavior to "Never". If I try to select it, it defaults back to Use KeeFox setting, regardless of whether or not the KeeFox setting is always or never. I can also choose the Always option here, but that's not what I'm trying to accomplish.

Hope this can be fixed!

**Comment by luckyrat** [comment]
Thanks for reporting it. I'll try to fix it soon.

You can workaround by ensuring auto-submit is set to "use KeeFox setting".

**Comment by luckyrat** [comment]
Low priority for v1.5

**Comment by dlech** [comment]
This is working for me in 1.5.0b1. I have a feeling that the massive changes for e10s fixed it.

**Comment by luckyrat** [comment]
The problem only appeared if auto-submit is set to "Never". I'm all for spontaneous bug fixes but I don't recall doing any work in this area and it looks like the problem is still there on my machine.

**Comment by dlech** [comment]
> The problem only appeared if auto-submit is set to "Never"

In the KeeFox options in Firefox or in the per password entry options in KeePass?

**Comment by luckyrat** [comment]
the per password entry options in KeePass.

**Comment by dlech** [comment]
OK. I see the problem now. It is 100% in KeePass.
