### ISSUE TITLE
TIP:  Fixing RPC Plugin not Loading, Linux-Keepass 2.28,  Old Mono version is the issue

### ISSUE THREAD

**Issue by dkebler** [luckyrat/KeeFox#364]
For Keefox users on Linux upgrading to Keepass 2.28 and getting errors loading RPC plugin here is my post at sourceforge that fixes this issue.  

https://sourceforge.net/p/keepass/discussion/329220/thread/086c0a71/

================
For those getting errors loading plugins when using Keepass 2.28 in Linux even if you have mono loaded is that you need better than the 3.28 version of Mono which is the current default package in the ubuntu library.

I loaded mono 3.12 and these errors went away.  Follow the directions here.
http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

I loaded mono complete but others say you just need to load mono-dcms.  I first had to uninstall 3.2.8.
https://sourceforge.net/p/keepass/discussion/329221/thread/d6f5b5b5

**Comment by dlech** [comment]
KeePassRPC works just fine for me in Ubuntu 14.04 with the default mono 3.2.8 package. I don't think the errors you were seeing were because of the mono version.

**Comment by luckyrat** [comment]
As @dlech says, there was obviously something else going on with your system but none-the-less those links could prove useful to others searching for solutions to similar problems so thanks for taking the time to post.
