### ISSUE TITLE
Is it possible to fill 'advanced' attributes?

### ISSUE THREAD

**Issue by psteinforth** [luckyrat/KeeFox#365]
Hi,

is it possible to fill a formular field with a custom attribute saved at the KeePass 'Advanced' tab?
Example:
- Save a String field 'customerID' with value '12345' at the advanced tab.
- Is there any way to use '12345' at the 'KeeFox' -> 'Form fields' tab as 'Value'? Can I use a variable name like the default placeholder '{USERNAME}'?

Best regards
Patrick

**Comment by luckyrat** [comment]
Not directly but for some situations you can use a KeePass placeholder in the main KeePass username field like this:

{S:customerID}
