### ISSUE TITLE
Nonstandard form field name/id not recognized even when explicitly configured in options

### ISSUE THREAD

**Issue by Mooninaut** [luckyrat/KeeFox#367]
On my credit union's website at https://www.centralink.org/ISuite5/Features/Auth/MFA/Default.aspx , KeeFox does not detect the User ID field and does not fill in the form. In KeePass, I opened the entry for that url, KeeFox tab, Form fields subtab and entered Name "ctl01$Main1$UserIDTextbox", Value "{USERNAME}" (fixed), Id "ctl01_Main1_UserIDTextbox",  for page 1 of that form. KeeFox still does not detect the User ID field.

I am using KeePass 2.28, KeeFox 1.4.6 and Firefox 35.0.1 on Windows 7 Ultimate SP1 64-bit.

The XHTML source for the field is as follows:

```xhtml
<input name="ctl01$Main1$UserIDTextbox" type="text" maxlength="20" size="20" id="ctl01_Main1_UserIDTextbox" class="input" AutoComplete="Off" />
```

I believe this issue occurs because this form does not have a password field, being a two-part login form, and also does not use a standard name for the login field. This situation avoids all the heuristics KeeFox uses to detect username fields.

KeeFox has a secondary mechanism, user-configured form field names and IDs that also fails in this situation, because only a hardcoded set of defaults, not user-configured field names are included in the initial check for fillable form fields.

The KeeFox log file when loading that page is as follows:

> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: Location changed.
> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: Removing all matched logins
> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: setupButton_ready start
> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: Setting widget status
> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: setupButton_ready end
> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: onStateChange accepted
> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: nouid
> Fri Feb 06 2015 15:42:42 GMT-0500 (Eastern Standard Time):DEBUG: onStateChange: end
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domEventListener: got event DOMContentLoaded
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: Returning configuration from cache
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domEventListener: trying to load form filler
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):INFO:  Filling document. Initial page load: true
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):INFO:  attempting document fill
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: Returning configuration from cache
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: fillDocument processing 1 forms
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: about to get form fields
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: hidden
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: text
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: proccessing...
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: text
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: proccessing...
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: submit
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domtype: submit
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: usernameIndex: -1
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: actualUsernameIndex: 0
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: otherFields.length:2
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: no password field found in this form
> Fri Feb 06 2015 15:42:44 GMT-0500 (Eastern Standard Time):DEBUG: domEventListener: form filler finished

**Comment by luckyrat** [comment]
> KeeFox has a secondary mechanism, user-configured form field names and IDs that also fails in this situation, because only a hardcoded set of defaults, not user-configured field names are included in the initial check for fillable form fields.

I would expect you to be able to override this behaviour using a custom text field name/id white-list override in the KeeFox [site-specific settings](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options#keefox-per-site-options-dialog) for that domain. I think you're saying that is not working for you. Is that correct?

Might be worth restarting Firefox between configuration changes just in case that helps (though it shouldn't be needed so let me know if it is!).

**Comment by Mooninaut** [comment]
Okay, I see the problem. I was unaware that there are two completely different places to edit form-specific data, firstly in the Firefox add-on, "site-specific settings" and also in KeePass2, Edit Entry, KeeFox tab, Form fields subtab.

I added a whitelist entry for the site, but I don't understand why this was necessary. Is there a reason that KeeFox doesn't include the form field names from the database as part of the whitelist by default? Having two places to configure essentially the same thing is confusing to me. I wasn't even aware that "site-specific settings" in the Firefox add-on existed before now.

**Comment by luckyrat** [comment]
> Is there a reason that KeeFox doesn't include the form field names from the database as part of the whitelist by default?

Yeah, performance is a massive concern, although such a change would also be a little confusing for people that already know how it works at the moment (there may be a need to allow people to exclude specific form field names from being automatically whitelisted... which might be even more complicated than the current situation). Several hundred entries multiplied by several form field names is a huge amount of data to have to process for every single page that Firefox loads.

Although both places to configure form field data seem similar, they are useful for different things (as you've now noticed) - for site-specific settings you can adjust behaviour for many KeePass entries on a single site and for the KeePass entry KeeFox tab you can adjust the behaviour of a single entry on many sites.
