### ISSUE TITLE
RPC plugin not able to maintain/save authorizations

### ISSUE THREAD

**Issue by dkebler** [luckyrat/KeeFox#369]
Opening this because none of the three closed related issues #235, #252, #346 is resolving the issue for me nor any info in the troubleshooting guide.  
---------------
ubuntu 14.10/mint 17.1.
I am running mono 3.12.0-0xamarin4
Like the others it "just started to happen :-)" a few days ago.
FYI Running RPC plugin 1.4.4 and keefox 1.4.6.

I followed @TobiX 's advice to remove the keypair folder but that did not resolve the issue.
This is the related mono bug https://bugzilla.xamarin.com/show_bug.cgi?id=19274 which apparently have been fixed.  I checked the permissions on that directory and it's fine, 700.

I followed advice to set security to low but when I restart keepass the rpc has reset it back to medium and still the issue continues.

I did a minor update of mono from 3.12 marin3 to 3.12 marin4 but that did not resolve the issue.

I followed all the advice in the troubleshooting.  (FF was not set to delete anything)

I deleted all the rpc sfuff (custom section) of the keepass config file (was regenerated)

I deleted the cert.p12 in the  KeepassRPC config directory (was regenerated)

The issue remains. Unfortunately I run three profiles of firefox so it's not particularly fun to reset the authorization three times each time I start keypass (which fortunately is only at boot)

See the warning toward the bottom of this log.

Any further suggestions/advice??

````
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):Logging system initialised at Thu Feb 19 2015 08:28:42 GMT-0800 (PST)
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  KeeFox initialising
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  KeePass install location found in preferences: /usr/lib/keepass2
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  KeePass EXE found in correct location.
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  Looking for the KeePassRPC plugin plgx
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  KeePassRPC plgx found in specified or default location.
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  Mono install location found in preferences: /usr/bin/mono
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  Mono executable found in correct location.
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  Checking and updating KeePassRPC installation settings
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  KeePass is not running or the connection might be established in a second...
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  KeeFox initialised OK although the connection to KeePass may not be established just yet...
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  Created KeeFox widget
Thu Feb 19 2015 08:28:42 GMT-0800 (PST):INFO:  Testing to see if we've already established whether KeePassRPC is connected.
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  attempting document fill
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  No forms found on this page
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  attempting document fill
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  No forms found on this page
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  attempting document fill
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  No forms found on this page
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  attempting document fill
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  No forms found on this page
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  attempting document fill
Thu Feb 19 2015 08:28:43 GMT-0800 (PST):INFO:  No forms found on this page
Thu Feb 19 2015 08:28:44 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:44 GMT-0800 (PST):INFO:  attempting document fill
Thu Feb 19 2015 08:28:45 GMT-0800 (PST):INFO:  Filling document. Initial page load: true
Thu Feb 19 2015 08:28:45 GMT-0800 (PST):INFO:  Websocket connection opened
Thu Feb 19 2015 08:28:45 GMT-0800 (PST):WARN:  KeeFox was not allowed to connect, probably because you entered the connection password incorrectly. Further info may follow: Stored key not found - Caused by changed Firefox profile or KeePass instance; changed OS user credentials; or KeePass config file may be corrupt
Thu Feb 19 2015 08:28:45 GMT-0800 (PST):INFO:  Disconnecting from RPC server
Thu Feb 19 2015 08:28:45 GMT-0800 (PST):INFO:  KeeFox paused.

more.....deleted for brevity
````

**Comment by dlech** [comment]
> FYI Running RPC plugin 1.4.4 and keefox 1.4.6.

These versions do not match. Try updating the RPC plugin. Also, there is a Debian package available via PPA. You could use it instead. See <https://github.com/luckyrat/KeeFox/wiki/en-|-Installation-|-Linux>.

**Comment by dkebler** [comment]
I took the plugin from the mozilla profile directory after updating to
1.4.6 and copied it to my keepass lib dir.   Keepass then says it's still
1.4.4.
Shouldn't the add on 1.4.6 come with the matching copy of rpc?.  If not
where is it hiding?

Despite this....I don't think this is the issue as I was using 1.4.4b with
1.4.4 plugin and it was doing the same thing.

I've used the ppa before.  Better to just manually copy it if I just know
where to find a copy.

On Thu, Feb 19, 2015 at 11:04 AM, David Lechner <notifications@github.com>
wrote:

> FYI Running RPC plugin 1.4.4 and keefox 1.4.6.
>
> These versions do not match. Try updating the RPC plugin. Also, there is a
> Debian package available via PPA. You could use it instead. See
> https://github.com/luckyrat/KeeFox/wiki/en-|-Installation-|-Linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luckyrat/KeeFox/issues/369#issuecomment-75114346>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by dkebler** [comment]
followup.
updated to 1.4.6b2.  Copied over the rpc plugin from profile directory,
start keepass....keepass plugins window still says 1.4.4.
So loaded the ppa back in.  ppa says 1.4.6 available.  I install.  check to
see if the file really got put in the lib/keepass2 folder....yes.... Start
up keepass, plugins window still says 1.4.4

As I said this may not be the issue but as it stands I can't even get 1.4.6
rpc plugin loaded to see.

On Thu, Feb 19, 2015 at 1:09 PM, David Kebler <d@kebler.net> wrote:

> I took the plugin from the mozilla profile directory after updating to
> 1.4.6 and copied it to my keepass lib dir.   Keepass then says it's still
> 1.4.4.
> Shouldn't the add on 1.4.6 come with the matching copy of rpc?.  If not
> where is it hiding?
>
> Despite this....I don't think this is the issue as I was using 1.4.4b with
> 1.4.4 plugin and it was doing the same thing.
>
> I've used the ppa before.  Better to just manually copy it if I just know
> where to find a copy.
>
> On Thu, Feb 19, 2015 at 11:04 AM, David Lechner <notifications@github.com>
> wrote:
>
>> FYI Running RPC plugin 1.4.4 and keefox 1.4.6.
>>
>> These versions do not match. Try updating the RPC plugin. Also, there is
>> a Debian package available via PPA. You could use it instead. See
>> https://github.com/luckyrat/KeeFox/wiki/en-|-Installation-|-Linux.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/luckyrat/KeeFox/issues/369#issuecomment-75114346>.
>>
>
>
>
> --
> Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
> David
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by luckyrat** [comment]
> when I restart keepass the rpc has reset it back to medium

This sounds strange and suggests that the underlying problem is related to your KeePass installation's ability to save its config file. Try checking the file permissions for the config files? http://keepass.info/help/base/configuration.html

The KPRPC version is often lower than the KeeFox version. It has not been increased since KeeFox 1.4.4 so that version mismatch is expected (it saves people from having to upgrade the plugin with every small change to the addon).

**Comment by dkebler** [comment]
As I said it my post.  I deleted the part of the xml file
(~/.config/KeePass/KeePass.config.xml related to rpc and upon starting
keepass it opened and wrote that information back to the config xml file.
So it can write to that file no problem.  I doubled checked and it has
owner write permission (644).

Just for grins I deleted (well moved to a copy) both of the
KeePass.config.xml both local ~/.config/KeePass and global
(usr/lib/keepass2).  Open keepass.  New files were written.  then set new
authorizations.  Close keepass.  Open keepass....YEA not more requests!

Now just the hassle of recovering all my settings in the original config
files :-(..

So this then another thing to try for those having this issue.

Guess you can close this.  Thx.

**Comment by luckyrat** [comment]
Glad it's fixed!

My suspicion is that something previously prevented KeePass from writing to the local config file so it fell back to writing into the global file. The priorities of all the different config files have sometimes played strange tricks like this so transient write problems to specific config files can result in some unusual behaviour. Whether that transient problem was caused by KeeFox, KeePass, 3rd party app, OS or user would be pretty tough to figure out at this stage but if anyone else comes across this and can add more data to the issue we might all learn something useful eventually :-)
