### ISSUE TITLE
Omit "www." prefix during URL matching

### ISSUE THREAD

**Issue by Leonid-SPB** [luckyrat/KeeFox#372]
I think it would be good to omit "www." prefix during URL matching. 
So if we have a record like "example.com" in database it will match URLs: "http://example.com", "http://www.example.com", "https://example.com", "https://www.example.com"

**Comment by dlech** [comment]
It actually matches anything with "example.com", not just and extra "www.". You can change this behavior by checking the "Require more accurate URL matching" on the URLs sub-tab of the KeeFox tab on a per-entry basis.

**Comment by Leonid-SPB** [comment]
I'm using KeePass 2.28 and KeeFox 1.4.6
I have a record "outofmilk.com" in my KeePass database. When I enter URL "outofmilk.com" KeeFox recognizes it and fills the form. But when I enter "www.outofmilk.com", KeeFox can't fill the form.

**Comment by dlech** [comment]
In that case, you could add "www.outofmilk.com" on the URL tab so that the same entry will match that host name too. I thought that KeeFox stripped off the subdomain ("www.") when doing host matching, but apparently it does not.

**Comment by Leonid-SPB** [comment]
Yes, I can. But it is very inconvenient and there are lot of records in my base. Probably stripping off "www." would be nice enhancement for some future release

**Comment by luckyrat** [comment]
I suppose it might be acceptable to do this when "require more accurate URL matching" is not checked.

I probably won't do it though - I'd rather concentrate on integrating with Mozilla's list of known top-level domains instead. Partly that's because I don't think there should be a special case for "www" above all other possible subdomains (but at the moment it's not possible to know what part of the hostname is registered to the same company at the domain registrars).

**Comment by luckyrat** [comment]
KeeFox 1.5 will include the top-level domain detection feature I mentioned previously. That means that default behaviour will change to match by domain only, with increased priority given to entries that more closely match.

In this case that means an entry stored with a URL of https://www.example.com will by auto-filled before an entry stored with https://example.com but if the latter is the only entry available it will still be used.

It's a different way of approaching the problem than requested here but the end result should be the same (or better).

#438, #439 and #442 are all related to this work although the main bulk of it is the new .NET library I created at https://github.com/luckyrat/domain-public-suffix
