### ISSUE TITLE
Unable to register KeePassRPC as Plugin in KeePass2 2.24

### ISSUE THREAD

**Issue by mbutz** [luckyrat/KeeFox#373]
Hi,

I am trying set KeeFox up which I managed on other systems without any problem.

KeePass2 won't recognize the `KeePassRPC.plgx` which I copied from 

```~/.mozilla/firefox/[myProfile] /extensions/keefox@chris.tomlinson/deps/```

to

`/usr/lib/keepass2/`

I also tried:

`/usr/lib/keepass2/plugins`, `/usr/share/keepass2/` and `/usr/share/keepass2/plugins`.

From earlier installations I know that KeePass will show a dialog on the first run, saying that it is about to register a new plugin. This does not happen. Also (and consequently) I will find no entry in KeeFox under Tools > Plugins. I tried to install KeePass2 as well as KeeFox several times.

My setup:
Linux Mint LMDE (Debian Jessie)
Mono: 3.0.2
KeePass2: 2.24
KeeFox: 1.4

I'd be grateful for any hint what else I could try.

**Comment by mbutz** [comment]
Went through:

```http://sourceforge.net/p/keepass/discussion/329220/thread/086c0a71/ ```

and have now:

```Mono JIT compiler version 3.12.0```

No change. Plugin will still not be compiled and does not show up in KeeFox.

**Comment by luckyrat** [comment]
What about following the link Paul gave to enable plugins in Linux/Mono:
https://sourceforge.net/p/keepass/discussion/329221/thread/d6f5b5b5

Does that help?

**Comment by mbutz** [comment]
No luck with that: I have installed `mono-complete`, `mono-dcms`. According to your hint I also added `mono-gmcs`. `KeePassRPC.plgx` at the right spot but will still not be recognised.

**Comment by dlech** [comment]
I know for a fact that plgx plugins (all of them, not just KeePassRPC) do not work in Mono 3.0.x due to a bug in Mono so that explains the original problem.

I also have Mono 3.12 on my Mac and KeePass 2.28 is it is working there with plugins. Perhaps you need to upgrade KeePass too?

**Comment by mbutz** [comment]
Yes. You are right. Here is what I did:

As I did not find a Debian package of KeePass2 I downloaded the portable version (`KeePass-2.28.zip`) from SourceForge, put everything in `/usr/lib/keepass2` (after saving the previous content) and it so far it seems to work. Have to take care that an upgrade via `apt-get` will not destroy my custom upgrade of KeePass.

Thanks a lot
Martin

**Comment by dlech** [comment]
FYI, the Debian/Ubuntu keepass2 package maintainer has a PPA that he keeps up to date with the latest KeePass version at <https://launchpad.net/~jtaylor/+archive/ubuntu/keepass>.

I also maintain a PPA for some KeePass 2.x plugins at <https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins>.

**Comment by mbutz** [comment]
Thanks for the update.
