### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by Fossius** [luckyrat/KeeFox#374]
Hi, Is it possible to teach Keefox understand relative paths? I write in the settings  ../KeePass-2.28 and he does not understand

**Comment by dlech** [comment]
According to [this page](https://github.com/luckyrat/KeeFox/wiki/en-|-Portable-KeeFox), relative paths should work. Maybe this is a problems with forward slash vs. backslash? Are you using Windows or Linux/Mac?

**Comment by Fossius** [comment]
Thank you very much!!!!!!! Need to write .\Profiles\extensions\KeePass-2.28
