### ISSUE TITLE
Thunderbird - Provider for Google Calendar support

### ISSUE THREAD

**Issue by sputtene** [luckyrat/KeeFox#375]
I'm using KeeFox in Thunderbird, which works wonderful for regular email accounts.

I also use the Lightning extension for calendar functionality, together with the "Provider for Google Calendar" extension.

Keefox doesn't fill out the password in the credentials pop-up. That pop-up is a webpage (rendered by Thunderbird), not a regular username/password dialog box.

Others have described the same issue at https://zohodiscussions.com/keefox/topic/thunderbird-keefox-support-for-provider-for-google-calendar and https://zohodiscussions.com/keefox/topic/keefox-provider-for-google-calendar-issue (this link has a screenshot of the credentials pop-up).

I've enabled sensitive logging as suggested by @luckyrat in his replies to the reports I linked to above, but I don't see anything in the log that could help me to configure KeeFox to handle this case correctly.
Log file with sensitive logging enabled is available through email on request. I'm not going to post possibly sensitive data here :)

Has anyone got this working? If yes, how?

**Comment by sputtene** [comment]
Hi,

Google Calendar Provider still doesn't work with KeePass. I think your code to add support for that extension doesn't parse the credentials pop-up correctly.

This is from the KeePass log file with sensitive logging enabled. I've redacted my email address, but didn't change anything else:
<pre>
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: gdata-provider prepareFill accepted
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: The Provider for Google Calendar would like to access your account , to retrieve events and tasks. Credentials and calendaring data is only transfered between your computer and Google, no third party sites are involved.
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: The Provider for Google Calendar would like to access your account <b><i>my_username</i></b>@gmail.com to retrieve events and tasks. Credentials and calendaring data is only transfered between your computer and Google, no third party sites are involved.
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: <b><i>my_username</i></b>@gmail.com
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: gmail.com
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: Exception occured while trying to extract the host from this string: gmail.com. [Exception... "Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: chrome://keefox/content/gdata-provider.js :: keeFoxGDataProviderHelper.prepareFill :: line 108"  data: no]
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: Sending a JSON-RPC request: {"params":[["gmail.com"],null,"","LSTnoRealms",false,null,"",null,"<b><i>my_username</i></b>@gmail.com"],"method":"FindLogins","id":5}
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: starting webcrypto encryption
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: decryption stage 'aes-cbc' took: 312
!! Mon Sep 14 2015 21:41:30 GMT+0200 (CEST):DEBUG: decryption stage 'utf-8 conversion' took: 1
!! Mon Sep 14 2015 21:41:31 GMT+0200 (CEST):INFO: callback fired!
</pre>

This is with KeeFox 1.5.3.

If there is any more information I can provide that would help, please ask.

Thanks!

**Comment by dlech** [comment]
It looks like it is doing what it is supposed to. It just must not be finding a matching entry in KeePass. Version 1.5.x changed how domain matching works, so check your KeePass entry and make sure that it is not set to "exact match" or something like that and make sure that entry has a URL with "gmail.com" in it.

**Comment by sputtene** [comment]
Thanks for your speedy reply.

Adding just <tt>gmail.com</tt> to my KeePass URL entries (it already had my full email address in there, but that didn't do the trick) made it work.

Now to figure out how to use a one time password, so I don't have to confirm my credentials every time.

Thanks a lot!

**Comment by dlech** [comment]
If you figure it out, please let us know on #511.
