### ISSUE TITLE
Keefox keeps asking for authorisation with two independent Firefox instances. 

### ISSUE THREAD

**Issue by victor-50** [luckyrat/KeeFox#382]
I have two independent Firefox instances running and until now this worked fine. This evening all of a sudden it keeps on asking for keys. I think for one and then for the other and so on, but am not sure about that. Only when I disable Keefox in one of the two this stops. I can live with that but I don't like it. 
FF 36.0.4 / W7-64bit / Keepass 2.28 / RPC 1.4.4 / Keefox 1.4.6

**Comment by luckyrat** [comment]
Are they really independent? Separate Firefox profile, separate KeePass instance, separate KeePassRPC port?

**Comment by victor-50** [comment]
They have a separate profile. I don't think they have a separate Keepass instance. I guess they once had an identical port, don't know if that was the case when the trouble started as they asked for different keys. As said It used to work this way. It's not a real big problem as I almost never need a password in the second instance.

**Comment by luckyrat** [comment]
Don't think there's anything we can/should do here.
