### ISSUE TITLE
Text Overflow in Settings Dialog

### ISSUE THREAD

**Issue by Marcuse7** [luckyrat/KeeFox#385]
In the Options dialog, Connection Security tab, text is not displayed completely when language is set to German. Due to longer sentences in that language, there is not enough room.
![keefox_text_overflow_issue](https://cloud.githubusercontent.com/assets/11646725/6823651/85437fa0-d2ea-11e4-98f3-f4479ac13519.png)

**Comment by dlech** [comment]
Duplicate of #325.
