### ISSUE TITLE
"Websockets disabled" warning in Firefox 35+ is incorrect

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#386]
The network.websocket.enabled setting no longer exists in FF35+ so any transient connection problem can trigger an unnecessary warning to users.

Any user that takes initiative to create this about:config setting and set it to true as implied in the warning message will experience no ill effects and if the problem happens again, they may be notified of a possible Firewall problem as per usual behaviour in earlier Firefox versions.

It is no longer possible to disable websockets through a preference (although other addons might still be able to inject code to force this behaviour, but I doubt those kind of tricks would make it through AMO review so we'll be unlikely to see many problems in the wild).

**Comment by chinaar** [comment]
Just for your information, It appears that the Request Policy Continued addon can cause this to occur as it disables websockets. https://github.com/RequestPolicyContinued/requestpolicy/issues/615.
