### ISSUE TITLE
thunderbird 38 breaking compatibility?

### ISSUE THREAD

**Issue by r2evans** [luckyrat/KeeFox#388]
I recently upgraded to TB 38 (not realizing it's still classified as a nightly ... TB tricked me!). In so doing, KeeFox/KeePassRPC works fine for IMAP retrieval but not for SMTP auto. Any thoughts on best way to troubleshoot? (It was working fine with TB 37 and KeePass hasn't changed, so I believe TB just broke it somehow.)

Win8.1_64, TB38, KeeFox 1.4.7b3 in TB (and FF), with KeePassRPC 1.4.4 in KeePass 2.28.

**Comment by dlech** [comment]
Here is probably what broke it: http://hg.mozilla.org/comm-central/diff/1def2116d8fc/mail/locales/en-US/chrome/messenger/messengercompose/composeMsgs.properties#l1.461

Although with the recent fixes to string matching (#344, #354, KeeFox 1.4.6), this *should* not have broken it.

I'll have a look at it sometime. Remind me if I haven't fixed it in a month.

**Comment by r2evans** [comment]
BTW: I know this is a closed issue, but I thought I'd add that 1.5.3b1 is working fine with TB-38.0.

**Comment by ktchong** [comment]
I installed KeeFox 1.5.3b9.  It did not work.  It failed to even fill in the initial login for IMAP.

**Comment by ktchong** [comment]
English.  I can't email you.  All my email to you was bounced back, which is extra annoying because I had to manually type in my password every time I sent an email.

**Comment by r2evans** [comment]
Just curious, @ktchong, even if the auto-type functionality isn't working, are you not able to copy/paste from keepass to the password dialog? I hear your frustration, but frankly it's just going back to what it was before KeeFox, nothing worse.

**Comment by ktchong** [comment]
I actually stopped using KeeFox awhile back (because I could not find  a 
solution to the problem.)   I don't remember if I was able to cut/paste 
from keepass to the dialog.

On 11/5/2015 12:30 PM, r2evans wrote:
>
> Just curious, @ktchong <https://github.com/ktchong>, even if the 
> auto-type functionality isn't working, are you not able to copy/paste 
> from keepass to the password dialog? I hear your frustration, but 
> frankly it's just going back to what it was before KeeFox, nothing worse.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/luckyrat/KeeFox/issues/388#issuecomment-154181306>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
