### ISSUE TITLE
Custom Password Profile not working with Generate Password function

### ISSUE THREAD

**Issue by ligos** [luckyrat/KeeFox#392]
Hello,

I'm the developer of the Readable Passphrase Generator for KeePass, and I have an issue raised where KeeFox is not generating a password via your *Generate new Password* button.

After a bit of trawling though KeeFox and KeePass source, I think the issue is in your `KeePassRPCService.GeneratePassword()` method. Around line 1141, your last parameter shouldn't be `null`, but `IPluginHost.PwGeneratorPool`, that is `this.host.PwGeneratorPool`.

Now, this is entirely based on reading unfamiliar source code (and I have not tried to fix the issue, or inspect the code in a debugger), so I might be totally off the mark. It's based on KeePass's  `PwGenerator.GenerateCustom()` implementation.

Let me know how you'd like to go from here.
Murray

https://readablepassphrase.codeplex.com/
https://readablepassphrase.codeplex.com/workitem/20

**Comment by luckyrat** [comment]
My vague memory of that source code was that I had to pass null because I didn't want to force the search to use an instance of CustomPwGeneratorPool. Hopefully I just misunderstood the method signature. I'll take a closer look soon but your suggested change sounds hopeful!

**Comment by ligos** [comment]
The KeePass source for `PwGenerator.Generate()` has a bunch of if statements on `PwProfile.Generator`. The `CustomPwGeneratorPool` is only used if `PwProfile.GeneratorType == PasswordGeneratorType.Custom`. So I think you should be safe. Possibly older versions had the behaviour you describe.

The relevant file in KeePass is KeePassLib\Cryptography\PasswordGenerator\PwGenerator.cs

Anyway, I'll point my requester to this issue for tracking.
Thanks.

**Comment by luckyrat** [comment]
It'll be a while before this can make it into even a beta release but the work is now done and tested so it's just a matter of time.
