### ISSUE TITLE
Anonymous stats generating far too many outbound requests.

### ISSUE THREAD

**Issue by Radagast** [luckyrat/KeeFox#399]
My firewall log is basically full of nothing but requests to anonymousstats.keefox.org, 

23/04/2015 09:25:09 | 1668 | Firefox | M:\windows\mozilla\beta64\firefox.exe | Out | 51194 | 162.243.252.183 | 443 | 6
23/04/2015 09:24:48 | 1668 | Firefox | M:\windows\mozilla\beta64\firefox.exe | Out | 51193 | 162.243.252.183 | 443 | 6
23/04/2015 09:24:27 | 1668 | Firefox | M:\windows\mozilla\beta64\firefox.exe | Out | 51191 | 162.243.252.183 | 443 | 6
23/04/2015 09:24:27 | 1668 | Firefox | M:\windows\mozilla\beta64\firefox.exe | Out | 51192 | 162.243.252.183 | 443 | 6
23/04/2015 09:23:55 | 1668 | Firefox | M:\windows\mozilla\beta64\firefox.exe | Out | 51190 | 162.243.252.183 | 443 | 6
23/04/2015 09:23:54 | 1668 | Firefox | M:\windows\mozilla\beta64\firefox.exe | Out | 51189 | 162.243.252.183 | 443 | 6

is this really necessary? Maybe an option to turn this off would help.

**Comment by luckyrat** [comment]
Doesn't your firewall allow you to filter out valid requests? I can't imagine it's much fun having to sift through logs of all connections made by Firefox!

Have you read https://github.com/luckyrat/KeeFox/wiki/en-%7C-Metrics-collection ?

If you disable the usage metrics tracking you should find the quantity of requests drops significantly.

**Comment by Radagast** [comment]
Thanks for the reply. The firewall is Windows firewall, which can be quite easily filtered, however, it doesn't take away from the fact that keefox is generating two outbound requests approximately every 30 seconds, even with metrics disabled.

**Comment by luckyrat** [comment]
The only reason KeeFox would consistently attempt to send messages when metrics are disabled is if it can't contact the metrics server. I've just checked and it is all working fine so if that's the reason you're seeing so many connections it must be a problem that's at least relatively local to your internet connection. If it's only been doing this a short while, maybe it's a transient problem that your ISP will resolve for you. Once KeeFox has sent the pending messages it should only send another one when your browser next starts up.

**Comment by pit001** [comment]
Also one ist to much for an App who deals with my bank account password !! I don't trust this App.

**Comment by luckyrat** [comment]
KeeFox 1.5 (available in Beta at the moment) takes a few more aggressive steps to work around Firefox bugs that have caused problems in the past. It's possible that this type of regular traffic to the stats server will be eliminated on your system shortly after upgrading to v1.5.

> I don't trust this App.

@pit001 That's up to you but you'll struggle to find many similar solutions that are as open and transparent about privacy and security issues so if you've not read it yet, I'd recommend looking at the [metrics manual page](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Metrics-collection) and you're obviously free to inspect the Javascript code that implements the metrics system so you can see that there is no reason to distrust it.

**Comment by pit001** [comment]
It's up to me to give my password to an App of an foreign person. I can read the documentation, check the vita, pray and also walk through the code. It depents of the time I can spend. At the end I can write my own App - at the beginning use a commercial like LastPass, ... .
In the actual case I switch off the Anonymous stats with the checkbox offered by you (!)
And ? I find that the App don't stop to send requests to the DNS for the IP of anonymousstats.keefox.org. Test ended. Thx, but no.

Please understand - a hole or backdoor in this system will have a big impact in my real life. I think you are not able to pay the stolen money back - are you ? And if you are as the programmer of this App not able the get a simple binar information (a checkbox) working correct, than sorry.

**Comment by luckyrat** [comment]
You've obviously not read even the basic introduction to the metrics feature nor the description in the add-on privacy policy nor the labels on the option form containing the checkbox you refer to, so please feel free to supply your passwords to a commercial organisation like LastPass since you are clearly not as concerned with privacy and security as I am or you would have taken at least that small amount of time.
