### ISSUE TITLE
Decrease likelihood of "Matched logins found" popup being required on page load

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#410]
I expect that 99% of times the popup is required are because the page has done something on-load in order to create a new frame or form. In most of those cases, the user won't notice the delay in the form appearing so the appearance of the matched logins found popup would be unintuitive and unpredictable.

I think there might be a way to tackle this by recording a timestamp of when the main parent page fired its DOMready event. We can then compare against that time when launching a search for logins and only request the popup if it's been long enough* that the user might have started interacting with the page.

\* 1 or 2 seconds?

**Comment by luckyrat** [comment]
Punting this to a later milestone to get it off the 1.5 list but if I hear lots of feedback during beta testing that this is a problem in the real world, it could be prioritised for v1.5 again.

**Comment by andredasilvapinto** [comment]
Ideally I would want an option to disable this kind of notifications. the red star on the keefox icon is more than enough for me...

**Comment by luckyrat** [comment]
The red star/plus on its own is not always enough to indicate when new logins have been found (a new form could have appeared on a page that already had a couple of logins).

**Comment by andredasilvapinto** [comment]
fair enough. but I never experience such use case. it would be nice to have the option of turning them off. I keep getting those notifications for example when navigating around on twitter. anyway, it is not a major concern.

**Comment by Kintak** [comment]
I came here just to post what Andre has. This notification is an annoyance that I want to disable. The plus is enough.

**Comment by cfassett** [comment]
I agree with Andre and Kintak.  The old behavior was much less obtrusive.

**Comment by gaston68cz** [comment]
+1 for option to disable this notification

**Comment by erwanlr** [comment]
Also would like to be able to disable that :)

**Comment by luckyrat** [comment]
> The old behavior was much less obtrusive.

I appreciate it's academic but you might be interested to know that this is not strictly replacing an old behaviour. The forms that are being detected in a way that triggers this notification were never detected by earlier versions of KeeFox.

**Comment by luckyrat** [comment]
I'm not sure I want to offer a way to disable the notification but it is a possible approach if we can't address this issue effectively enough.

I'm interested in how often people are seeing this notification. I see it less than once a day on average so maybe some people have a lower tolerance for these types of alerts than me or maybe some computer configurations or websites are more affected than mine.

**Comment by erwanlr** [comment]
> I'm interested in how often people are seeing this notification. I see it less than once a day on average so maybe some people have a lower tolerance for these types of alerts than me or maybe some computer configurations or websites are more affected than mine.
 
On Twitter, you have a notification each time you do something like a search, access the main page (https://twitter.com/). Then, sometimes it also shows up when accessing a user page/profile

**Comment by Kintak** [comment]
I personally have zero tolerance for popups of any kind. I find them very intrusive. That said, KeeFox's notification is also popping up a lot. Twitter is the biggest problem of all.

**Comment by yedeneek** [comment]
While it might be detecting new forms in a different way, I don't feel like I need to know about it through a popup. Clicking an image on the imgur.com front page does this everytime for me.

**Comment by oliver-graetz** [comment]
+1 for an option to disable those notifications altogether. They are annoying. It's the same with all those information gadgets: They are good for really important stuff, but then everbyody starts using them for useless information. That makes them annoying and what's worse, you stop paying attention and might ignore those rare and very important messages. For another example of this, see the UAC in Windows Vista which only becomes acceptable two weeks after installing the system or after upgrading to Windows 7.

Perhaps introduce more versions of the Keefox toolbar icon. The red star is not very good to begin with, because it is red just like the key, thus reducing the visual impact when signaling newly found logins. Use something with more color contrast. But I'm not a graphics expert. Wild guess: Perhaps switch to the single-coloured look of default Firefox icons for the default icon, something like a simple diagonal key, looking a bit like the magnifier icon for the search. With that loss in colous for the default status you could introduce differing colours for information about found logins: red for those classic ones and orange glowing for "dynamic forms".

**Comment by slovdahl** [comment]
I find these notifications very obtrusive as well. Saw maybe 20 notifications yesterday and maybe one of them was actually shown when I would have expected it.

I don't understand the need of notifying the user that there are new matching logins at all. If I open a page that needs login I already know it, no need for KeeFox to tell me that.

**Comment by johnfender** [comment]
It's really a pain, i'm searching to downgrad to the previous version, i'm fed up to be harassed in my every day surfing, it's just horrible ! Do you use your own extenion guy ? Really ? It's a MAJOR mistake ! i'm really angry about that. And you know what, you can't hide it via the normal way, in windows you are usually allowed to hide or show notification. It's not working for keefox grrrr !!!!

![snap2](https://cloud.githubusercontent.com/assets/9516547/9909479/b8138eec-5c98-11e5-9069-365d0038c57a.png)

The new notification if bigger than big it's really boring. Why not making a small an inintrusive pop which open this big one ??? Why ?

![snap4](https://cloud.githubusercontent.com/assets/9516547/9909521/e4263b24-5c98-11e5-8df3-f5bd8f3248df.png)

**Comment by Ythan** [comment]
I'm a big fan of this addon and have donated in the past. I understand the technical reasoning behind the popup, and I'm very glad Keefox now recognizes login forms like https://wwws.mint.com/login.event which never worked before. To me, that's the most important fix in this update and I'm really grateful for the change! But I agree with the other commenters, the popup is needlessly intrusive and it would be better to have a numeric form counter on the Keefox browser button or something. Thanks for your consideration and keep up the good work!

**Comment by theSoenke** [comment]
The new version is amesome, but this popup is really annoying. Saw it probably a few dozens time today.

**Comment by Radagast** [comment]
I hate pop-ups and this one is really starting to annoy me.Please add an option to disable it.

**Comment by webloem** [comment]
I love Keefox but I don't like popups. And thanks for an amazing addon.

**Comment by marjasin** [comment]
I'm incredibly disappointed in your choice of destroying such a nice addon by introducing these intrusive popups.

**Comment by mobamoba** [comment]
On pages like from the New York Times, merely scrolling down the page to read an article triggers the popup multiple times. As with others, I'm +1 for removing it as I find the constant barrage of popups to be very annoying.

**Comment by kitsnet** [comment]
If you have an opened window with a Disqus-powered forum, the popup may be triggering several times per minute. The window doesn't even need to have focus for that.

Very annoying.

**Comment by luckyrat** [comment]
> If you have an opened window with a Disqus-powered forum, the popup may be triggering several times per minute. The window doesn't even need to have focus for that.

Maybe there is a way to prevent it showing when the window does not have focus - there's certainly no benefit to that behaviour and I can see that it would be very annoying.

I have no spare time at the moment but finding a solution to the annoyance being felt by some here is a fairly high priority when I can next work on KeeFox.

**Comment by romland** [comment]
It was driving me nuts, so I removed it with a really quick hack.

No warranty, do at own risk etc.

Follow these rather hurriedly thrown together steps...

- Go to the addon-site @ Mozilla to get Keefox, shift+click the "get addon" button to download it
- Rename the XPI that was downloaded to end with .zip
- Extract this .zip file
- Open (in my case) \keefox-1.5.3-tb+fx-windows.xpi\chrome\content\panel.js in notepad (or any text editor)
- Search for "Matched logins found"
- Now comment out the two lines below, so it looks like (add two slashes in front of each line):
  //        if (notifyUserOnSuccess)
  //            keefox_win.UI.growl("Matched logins found", "View them in the main KeeFox panel", true);
- Save this file, close notepad
- Zip the CONTENTS of that directory (not the folder itself)
- Rename zipped file so it's called e.g. keefox-1.5.3-tb+fx-windows-patched.xpi
- Go to "Extensions" in Firefox
- Under the cogwheel on top of that screen you have the option
  "Install Add-on from File" -- use it.
- Accept the warning that pops up

**Comment by romland** [comment]
Sorry, but it was driving me nuts. I don't need to be told that a password was found. When I need a password, I will look for it.

So, I removed the growl with a really quick hack.

(this is a double post from earlier, for a moment I thought the addon stopped working, but that was just in my head)

Follow these rather hurriedly thrown together steps... (No warranty, do at own risk, etc.)

-    Go to the addon-site @ Mozilla to get Keefox, shift+click the "get addon" button to download it
-    Rename the XPI that was downloaded to end with .zip
-    Extract this .zip file
-    Open (in my case) \keefox-1.5.3-tb+fx-windows.xpi\chrome\content\panel.js in notepad (or any text editor)
-    Search for "Matched logins found"
-    Now comment out the two lines below, so it looks like (add two slashes in front of each line):
     // if (notifyUserOnSuccess)
     //     keefox_win.UI.growl("Matched logins found", "View them in the main KeeFox panel", true);
-    Save this file, close notepad
-    Zip the CONTENTS of the directory that hold the entire addon (not the folder itself)
-    Rename zipped file so it's called e.g. keefox-1.5.3-tb+fx-windows-patched.xpi
-    Go to "Extensions" in Firefox
-    Under the cogwheel on top of that screen you have the option "Install Add-on from File" -- use it.
-    Accept the warning that pops up
-    Restart Firefox

I did not do much testing (I literally did this in 10 minutes, a few minutes ago).
I tested on the two pages that were driving me nuts!

Your mileage may vary.

(if I have offended by posting this, I apologize)

**Comment by srvg** [comment]
I use a web based online accounting app. *Each* time I select the tab of that app, I get the popup. The application doesn't even show a visual form where logging in is needed.
The app makes extensive use of frontend code, and I assume this is where something gets triggered. On the plus, keefox now works on that app, where in the past, it never detected the initial login form (which is plain JavaScript I believe).

I never encountered a situation where I needed any kind of notification when a form gets detected and fully agree with @slovdahl remark:

> I don't understand the need of notifying the user that there are new matching logins at all. If I open a page that needs login I already know it, no need for KeeFox to tell me that.

**Comment by luckyrat** [comment]
It looks like my initial assumption in this issue might be wrong. The only feedback I'm hearing is regarding the existence of the notification rather than any problem with the notification appearing immediately after page load. Therefore it is unlikely I'll be able to find time to implement this enhancement and given its vague definition I don't think it's realistic to expect anyone else to want or be able to either.

I still can't get the notification to appear reliably in any of the situations/websites described above but I've implemented an untested option which might help in #555.
