### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by SnowGabe** [luckyrat/KeeFox#426]
I generally dislike animations and I haven't found a way to disable the feature with KeeFox. It takes around a second to open KeeFox window.

**Comment by luckyrat** [comment]
That's a Firefox behaviour. KeeFox can't override it but maybe there is some setting you can find to adjust the animation delay for all Firefox panels? It's not something I've personally ever investigated but if you find a solution please post it here in case anyone else finds it helpful.
