### ISSUE TITLE
Binary Extension Components no longer allowed in Firefox Nightly

### ISSUE THREAD

**Issue by hooloovoo79** [luckyrat/KeeFox#435]
The firefox team added code to nightly than prohibits extensions from using binary components in then. I'm not sure if (but expect it will) affect the binaries in the \deps folder. More reading:

https://bugzilla.mozilla.org/show_bug.cgi?id=1159737
https://groups.google.com/forum/?fromgroups#!topic/mozilla.dev.extensions/B3H3j6FRVms

**Comment by luckyrat** [comment]
Thanks for the heads-up. This change should only affect binary XPCOM which KeeFox has not used since pre version 1.0 so we should be fine. Next time I'm on Nightly I'll double check before then closing this issue.
