### ISSUE TITLE
Connections to Keefox site for Stats

### ISSUE THREAD

**Issue by SPOTBEAM** [luckyrat/KeeFox#451]
I have disabled sending anonymous keefox stats in the options like so:
![Advanced Tab](http://i.imgur.com/wzo9b8d.png)

But still when traffic is seen in Fiddler connections to anonymousstats.keefox.com show up:
![Fiddler](http://i.imgur.com/Tk7gHrf.jpg)

Kindly mark this as bug and fix it. :smile:

**Comment by luckyrat** [comment]
That option disables the usage (behavioural) statistics, not system data so those outgoing connections will be reduced but not completely eliminated. All the details are in the privacy policy and this manual page: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Metrics-collection

PS: I've just added a link on that page to the source code to aid verification of the situation.

**Comment by SPOTBEAM** [comment]
Is there a way to turn this feature off?

**Comment by luckyrat** [comment]
Not the system level stats, no. As explained elsewhere, it's only recording the same information that is already provided by Mozilla/Firefox plus version numbers related to KeeFox.

There shouldn't be any need to turn it off but if it is causing you a technical problem, please explain so we can see if there is anything that can be done to fix it (we could always re-open this ticket with a more specific description if we find a bug to fix).
