### ISSUE TITLE
HTTPSEverywhere blocking connections between Keepass and Keefox

### ISSUE THREAD

**Issue by Muscular** [luckyrat/KeeFox#452]
Enabling `Block All HTTP Requests` blocks :no_entry_sign: communication between Keepass and Keefox:

![Menu](http://i.imgur.com/Pv60LAd.png)

The result is that Keepass status is stuck at `You are not logged in to your password database`
Can you think of a fix apart from disabling the option?

**Comment by luckyrat** [comment]
From your screenshot I assume that you mean `Block all HTTP Requests` (not HTTPS).

There might be an advanced configuration option in that addon which allows you to whitelist localhost communication but block non-secure connections for any requests which go over the internet. For example, If I were using that add-on I'd have a poke around to find out what "Enable / Disable Rules" does :-)

Actually, blocking plain HTTP requests even to localhost shouldn't affect KeeFox too severely but it sounds like this option also disables websockets which will definitely be incompatible with the need for KeeFox to communicate with KeePass. Whether websockets are HTTP requests is a little bit open to interpretation but I am certain that an add-on like this which aims to prevent all non-secure communication should be treating them the same way as a normal HTTP request so I don't think there is anything the add-on author should do to change this behaviour.

If you're interested in some of the technical detail about how and why KeeFox uses websockets (and why it is still secure despite the lack of HTTPS) you might want to take a look at the technical section of documentation: https://github.com/luckyrat/KeeFox/wiki/en-|-Technical-|-KeePassRPC-detail

**Comment by SPOTBEAM** [comment]
Yup I meant HTTP requests. I have checked `Enable/Disable Rules`. It allows downgrading or upgrading from either HTTP to HTTPS or vice versa with reference to a particular website url. I am going to try using localhost:port downgrading and report soon.

**Comment by luckyrat** [comment]
Given this is a problem with a 3rd party addon and no further info has led to any action we can take to change KeeFox I'm going to close this.
