### ISSUE TITLE
Bug to record password

### ISSUE THREAD

**Issue by shafan** [luckyrat/KeeFox#472]
When I want recorded after a password set connected to a site, I click on the desired database and got this message. And entry is not registered. But not with all website.

Message : ERROR: An error occurred in KeePassRPC object id: null with this message: undefined and this error: [object Object] and this error message: Expected a ',' or '}'. See line 1, position 502.

KeePass 2.29
Keefox 1.4.8.1
Debian - Iceweasel 40.0

**Comment by luckyrat** [comment]
I'll let you know when the beta of KeeFox 1.5 is ready so you can test in that. If it's still broken I'll take a look before the final v1.5 release.

**Comment by luckyrat** [comment]
Have you had a chance to try out the KeeFox 1.5 beta yet? It's available on the AMO development channel (bottom of the page): https://addons.mozilla.org/en-US/firefox/addon/keefox/#beta-channel
