### ISSUE TITLE
Toolbarbutton gets stuck in open (depressed) state but panel has gone away

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#474]
I've seen this happen twice now and I suspect the cause is that an exception gets thrown by the onViewHiding function. There's probably a Firefox bug here (either it shouldn't be possible for me to break the core UI from a callback like this, or it is nothing to do with the KeeFox onViewHiding function call). Both times I've seen it happen, my PC has been pegged at 100% CPU and very sluggish so it's potentially a race condition that only occurs under heavy load (or on very slow computers?).

There may be a clue somewhere in Bugzilla but after an hour of trying I can't get anything in-between 10,000 results and zero for anything approaching a relevant search query so I've run out of time to investigate further.

The only known realistic way to recover is to close the window/Firefox and start again but it can also be fixed by removing the open="true" attribute from #keefox-button if anyone prefers to hack the browser XUL through the Browser Toolbox rather than restarting. There's probably also a Javascript incantation that will do the trick when run in the console but I've not been able to test any ideas yet.

**Comment by chinaar** [comment]
Just run into this. Don't know if I can help at all. I'm running the latest nightly x64 20150629 on Windows 8.1 x64. 
![keefox](https://cloud.githubusercontent.com/assets/10645442/8426856/81467d56-1f45-11e5-9edf-43fc468587a7.png)

**Comment by luckyrat** [comment]
Thanks for mentioning it and the screenshot - that looks like the issue I saw.

1.4.103a1 is no longer the latest version - keep an eye on the Releases page unless you install KeeFox from the official Firefox addons website or in-browser tab. I've uploaded another new release just a minute ago.

I've spent another half hour trying to replicate this with the latest version of KeeFox and haven't been able to but it is such an intermittent issue that this doesn't mean it is actually fixed (and I have no reason to think it would be).

In any case, I've now added an extra bit of logging to the onViewHiding function I mentioned above in case this is related to the problem so please ensure you are logging to a file just in case it happens again so we can get a clue what might be causing it ("Error" level will suffice but you shouldn't see much noise from enabling "Warn" too).

**Comment by chinaar** [comment]
So I just installed 1.5.2b4 and I am still seeing this now. I can now reproduce this in a foolproof way on my computer everytime. I use reddit with the SHINE addon. If i go to reddit while that addon is enabled, attempt to autofill (fails) and then click on the keefox button, this reproduces for me every single time. I tried reproducing this with the warnings level logging on, but unfortunately I wasn't getting any useful information (or any information apart from a logging started line). If you like I can run at the debugging level while reproducing the issue and see if that turns up anything useful?

**Comment by luckyrat** [comment]
Well that's good news (in a way!)

I've been able to replicate it without the SHINE addon (which is just as well because I can't work out what that addon is for because it has been removed from the Firefox addons website and I also can't find the source code anywhere either so it doesn't look like there is an easy and safe way for me to install it on my machine).

The fact that there were no errors is useful information itself since it rules out my initial theory about it being a bug with the onViewHiding function.

I can now replicate the issue by attempting to open the KeeFox panel after clicking on a matched login. Normally a new page would have loaded before there is a need to interact with the panel again so that is why it is such a rare problem. In the case of reddit (at least when logging in with invalid credentials) no new page is loaded so this vastly increases the chance of hitting the bug. Likewise, on a slow computer there is more time between that matched login click and the new page load even on a "normal" website so that explains why I previously saw a correlation with high-CPU usage.

I'll go out on a limb and say it is now likely to be a KeeFox bug but I'll have to do some more investigation to narrow it down. I've not got much spare time until next week but I'll make this a priority once I can find a chunk of time to dedicate to KeeFox development next week.

In the mean time, you should be able to prevent the problem occurring by remembering to always switch to a different tab and then back again after selecting a matched login on any affected site (or all sites depending on how painful a Firefox restart is for you versus the tab-dancing inconvenience).

**Comment by chinaar** [comment]
Great news, thanks for looking into this!

**Comment by luckyrat** [comment]
I've found and committed a fix for the reddit symptom but have also found another way to trigger the bug (which is probably more likely to be the trigger I found originally). If you move the mouse over the first matched login item within a fraction of a second after clicking the KeeFox toolbar button you trigger the onMouseEnter function that normally displays the hovering menu button.

I think this function must be trying to do something which is not allowed until after the view has been completely shown in which case we probably need to hope that the #503 idea works (or Mozilla add support for an onViewShown event which is where I would normally want to activate that kind of interaction)
