### ISSUE TITLE
No longer prompted for calendar password in TB 31.7.0/Lightning 3.3.3 with KeeFox 1.5.1b1

### ISSUE THREAD

**Issue by dlech** [luckyrat/KeeFox#476]
Not sure if this is a KeeFox bug or a Lightning bug at the point. Just wanted to throw this out there in case other beta testers are seeing the same thing.

**Comment by dlech** [comment]
Forgot to mention that this is with a caldav calendar. I have a Google calendar as well and it is working normally.

**Comment by luckyrat** [comment]
Is it a new problem with 1.5.x?

**Comment by dlech** [comment]
I'm not sure. I tried disabling KeeFox and the problem persisted, so it is either a problem with Thunderbird/Lightning or a problem with some setting that KeeFox changes. Or it could just be a problem with my calendar provider. The password dialog is jut not popping up at all and there are no errors in the error console, so it is really hard to say what is going on. I haven't tried downgrading back to 1.4.x.

**Comment by dlech** [comment]
Well, this seems to be a problem with my caldav server.
