### ISSUE TITLE
"Update Existing Entry" throws error

### ISSUE THREAD

**Issue by mscrivo** [luckyrat/KeeFox#480]
After upgrading to the 1.5.1 beta, many of my logins work but prompt me to save or update them in keepass.  When I choose to update the existing entry, it sometimes works, but often throws the following error from keepass:

Warning: Configuration errors

There are configuration errors in this entry. To fix the entry and prevent this warning message appearing, please edit the value of the 'KeePassRPC JSON config' advanced string. Please ask for help on http://keefox.org/help/forum if you're not sure how to fix this. The URL of the entry is: <URL> and the full configuration data is: 

I then check the "Advanced" tab in the keepass entry and there is no KPRPC JSON field at all.

**Comment by luckyrat** [comment]
Can you find the old entry in the KeePass history tab? Maybe try restoring that and inspecting it to see if there is any pattern between the ones that throw the error and those that don't.

Is the error thrown during the update operation or at a later time?

**Comment by mscrivo** [comment]
The error is thrown as soon as I click "Save" in the update existing entry pane.  There are no recent items in the History tab.

**Comment by mscrivo** [comment]
If I create the KPRPC JSON field manually and then try updating the entry, it works fine.

**Comment by luckyrat** [comment]
Ah, I see. It must be happening only for entries that never had a KPRPC JSON field in the first place. So you shouldn't be losing any data.

I'll take a look at fixing it soon.

**Comment by luckyrat** [comment]
Fixed here: https://github.com/luckyrat/KeeFox/releases/tag/v1.5.2b1

Thanks for reporting the problem.

**Comment by mscrivo** [comment]
Thanks for fixing it so quickly.
