### ISSUE TITLE
No matching entry found with Lightning on Thunderbird 38.0.1

### ISSUE THREAD

**Issue by crazy-max** [luckyrat/KeeFox#488]
Hi,

Windows 8.1 64-bits
Keepass 2.29
Thunderbird 38.0.1
Keefox 1.4.8b1
Lightning 4.0.0.1

I can't make things work with Lightning addon and Thunderbird, the prompt window is not autofilled now :

![image4](https://cloud.githubusercontent.com/assets/1951866/8148189/2fb4ccca-1290-11e5-95d5-dd9cc6164c75.jpg)

Thanks for your help!

**Comment by crazy-max** [comment]
Works on Keefox 1.5.2b1!

**Comment by luckyrat** [comment]
That's useful information. Thanks.

**Comment by dlech** [comment]
Duplicate of #388.
