### ISSUE TITLE
Non localized strings

### ISSUE THREAD

**Issue by stenox** [luckyrat/KeeFox#497]
From time to time I get pop up notification which is non localized.
I'm testing the beta 1.5.2b3 (Ukrainian) at the moment.
Ukrainian localization is 100% translated.
Non localized notification:
![2015-06-22 11_15_59- - 12 -](https://cloud.githubusercontent.com/assets/7978799/8278011/a5828ed8-18d0-11e5-9bb2-9b1a71a99d08.png)

**Comment by luckyrat** [comment]
The Ukrainian translator has been hard at work the past few days so those newly translated strings will be included in the next beta in about a week.

**Comment by stenox** [comment]
That translator was me :)
The translation was complete by June 19th. So, I thought that all staff should be included into first beta.
OK, will test it with next beta.
Thanks!

**Comment by luckyrat** [comment]
I've just included your most recent translated strings in v1.5.3b7
