### ISSUE TITLE
Postpone FAMS notifications when main panel is open

### ISSUE THREAD

**Issue by dlech** [luckyrat/KeeFox#499]
I was just perusing my list of logins when all of a sudden, a FAMS message appeared. This resized the popover box and closed the list of logins, causing me to have to click on the "Logins" button again.

I think FAMS should be more polite and not interrupt. Perhaps you could test if the user has opened the KeeFox menu manually and delay the display of FAMS until later.

**Comment by luckyrat** [comment]
Good idea. #450 is intended to help ease that sort of situation but finding a way to postpone it would be preferable, and given my inexperience with animations, potentially faster to implement too!

FAMS isn't the only thing that can cause this issue but it's by far the most likely to interrupt during normal usage so focussing on it first is sensible.

**Comment by luckyrat** [comment]
The implementation affects all notifications and it will still allow high priority messages to appear immediately (for FAMS, this is currently only the privacy policy notification at first install and the warning about the KeeFox version being very old)
