### ISSUE TITLE
Copy username and password directly from search results

### ISSUE THREAD

**Issue by fgianneschi** [luckyrat/KeeFox#505]
Hi,

this is a feature request.
When KeeFox shows you more than one matched entry after a search, the only option you have for every item after right clicking on it is "Edit login".
It could be extremely useful to have also the "Copy Username" and "Copy password" options.
Thanks

**Comment by dlech** [comment]
What version of KeeFox are you using? If you are not using 1.5.x, you should upgrade and try again. There are copy username and password options. Not sure exactly what you are getting at with the search, but it is probably different in the new version.

See <https://github.com/luckyrat/KeeFox/releases> for the download.

**Comment by fgianneschi** [comment]
David Lechner ha scritto:
    
    
      What version of KeeFox are you using? If you are not using
        1.5.x, you should upgrade and try again. There are copy username
        and password options. Not sure exactly what you are getting at
        with the search, but it is probably different in the new
        version.
      See https://github.com/luckyrat/KeeFox/releases
        for the download.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    Hi,
    I'm using the 1.4.8.1-signed. I'll try with a 1.5.x, thanks.
    Fabrizio
