### ISSUE TITLE
Passwords automatically filled in plain text fields

### ISSUE THREAD

**Issue by hko-gh** [luckyrat/KeeFox#512]
I am using a site with a weird login form. The password field is of type 'text', filled with the word 'Password'. When I click the field, and the field clears and the type changes to 'password'.
Now, when I enter the site with KeeFox, it automatically fills the user name and password field, which still has the type 'text', so my password is shown in plain text. Which is very bad.
So, KeeFox should either refuse pasting passwords to 'text'-fields, or try to perform the onFocus /onClick / whatever function or simply set the type of the field to 'password' before pasting.

**Comment by luckyrat** [comment]
Unfortunately none of your suggested solutions can reliably work across all websites and some could have unintended side-effects.

KeeFox never fills a password into a text field so you could edit your KeePass entry to ensure that the value which should be password is actually stored in the entry's password field - you'll lose auto-fill capability but at least still be able to reference the password manually (this is even easier in KeeFox 1.5).

Alternatively, just don't worry about it. It's annoying when websites go out of their way to reduce security but in this case the risk is quite limited. The only thing the weird login field type change does is protect against people looking over your shoulder so just make sure you're alone when you use that website or hold your hand over the part of the screen with the login form as the page loads (and reduce risk by using a different password for every website, but you should do that anyway).

**Comment by hko-gh** [comment]
Too bad, it does not work. But thank you anyway. I just disablesd auto-fill for this specific entry, so i can click the password field first and then manually select the login from keefox.
BTW, the security risk is not that little, I think. If I submit the form with the plaintext password, Firefox stores the values to suggest them next time. So the password is probably stored somewhere in clear text. But this is issue belongs rather to the website than to keefox.
