### ISSUE TITLE
stopped working with TB 40.0

### ISSUE THREAD

**Issue by r2evans** [luckyrat/KeeFox#515]
Similar symptom as before, the password modals (no titles?) are not being filled. I'll keep looking for other things, just thought I'd start the discussion. Thanks!

Currently win81_64, TB 40.0, KeeFox 1.5.3b5.

**Comment by dlech** [comment]
Can you post a screenshot? If there are no titles, that would explain why it broke since we use titles for matching. I wonder if the same change was made in Firefox 40 since they share the same password dialogs.

**Comment by r2evans** [comment]
Sure, here are IMAP and CALDAV (Lightning) password dialogs:
![tb40-imap](https://cloud.githubusercontent.com/assets/5815808/9027082/0ee84782-38fc-11e5-9364-4eb569539f35.png)
![tb40-caldav](https://cloud.githubusercontent.com/assets/5815808/9027084/13d634ca-38fc-11e5-9e16-aa9a433f65eb.png)

I don't have FF 40 yet, it's still telling me 39 is current.

**Comment by luckyrat** [comment]
FF40 is in beta at the moment. I still see the usual window title for HTTP Auth ("Authentication Required") and KeeFox works as before.

**Comment by ecommunities** [comment]
Not sure if this is related, but I've been using your Beta version 1.5.3, maybe 1.5.2, can't tell because latest version of FF Dev Ed has disabled your plugin and will not list the current version... anyhow the problem is that your plugin "is not signed" and as of the latest release in Aurora branch, there is no way to override this, so I've now lost access to KeeFox entirely :(

**Comment by r2evans** [comment]
@dlech or @luckyrat, without dialog titles, are there reasonable options for auto-fill detection or have TB and FF disabled this functionality at the expense of perceived aesthetic improvements?

**Comment by luckyrat** [comment]
@ecommunities That is unrelated to this issue. You'll need to set the about:config `xpinstall.signatures.required` setting to true in order to use development snapshots of KeeFox from now on. That's not required for the standard beta release from AMO (at least it shouldn't be, but given the masses of bugs Mozilla have created recently, I wouldn't be surprised if there are further problems for a few weeks).

**Comment by luckyrat** [comment]
@r2evans I don't think this affects Firefox so I'll let @dlech investigate the TB situation and get back to you.

**Comment by r2evans** [comment]
@dlech, any thoughts on workarounds? The password prompts have generic (non-host-specific) popup titles, so nothing has really change from my perspective. (Unfortunately, this "TB feature" completely negates KeeFox with TB. Bummer).

FWIW: win10_64, TB 42.0, keepassrpc 1.5.4.0 (b1), keepass 2.30, keeagent 0.7.5.0 (upgrading to 0.7.10 at the moment)

**Comment by dlech** [comment]
Sorry, I seem to have forgotten about this. I'll have to install TB42 and poke around with the DOM inspector to see what is going on.

**Comment by r2evans** [comment]
I understand. If it's easier, though I haven't used TB's DOM inspector, with some guidance I might be able to get you enough of what you need. (Just trying to ease the workload for you.)

**Comment by dlech** [comment]
I forgot the exact name of the plugin, but there is a DOM inspector plugin. I was going to use it to see if the titles were still there and just hidden.

**Comment by r2evans** [comment]
I found a DOM property that seems to make sense. When querying for email (IMAP, I'm assuming POP3 as well), I found (sorry for the png, "save DOM" gave me 0-length files):

![tb-dom](https://cloud.githubusercontent.com/assets/5815808/10976734/3f58205e-83a2-11e5-988b-a6763ed2565b.png)

`#document > dialog > xul:vbox > grid > rows > row[0] > vbox > description[1] > #text` contained a nodeValue of *Enter your password for username@domain.com on imap.domain.com*. (Indices here are 0-based, and the username and server names are correct/precise.)

The same location and text were used for querying the SMTP password. Both popups are single-field, just the password.

With CalDAV (SOGO Connector, Lightning), I found the same exact location gave me slightly different text: *A username and password are being requested by https://calendar.domain.com. The site says "ownCloud"*. This is a two-field form with "User Name:" and "Password:". In the image, they are in `row[1] > textbox > xul:hbox > html:input` (and `row[2] > ...`).

Does this help?

**Comment by dlech** [comment]
For IMAP, the title should be "Mail Server Password Required" (comes from https://mxr.mozilla.org/comm-central/source/suite/locales/en-US/chrome/mailnews/imapMsgs.properties#133).

In the KeeFox code, we are reading it from `Dialog.args.title` (at https://github.com/luckyrat/KeeFox/blob/master/Firefox%20addon/KeeFox/chrome/content/commonDialog.js#L327).

The "Enter your password..." that you found is the other part of the match that is returned by `Dialog.args.text`.

I think the DOM inspector also lets you look at javascript objects, so you can check these properties on the javascript object and also see if you can find "Mail Server Password Required" in the DOM (probably under info.title hopefully).

**Comment by r2evans** [comment]
Sorry, I remember now that at some point TB had no-title popups, and that was causing some problem. The current auth popup (for imap/smtp) does in fact show "Mail Server Password Required" in `info.title` and is shown on the popup; it is not hidden. For caldav auth, it gives "Authentication Required" instead. I had assumed you were trying to find a node that contained the username/server to tie it to a specific keepass entry.

I looked in the JS objects and didn't find `Dialog.args`, but then again it's a large model and I wasn't certain if you needed to find it in the JS object list or just confirm something. Let me know and I can dig with a better-informed eye.

**Comment by dlech** [comment]
Yes, I was under the impression the title was still missing, so sorry I've wasted a bit of your time looking in the wrong place.

I have found the source of the failure for IMAP: http://hg.mozilla.org/comm-central/rev/33593fa70bb9

We need to add a check [here](https://github.com/luckyrat/KeeFox/blob/master/Firefox%20addon/KeeFox/chrome/content/commonDialog.js#L312) that says: if imapEnterPasswordPrompt contains "%S" then call LoadDialogData as it is now, otherwise call it like pop3 below.

Is it just IMAP that is still broken or others as well?

**Comment by r2evans** [comment]
I'm glad you found the source for the failure; I wish I could have been more helpful.

IMAP, SMTP, and CalDAV are all broken (for me). They were all working before TB 40.0. I do not use POP3, but I assume it'd be consistent with IMAP.

**Comment by dlech** [comment]
SMTP could be because parentheses `()` were added. http://hg.mozilla.org/comm-central/diff/1def2116d8fc/suite/locales/en-US/chrome/mailnews/compose/composeMsgs.properties

I thought we already fixed that though in #466.

**Comment by r2evans** [comment]
Yeah, I see #388 and #466, but somehow TB has defeated you again :-)

**Comment by luckyrat** [comment]
This is in 1.6.1b1: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/beta

**Comment by r2evans** [comment]
Working great in TB45, thanks @luckyrat!

**Comment by luckyrat** [comment]
Thanks @dlech for the work that fixed the issue.

**Comment by r2evans** [comment]
@dlech, thanks, works like it used to. I had forgotten how "nicer" KeePass interfaces with TB with this feature working.
