### ISSUE TITLE
Matched logins popup appears on the wrong monitor

### ISSUE THREAD

**Issue by contre** [luckyrat/KeeFox#518]
I have three 1080p monitors setup horizontally with the following layout: 3 - 1 - 2. They are all set as extend so my total monitor size is 5760 x 1080. The X coordinates start on the left edge of the center monitor which means the range of possible valid X screen coordinates stretches from -1920 to 3840 or there about. I'm probably off by one in some direction.

Firefox is set to normally load on the farthest right monitor. I believe that a popup saying that Matched Logins were found appears on the middle monitor instead of the right monitor as expected.

I'm not sure how to force the popup to appear so I'm not certain that it always appears on the wrong monitor or not.

**Comment by contre** [comment]
I am using 1.5.3b5 and KeePass 2.30

**Comment by luckyrat** [comment]
There are known Firefox bugs relating to popups in 3 monitor setups. Unfortunately I don't know where to find them again right now but I suspect you'll find any potential workarounds and the ability to +1 a fix on Bugzilla.

**Comment by contre** [comment]
Did some searching but was unable to find anything that had any kind of workarounds. In addition, all of the ones I found seemed to be happening on linux so maybe I just don't have the right search terms.

I guess you can close this if you want to since it isn't an issue with your code.
