### ISSUE TITLE
[Windows 32bit] Keefox 1.4.8.1-signed crashes Firefox 40.0.2 on start

### ISSUE THREAD

**Issue by hillbicks** [luckyrat/KeeFox#524]
Hey huys,

apparently I'm the only one with this problem, at least I couldn't find anyone else with this problem. Since the latest update of Firefox, the browser crashes when the addon KeeFox is enabled, even if no other extension is enabled. KeePass is the portable version (2.25)

Here is the debug log that is created by firefox when it crashes.

http://pastebin.com/iXau42WM

Anything else I can provide?

**Comment by luckyrat** [comment]
Is there a link to some of the relevant Mozilla crash reports on your "about:crashes" page?

Take a look at those links in case Mozilla have already identified a bug causing the crashes.

If not just post the links here so I can take a quick look in case there are any clues that might indicate which part of Firefox is faulty.

As a possible fix, have you already tried doing a [Firefox reset](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings)? You'll have to reinstall your add-ons but if there is an unusual configuration in your current Firefox profile you might be triggering a bug that few other Firefox users come across so a new profile could by a quick way to avoid it.

**Comment by luckyrat** [comment]
Not reproducible.
