### ISSUE TITLE
When launching Keepass via Keefox, 50% of the time Keepass cannot be closed

### ISSUE THREAD

**Issue by tgp1994** [luckyrat/KeeFox#525]
Typically I log into my Keepass database right when I log onto my computer. If there is an instance where I chose not to for whatever reason, or I close Keepass at some point after logging in, Keefox will prompt me to log back in to my database.

If this occurs, and I do log in, 50% of the time I will not be able to "close" Keepass back to my notification area just like I have it configured to do so. Clicking on the X button will not do anything, whereas normally it will just close back into the notification area. The only thing I can do is go to File>Exit, then launch it again and log in.

**Comment by luckyrat** [comment]
Duplicate of #323 ?

**Comment by tgp1994** [comment]
Whoops, indeed it is, sorry about that. I'll go add my system information over in that issue to hopefully help out with this.
