### ISSUE TITLE
KeeFox does not do anything in FireFox Developer Edition

### ISSUE THREAD

**Issue by BAPostma** [luckyrat/KeeFox#526]
I've installed KeeFox into FireFox and FireFox Developer Edition.
The connection and all are set up and work fine in 'regular' FireFox. The filling of form fields and 'detect forms' options don't do anything in FireFox Developer Edition although the connection works fine in that version of the browser also.

(I wouldn't say it does not respond, because it does respond and nothing is crashing.)

**Comment by dlech** [comment]
Are you using version KeeFox 1.5.x from the development channel? It probably has to do with[e10s](https://wiki.mozilla.org/Electrolysis). Support for this was added in KeeFox 1.5.x.

**Comment by captainju** [comment]
Same problème here using FF dev edition.
I disabled "multi-process" in preferences, now everything is fine.

**Comment by luckyrat** [comment]
Disabling multi-process will not be an option for long (possibly less than 4 weeks) so everyone using Firefox developer edition (and eventually Firefox Beta) will have to upgrade to the KeeFox 1.5 beta soon.

Install it by expanding the "Development channel" section at the bottom of the AMO page (https://addons.mozilla.org/en-US/firefox/addon/keefox/#beta-channel) and clicking the yellow "Add to Firefox" button.

**Comment by BAPostma** [comment]
I have installed the version from the Development Channel. This one works like a charm.
