### ISSUE TITLE
When suggesting to save a password, only the first attempt is recorded

### ISSUE THREAD

**Issue by mxt3** [luckyrat/KeeFox#527]
When suggesting to save a password, only the first attempt is recorded. When a user needs multiple attempts, this behavior results in storing a wrong password of the first try in the database. I got this bug with Keefox 1.4.8.1.

**Comment by luckyrat** [comment]
I don't really understand the problem you're describing but please at least try the new version 1.5 and then clarify what happens and what you expect to happen: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/1.5.3
