### ISSUE TITLE
Renable password manager after unninstall keefox on thunderbird

### ISSUE THREAD

**Issue by jorgegaspar** [luckyrat/KeeFox#529]
Hello
I can't re-enable the default password manager on thunderbird after removing the keefox add-on.

UPDATE: after I reinstalled keefox 1.4.8.1, update it to 1.5.3b9 and then removed it. After restarting the thunderbird I already see the check box that say "using the password manager to save this password"

**Comment by dlech** [comment]
As you have seen, this has already been implemented in the latest version.
