### ISSUE TITLE
Keep search results until cleared or until a timeout

### ISSUE THREAD

**Issue by contre** [luckyrat/KeeFox#530]
I will sometimes use keefox to get a password for a non-website application since I usually have Firefox open but don't necessarily have keepass in the foreground.

However, if I need to copy the username and password, I have to search twice since as soon as I do the copy operation, the search is cleared when the menu closes.

Is there any possible way to prevent this behavior by either only clearing explicitly when the user requests it or perhaps with a timeout? I'd definitely suggest this as a configurable option since I am using this in a non-standard way and the current functionality will work for a majority of users.

This is definitely a feature request and not a bug report.

**Comment by luckyrat** [comment]
See #481 

It's already implemented in KeeFox 1.5
