### ISSUE TITLE
KeeFox Disabling Self on Firefox Aurora 42.0a2

### ISSUE THREAD

**Issue by N3X15** [luckyrat/KeeFox#531]
KeeFox is disabling itself on Firefox Aurora 42.0a2 (2015-09-03), which brings up the disable survey and causes keefox to actually disable on restart.  Firefox developers suspect that it's writing to a file on disk, invalidating the signing.

Firefox Developer Console (CTRL+ALT+SHIFT+I) does not show any errors relating to KeeFox.

Reproduction steps unavailable, as this occurs after several hours of browsing.

**Comment by luckyrat** [comment]
Do you/they know that it is a problem with signing validation that causes the disable to occur or is that just a theory?

KeeFox shouldn't be making any changes to its own directory (there's no code that would do that and if there were, I would expect more of the hundreds of beta testers would have come across this problem).

There could be something else that is modifying the KeeFox addon though. Maybe a badly behaved anti-virus application is deleting one of the files?

Or it could be a bug in Firefox Sync? If you're syncing multiple Firefox profiles together maybe it is disabled on one and that keeps incorrectly overriding the enabled state on your more recent (active) profile.

Can the Firefox devs suggest a way to enable more detailed logging about their add-on disabling process? That might provide a clue what is causing it.

I take it you're on a recent beta? I.e. 1.5.3b9 or 1.5.3b10. I can't think of any changes that might affect this behaviour but it would make sense to rule out a bug with an earlier beta version just in case there was a problem that went unnoticed before everyone upgraded to a newer version.

**Comment by N3X15** [comment]
right now, it's just a theory from the firefox devs.  I've tried multiple times to catch something keefox related in the console, but nothing ever pops up.

I'll try disabling sync and see if that improves things.

**Comment by N3X15** [comment]
Seems to have been resolved at some point.
