### ISSUE TITLE
Adding password from form to a group is broken

### ISSUE THREAD

**Issue by JSteunou** [luckyrat/KeeFox#535]
At least on my configuration:  ubuntu 15.04 / firefox 40 / keepass2 from official ubuntu repo / mono-complete installed / keefox 1.4.8.1-signed

```
Sun Sep 13 2015 14:01:32 GMT+0200 (CEST):INFO:  Filling document. Initial page load: true
Sun Sep 13 2015 14:01:32 GMT+0200 (CEST):INFO:  attempting document fill
Sun Sep 13 2015 14:01:50 GMT+0200 (CEST):INFO:  Adding login to group: 00322BC04CD9144B9B23580061631F2F in DB: null
Sun Sep 13 2015 14:01:50 GMT+0200 (CEST):ERROR: An error occurred in KeePassRPC object id: null with this message: undefined and this error: [object Object] and this error message: Expected a ',' or '}'. See line 1, position 1 171.
```

**Comment by luckyrat** [comment]
Please try v1.5.3: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/1.5.3

**Comment by JSteunou** [comment]
isnt 1.5 in beta?

**Comment by dlech** [comment]
Not since yesterday (13 september 2015).

**Comment by JSteunou** [comment]
Ah I missed it for a few hours :p

**Comment by luckyrat** [comment]
Yeah it was in beta when I posted here last but it was only waiting approval from Mozilla (which happened in record speed and was a pleasant surprise given their warnings of lengthy approval delays over the past couple of months).

Please let us know if the new version fixes your problem.
