### ISSUE TITLE
Keefox and KeePass in different name spaces

### ISSUE THREAD

**Issue by ehudkaldor** [luckyrat/KeeFox#538]
sorry for the vague subject line. 

i am running Keepass2 and Firefox with Keefox in two separate Docker containers. while each works fine by itself, i cannot get Keefox to connect to Keepass. the ports are the same (even tried changing them to make sure nothing else is holding the RPC port), but the Keefox logs keeps saying the connection is refused.

my hunch is that Keefox calls on localhost:port for RPC, and because localhost is local to the container, it does not get through. if so, is there a way to change that address?

**Comment by luckyrat** [comment]
There's currently no way to allow KeeFox and KeePassRPC to communicate directly over an external interface.

I think others have previously used SSH port forwarding to expose the remote server on a localhost port but I've not tried it myself and can't promise that it will work now or in future versions - we'd be interested to know if you have any luck with that approach.

**Comment by ehudkaldor** [comment]
Yup, verified the network assumption. When both containers are running as
"--net host" they find each other well.

**Comment by ehudkaldor** [comment]
are you closing it because you will not implement that? accessing Keepass running in a different ip namespace has its benefits.

**Comment by luckyrat** [comment]
Sorry, I thought you just wanted to find a way to make it work, which it sounded like you had.

If instead you want to enable KeeFox to communicate with KeePass directly over an external interface, you'll want to read and subscribe to #125 (but note that it's a complicated feature request which has been unmodified for 4 years and still references old authentication methods so I wouldn't hold your breath for an imminent implementation!)
