### ISSUE TITLE
Bug : Keefox v1.53 KeePassRPC.dll incompatible with KeePass v2.30

### ISSUE THREAD

**Issue by Hysteriana** [luckyrat/KeeFox#540]
see title.

fresh installed Keefox v.1.53
in start of KeePass v2.30 i get incompatibility warning about KeePassRPC.dll.

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/9871644/4aa8a972-5b95-11e5-84ff-511956261112.png)

**Comment by dlech** [comment]
It sounds like one of the .dll files in the .plgx didn't get copied correctly. Try clearing you plugin cache (under Tools > Plugins...) and restarting KeePass.

**Comment by Hysteriana** [comment]
jup thanks a lot. that worked.

**Comment by luckyrat** [comment]
Interesting behaviour. Probably the most likely cause is a dodgy anti-virus program but could potentially be a KeePass bug or hardware failure.

**Comment by syntacticvexation** [comment]
I had the same issue, the fix worked for me as well.

**Comment by noamik** [comment]
I had the same issue and clearing cache worked for me as well.
