### ISSUE TITLE
Notifications for matched logins

### ISSUE THREAD

**Issue by slovdahl** [luckyrat/KeeFox#541]
Starting from 1.5.3 I get notifications every now and then that a matching login has been found. I find these notifications very annoying, could you please make it possible to disable them?

**Comment by dlech** [comment]
This sounds like a duplicate of #410.

**Comment by luckyrat** [comment]
Yeah I might split that issue into a separate "option to disable notification" feature request but I'm not sure yet so for now lets keep all discussion of this behaviour to that one place.
