### ISSUE TITLE
Keefox asks to be installed again?

### ISSUE THREAD

**Issue by opencobalt** [luckyrat/KeeFox#545]
Hi there,

first off, I love KeeFox since it saves a great amount of time when working with many different passwords and such.

Anyway, since yesterday I experience a problem that Keefox asks to install again in a separate tab on Firefox start-up (as it did the very first time after installation of KeeFox addon). Until yesterday though it worked very well (and was properly installed already) for a long time. Not sure if it may be related to some auto-update to version 1.5.3 of KeeFox which messed anything up?

Firefox: Ver. 40.0.3
KeeFox: 1.5.3.
OS: Linux Mint 17.2 "Rafaela"

Any help is very appreciated. Thanks in advance.

Btw: The same issue I posted here in different words, which may be helpful: http://forums.linuxmint.com/viewtopic.php?f=47&t=205091

**Comment by dlech** [comment]
I maintain a KeePass plugin ppa that includes KeeFox. It takes care of this sort of thing automatically. See: <https://github.com/luckyrat/KeeFox/wiki/en-|-Installation-|-Linux#install-the-firefox-extension>

If you don't want to use the ppa, you need to manually copy the new KeePassRPC.plgx to your KeePass directory. See <https://github.com/luckyrat/KeeFox/wiki/en-|-Installation-|-Linux#install-the-keepassrpc-plugin>.

**Comment by opencobalt** [comment]
Thanks alot for your reply dlech! That worked out well and solved my problem.

You know what? I recognized what made this KeeFox update especially confusing to me. I use the German version of KeeFox and the translation in the installation tab which pops up on FireFox start-up seems a little bit off since it reads as if you have to put the KeePassRPC.plgx file right into the plugin folder (link kindly provided) for the FireFox plugins (and when I checked, I recognized that the most recent file is still there and so everything seemed to be fine and just have been confused why it would tell me to do so if it is already there). Now that I read the description you mentioned, it is clear to me I should have rather copied the file from there to the keepass2 plugin folder. 

One word switched the meaning here :-).

Anyway, thanks again.

**Comment by dlech** [comment]
If you would be willing to contribute a better translation, that would be helpful.

See: https://github.com/luckyrat/KeeFox/wiki/en-|-Contributing-|-Translation

**Comment by opencobalt** [comment]
Thanks for the hint, I corrected the wrong translation.
