### ISSUE TITLE
Cannot detect new logins after using KeeFox once

### ISSUE THREAD

**Issue by bbbco** [luckyrat/KeeFox#549]
I cannot detect new logins after using KeeFox once. I am using the latest released version, 1.5.3. Please note, I do have two Firefox profiles open at the same time using KeeFox.

Steps:

 - Open two different Firefox Profiles, both using KeeFox and the same database file
 - In one Firefox Profile, click to find a new login to open
 - Notice it opens the website in the current new tab, and logs in
 - Do your business, log out
 - Open a new tab
 - Click to find a different login to open
 - Notice the new tab loads the proper URL, but does not add login credentials
 - Click to "Find matching logins"
 - Notice no matching logins found
 - Notice you are stuck, and can't really do anything else until you restart the Firefox profile

I checked the log in DEBUG mode, and this this the logging that occurs when opening the new tab a second time and trying to login:

````
Sat Sep 19 2015 12:52:04 GMT-0400 (EDT):DEBUG: _onTabSelected.
Sat Sep 19 2015 12:52:04 GMT-0400 (EDT):DEBUG: panel showSearchResults started
Sat Sep 19 2015 12:52:04 GMT-0400 (EDT):DEBUG: Removing all matched logins
Sat Sep 19 2015 12:52:04 GMT-0400 (EDT):DEBUG: setupButton_ready start
Sat Sep 19 2015 12:52:04 GMT-0400 (EDT):DEBUG: Setting widget status
Sat Sep 19 2015 12:52:04 GMT-0400 (EDT):DEBUG: setupButton_ready end
Sat Sep 19 2015 12:52:06 GMT-0400 (EDT):DEBUG: onLocationChange keefox_win: 0
Sat Sep 19 2015 12:52:06 GMT-0400 (EDT):DEBUG: panel showSearchResults started
Sat Sep 19 2015 12:52:06 GMT-0400 (EDT):DEBUG: Removing all matched logins
Sat Sep 19 2015 12:52:06 GMT-0400 (EDT):DEBUG: setupButton_ready start
Sat Sep 19 2015 12:52:06 GMT-0400 (EDT):DEBUG: Setting widget status
Sat Sep 19 2015 12:52:06 GMT-0400 (EDT):DEBUG: setupButton_ready end
Sat Sep 19 2015 12:52:14 GMT-0400 (EDT):DEBUG: loading and auto submitting button 0false...
Sat Sep 19 2015 12:52:15 GMT-0400 (EDT):DEBUG: onLocationChange keefox_win: 0
Sat Sep 19 2015 12:52:15 GMT-0400 (EDT):DEBUG: panel showSearchResults started
Sat Sep 19 2015 12:52:15 GMT-0400 (EDT):DEBUG: Removing all matched logins
Sat Sep 19 2015 12:52:15 GMT-0400 (EDT):DEBUG: setupButton_ready start
Sat Sep 19 2015 12:52:15 GMT-0400 (EDT):DEBUG: Setting widget status
Sat Sep 19 2015 12:52:15 GMT-0400 (EDT):DEBUG: setupButton_ready end
````

Expectations:

 - I should be able to continue to use other logins after using the first login upon bringing up the Firefox profile.

**Comment by luckyrat** [comment]
> Open two different Firefox Profiles, both using KeeFox and the same database file

This is not what KeeFox is designed to do; it sounds like it doesn't work so you won't be able to do this.

The only known way to work with multiple Firefox profiles is to have multiple instances of KeePass, each configured to use a different KeePassRPC port.
