### ISSUE TITLE
Drop Mono Requirement

### ISSUE THREAD

**Issue by drankinatty** [luckyrat/KeeFox#551]
I installed, then promptly uninstalled, KeyFox due to the mono dependency. It is not needed by either KeePassX or KeyPass and should not be a KeyFox dependency. The current installed size of KeePassX 0.4.3 on Linux is 2965666 'bytes' (2.9M). The mono requirement for KeyFox requires an 'additional 75.3 MiB' of mono install. That is nonsense. 

Since both KeePassX and KeePass work completely independent of mono, there is no reason why KeyFox should attempt to drag in the mono behemoth thereby using 25 times more storage than required for the underlying application itself.

Programming efficiency is not something that just goes by the wayside because we have larger hard disks and faster internet. It is something that defines a project. Requiring mono here, seem to violate the very cornerstone of programming efficiency.

Your idea with KeyFox is great. It should at most use the native KeePassX or KeePass .kdb password database, or allow import from the existing database and saving as a separate "web.kdb" in the same location as the original. I know I would not want all data exposed to KeyFox, but a separate password database utilized by KeyFox would be fine. Allowing selective import from the original is fine as well, but a wholesale import should only be an option and not the default. 

You should provided database support for the standard .kdb password database format (and the base code may be better for KeyFox) as the .kdb format is useable by both KeePassX and KeePass on both Linux and Windows without issue. Keep up the good work, but ditch mono...

**Comment by luckyrat** [comment]
What is efficiency? For me, a key part of efficiency is being able to develop a complex cross-platform solution in a short enough amount of time that it can be done within a small number of years worth of spare time.

.Net/Mono met and still meets that requirement, not least because the kdb file format does not have the flexibility required for a complex addon like KeeFox and kdbx is already accessible via a .NET version of KeePass.

If you have more spare time than me and wish to develop something in an alternative language you are welcome to do so and you can find a variety of docs regarding KeeFox and KeePassRPC if you would like to make it compatible with the .NET version I develop.

**Comment by drankinatty** [comment]
Chris, I respect that. I've been developing with open-source for nearly 2 decades. Longtime user/packager for openSUSE, Archlinux, and developer for the Trinity Desktop Project (KDE3) on Archlinux among some. No I don't have any more time than you do, but when I run across what could be a phenomenal project that has made project choices that I've seen other projects regret, it is worthwhile to add a thought or two. Yes, the easy path is sometimes quicker in the short term, but you run the risk of betting on a horse that you have no control over .NET in particular. When that risk is present and it balloons the install size by 25 times, then is that really a good trade-off? 

I haven't torn either KeePass or KeeFox apart yet to see what would be involved to provide a .kdb backend instead of the .kdbx backend, but I did grab the source for both after installing and removing KeeFox. There is a simple elegance to be able to provide a solid package without the additional baggage .NET adds. Since KeePassX 0.4.3 provides the .kdb backend in both its windows and Linux version which is compatible with KeePass on both, it should not be that much more work.

I will take a look when I get a chance and report back. If I didn't think KeeFox was worth the effort, or if taking the time to implement .kdb and get rid of mono and .NET wasn't worth it, I wouldn't bother. You have a good project here, it's worth doing right.

**Comment by luckyrat** [comment]
No offence (and I am definitely interested to hear where your investigations end up) but this issue just isn't within scope of the project so I'm closing it to help me focus on the hundreds of issues that just might be.
