### ISSUE TITLE
KeePass RPC doesn't save "Authorized Connections" across app starts

### ISSUE THREAD

**Issue by MeanderingCode** [luckyrat/KeeFox#552]
Every time I launch KeePass2, it asks me to authorize Firefox/Keefox.  I have opened my password database before authorizing in order to check the authorized connections, and it is always empty.  Authorizing works, putting an entry in the table, it is just not saved across app close and start.

I am on a linux system, running KeePass under mono, and the KeePass folder and all files and folders therein (including the KeePassRPC.pglx and the other KeeFox plugin files) are owned by root.

**Comment by luckyrat** [comment]
See: https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting#keepassrpc-authorisation
