### ISSUE TITLE
Several versions of Firefox repeatedly lose the KeeFox toolbar icon

### ISSUE THREAD

**Issue by dertuxmalwieder** [luckyrat/KeeFox#553]
It seems that recent KeeFox versions [randomly forget](/https://8pecxstudios.com/Forums/viewtopic.php?f=5&t=1175) that they are pinned to the toolbar.

Tested on Windows 10.

**Comment by luckyrat** [comment]
> Since I installed KeeFox, my uMatrix icon has not disappeared anymore...

Doesn't sound like it's anything to do with KeeFox. Possibly a Firefox bug.

If KeeFox is failing to start at all there should be some errors in the console or KeeFox logs but it sounds like it's a bug with the positioning of the KeeFox button which is completely out of KeeFox's control and therefore a bug with the browser.

I saw similar issues with early builds of the Australis interface last year so maybe it's a regression or maybe you just need to reset your Firefox profile and start over with a fresh add-on installation.

**Comment by dertuxmalwieder** [comment]
KeeFox starts (I get the popups), but its icon is gone. I had this on various machines/profiles...

**Comment by luckyrat** [comment]
Yeah so that definitely sounds like a browser bug.

**Comment by akwala** [comment]
The toolbar button went missing in one of my FX profiles. In the Customize panel, I clicked the Restore Defaults button in the lower-right corner. Then, I clicked the Undo button that appeared next to it. This returned the button to the navigation toolbar.

YMMV.
