### ISSUE TITLE
Keefox 1.5 beta glitch on Plasma 5 (effects disabled)

### ISSUE THREAD

**Issue by tancrackers** [luckyrat/KeeFox#554]
When using Keefox 1.5 beta on KDE Plasma 5, everything is fine unless KWin effects are disabled.
When the effects of KWin are disabled, Keefox prompts get cut off:
https://i.imgur.com/KB9Aqpg.png
And the cut off menu actually showed after taking that ^ screenshot:
https://i.imgur.com/bBxfxTa.png

Arch Linux
Plasma 5.4.1
Firefox 41.0
Keefox 1.5.3b12

When a site password (or favicon) gets updated, the menu is presented distorted when you click "update existing entry." However, you can bring up another window (like another running program or something) and the Keefox prompt will appear as it's supposed to.

**Comment by luckyrat** [comment]
I don't know what Plasma of KWin effects are but it doesn't sound like this could be a KeeFox bug.

**Comment by tancrackers** [comment]
KDE Desktop Environment:
https://en.wikipedia.org/wiki/KDE

KDE Plasma 5 Desktop:
https://en.wikipedia.org/wiki/KDE_Plasma_5
(Plasma 5 is the successor of Plasma 4, which was very different).

KWin:
https://userbase.kde.org/KWin

Kubuntu 15.04 uses Plasma 5:
http://www.kubuntu.org/

I'll try to find a way to analyse this problem the best that I can.

**Comment by luckyrat** [comment]
I'm closing this because it sounds like a bug in one of those Linux components or Firefox and even finding a way to work around the issue by changing KeeFox is unlikely.

**Comment by tancrackers** [comment]
I wanted to give an update- after an update to Plasma 5.4.2, this bug is no longer present for me.
