### ISSUE TITLE
Add an option to disable "Matched Logins Found" notifications

### ISSUE THREAD

**Issue by thvasilo** [luckyrat/KeeFox#555]
The new version seems to have brought a pop-up notification when matched logins have been found.

Is there an option to disable this notification somehow?

**Comment by n-st** [comment]
Same here (Firefox 41.0, KeeFox 1.5.3).
Those notifications are bloody annoying.

**Comment by luckyrat** [comment]
I've added an option to disable these notifications. I don't have time to make it granular so it's all or nothing I'm afraid. Still, given the negative reaction some users have had to the presence of the notifications I guess being able to disable them entirely is better than having no control at all.

At the moment I'm planning to expose this setting in the KeeFox options panel but it's a complex option to describe which might be too much for average users to understand so I could relegate it to an about:config setting before this makes it to a stable release.

For the record, the relevant config setting is `extensions.keefox@chris.tomlinson.notifyWhenLateDiscovery`

The untested (and obviously unsigned) XPI can be found here: https://github.com/luckyrat/KeeFox/releases/tag/v1.5.4a1

I've got no current plans to release it to the AMO beta channel but it will happen eventually (potentially with adjustments to the option exposure as explained above).

**Comment by luckyrat** [comment]
This will probably make it into a beta in around one week.

**Comment by cfassett** [comment]
I just wanted to thank you for this -- solves this issue for me!

**Comment by MethylBromide** [comment]
This is seriously annoying, and it appears the option to disable it doesn't yet exist in the main codestream. We don't want to install an unsigned addon that must already be seriously out of date. Can we PLEASE make this happen? Even if there's no UI but just an option in about:config, at least it would give us a way to tell our people to disable it.
