### ISSUE TITLE
Keefox broken on latest nightly

### ISSUE THREAD

**Issue by hooloovoo79** [luckyrat/KeeFox#562]
Keefox no longer works with the latest nightly (and likely will not work with any subsequent ones) because of changes to let, var, and const.

You can read about this here:
https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/
https://groups.google.com/forum/#!topic/mozilla.dev.platform/XoW35OxqDYI

These were in the error console too. Hopefully they will help get you started fixing:

TypeError: redeclaration of let Cc
<anonymous> SearchFilter.js:23
<anonymous> keefoxWin.js:48
SearchFilter.js:23:1

ReferenceError: keefox_org is not defined1 context.xul:7:4

**Comment by luckyrat** [comment]
Thanks for the warning. I'll investigate.

**Comment by luckyrat** [comment]
https://github.com/luckyrat/KeeFox/releases/tag/v1.5.4a2 is a smoke-tested version that works with Firefox 44.

More testing is required - the joy of dynamic languages mean there is no quick way to verify that no code paths still fail with the new let standards and this also hasn't been tested at all in any Firefox earlier than 44 but I'm not sure when I'll have time to do this so I wanted to post a potentially working version now.

**Comment by luckyrat** [comment]
https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/ has given me lots more information about the changes and following a fresh review of KeeFox code it doesn't look like I've missed any massive areas of functionality in my earlier tests so 1.5.4a2 should be good to go on FF44 at least (it'll still be a while before I can test earlier versions back to FF29).

**Comment by skibbipl** [comment]
I can confirm that 1.5.4a2 is working fine on my nightly. Please update it on Mozilla site so I can turn on addon verification checks :)
