### ISSUE TITLE
Clash with "Privacy Badger" add-on

### ISSUE THREAD

**Issue by rbrownwsws** [luckyrat/KeeFox#564]
I just discovered a clash between KeeFox and the Privacy badger add-on that would be useful to add to the troubleshooting wiki page at:

https://github.com/luckyrat/KeeFox/wiki/en-|-Troubleshooting#keefox-panel-has-a-launch-keepass-button

Privacy Badger attempts to learn which sites are tracking you and then automatically block them.
It seems to get a false positive from KeeFox as after a while it will block 127.0.0.1 and you will get the message "KeeFox cannot connect to KeePass. A firewall is probably blocking port ...".
This can be a bit confusing as KeeFox will actually work for quite a while before Privacy Badger decides to block it.

This can be fixed going into the Privacy Badger options page (Privacy Badger button -> Options gear -> Fliter settings)
Then moving the slider for "127.0.0.1" to "Allowed"

**Comment by rbrownwsws** [comment]
Oops, I didn't notice anyone has permission to edit the wiki.

**Comment by luckyrat** [comment]
Thanks!
