### ISSUE TITLE
Can't use with TOR

### ISSUE THREAD

**Issue by AugierLe42e** [luckyrat/KeeFox#565]
KeeFox gets disconnected when using with TOR.

**Comment by luckyrat** [comment]
TOR should understand the concept of local network communication and allow it to function correctly. Maybe there is an option you need to enable?

It doesn't look like there's anything here that KeeFox could do differently but please provide more details if there's something you think would help.

**Comment by AugierLe42e** [comment]
I'm using Tor on Firefox with FoxyProxy. The localhost address are blacklisted (do not pass through Tor). RegEx is `^https?://(?:[^:@/]+(?::[^@/]+)?@)?(?:localhost|127\.\d+\.\d+\.\d+)(?::\d+)?(?:/.*)?$` if that help. Tell me if you need more informations.

**Comment by AugierLe42e** [comment]
I have news about this. The problem only appears when KeeFox tries to connect to KeePass for the first time. When I disable FoxyProxy to let KeeFox connect to KeePass, then it works well and I can enable FoxyProxy again.

**Comment by luckyrat** [comment]
This is already covered in the troubleshooting part of the manual at https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting#keefox-panel-has-a-launch-keepass-button

**Comment by AugierLe42e** [comment]
Nice. Thx.
