### ISSUE TITLE
KeeFox asks to save existing passwords after automatically filling in the form.

### ISSUE THREAD

**Issue by dlech** [luckyrat/KeeFox#570]
This happens to me for most existing password entries. 

* I go to a web page with a login.
* KeeFox automatically fills in my username and password.
* I click the OK/Submit button (I have the option to just "Fill in the form", so not automatically submitting)
* KeeFox pops up asking me if I want to save the password that it just automatically entered.
* I have to re-save the password that was already saved and working properly.
* Repeat for almost every site that I have a login for.

This was discussed in #483 a bit in which the password saving process was improved, but the underlying issue of why I have to re-save so many passwords in the first place was not addressed.

**Comment by dlech** [comment]
Comments from @RizzoV on the subject:

> > I've just installed KeePass and KeeFox, imported my LastPass database and started using them. When I go on a website where KeePass knows the credentials, imported by LastPass, KeeFox succesfully fills the forms, but after the login it asks if I want to save the password again. The only way to avoid that is to actually save it, through KeeFox, creating a doublet. Is this a my problem or not?

> Just tried with Amazon and DropBox, I saved the credentials with KeeFox also if they were already in the database (imported from LastPass and correctly form-filled) and compared the old and the new URL: the only different part is "https://www.amazon.com/ap/[this]" and "https://www.dropbox.com/[this]".

> EDIT: Just tried also CircuitLab, and I found this funny because the old LastPass URL was more generic than the new one generated by KeeFox: the old one was "https://www.circuitlab.com", the new one is "https://www.circuitlab.com/accounts/login/?next=/".

**Comment by luckyrat** [comment]
I guess this can happen on some websites where the URL changes from one login session to the next. Maybe if there are multiple pages that show the login form and you don't log in from the same one each time?

**Comment by EuMMCR** [comment]
In my case, KeeFox asks me to save or update the password if the URL does not exactly match the saved URL, also if it is just http and https.
However, the password field auto fill algorithm seems to ignore these URL differences (does not matter if http or https), so users may be confused about this (Why does KeeFox recognize the password field but does not know that the login data is already saved in KeePass?).

**Comment by luckyrat** [comment]
If we just ignore URL changes (or allow the same rules as when filling in the form) users will be stuck without a way to update their entry when the website changes the URL of their login form.

This might not matter so much anymore since we now default to more relaxed domain-wide password matching but I'm still a bit uneasy about potentially allowing users to leave stale URLs in their entries without them knowing about it.

Also, if we were to ignore all/more URL changes upon form submission, there might be problems on sites where people have multiple logins for different accounts.

**Comment by luckyrat** [comment]
The most accurate approach here would be to consider the current configuration of each KeePass entry but we don't have that level of detail in KeeFox so without tons of extra work the best we can do is to just always ignore URL changes (so only subdomain changes might trigger a password update dialog if the username and password data matches). It's not perfect but I think given the feedback over the past 6 months this approach is likely to be better for most people at most times. It's also a trivial code change so very easy to switch back if there is some unexpected side-effect during beta testing.
