### ISSUE TITLE
1.5.4b1 does not work on Thunderbird

### ISSUE THREAD

**Issue by crazy-max** [luckyrat/KeeFox#573]
Hi,

Windows 10 64-bits
Keepass 2.30
Thunderbird 38.3.0 (French)
Keefox 1.5.4b1

I can't make things work with the latest beta release, the prompt window is not autofilled and a message says that Keepass is locked or closed.

Works on 1.5.3

**Comment by dlech** [comment]
Did you upgrade KeePassRPC (the KeePass plugin part of KeeFox) as well?

**Comment by crazy-max** [comment]
Oh my bad -_-
