### ISSUE TITLE
Add KeePassRPC on Keepass update check ?

### ISSUE THREAD

**Issue by crazy-max** [luckyrat/KeeFox#574]
Hi,

For now KeePassRPC update status is not integrated, can you provide it or it's linked to Keefox ?

![image1](https://cloud.githubusercontent.com/assets/1951866/10852636/085ccf6a-7f32-11e5-8356-e22497d62e04.png)

Thanks!

**Comment by luckyrat** [comment]
It's linked to KeeFox. Running the latest available KeePassRPC version might break KeeFox so this KeePass update check is not relevant to KeePassRPC and KeeFox.
