### ISSUE TITLE
form with multiple matches can't be override

### ISSUE THREAD

**Issue by robsonsobral** [luckyrat/KeeFox#575]
Hi!

I just started to use Keefox and if "Forms with multiple matches should be filled..." is enable the right login can't be picked. The first one keeps being used to fill the form.

I'm using 1.5.4a2 on Firefox 44.0a2.

Thank you for the addon and for your attention.

**Comment by luckyrat** [comment]
I'm sorry but I don't understand what you're trying to describe. I typically have "Forms with multiple matches should be filled" enabled and have never had any problem selecting the correct login for the sites I use.

Is there a problem with the current behaviour for you? If so, how can I reproduce on my machine and what do you expect to happen instead?

**Comment by robsonsobral** [comment]
Hi! Let me give an example. I tried to open the CP of my router. I've older entries saved to the same IP.

KeeFox filled the form using the wrong entry. So, I chose the right one. But it keeps replacing it by the wrong before I even get the chance to submit the form.

Thank you for your attention.

**Comment by luckyrat** [comment]
Is this a standard web form or a HTTP Auth popup dialog like the one below?

![httpauthenticationexample](https://cloud.githubusercontent.com/assets/1211375/11056946/c76cf732-877e-11e5-9e10-8d94afc703e0.png)

**Comment by robsonsobral** [comment]
It's a web form, but... It stopped! It's working now! I just tested again. I don't know what I changed from yesterday to now.

Maybe is something related to the Firefox Developer Edition, which is updated everyday.

I'm really sorry for bother you!
