### ISSUE TITLE
When starting, KeeFox cannot find KeePassRPC.plgx

### ISSUE THREAD

**Issue by temmokan** [luckyrat/KeeFox#576]
Operating system: Ubuntu 14.04 64-bit
Firefox: 41.0.2, from standard repository
KeeFox: 1.5.3, installed after lookup with standard Firefox tool

Problem: every time Firefox starts, Keefox opens window with instructions on installing KeePassRPC.plgx file. KeepAss2 is installed in /usr/lib/keepass2; creating plugins directory beneath that directory and copying the mentioned file there doesn't help. Plugin is unusable as a result.

There are no other KeePassRPC.plgx files, except in in plugin installation directory (file:////<firefox profile root>/extensions/keefox@chris.tomlinson/deps

Path to Mono (/usr/bin/mono ) specified correctly

KeepAss2 version: 2.25+dfsg-1ubuntu0.1
Mono version: 3.2.8

**Comment by dlech** [comment]
You need to copy KeePassRPC.plgx from `file://///extensions/keefox@chris.tomlinson/deps` to `/usr/lib/keepass2/plugins/`.

    sudo mkdir /usr/lib/keepass2/plugins/
    sudo cp ~/.mozilla/firefox/random.default/extensions/keefox@chris.tomlinson/deps/KeePassRPC.plgx /usr/lib/keepass2/plugins/

where `random.default` is your profile directory - it contains random characters and will be different for everyone.

Or, you can install KeeFox from a ppa.

See <https://github.com/luckyrat/KeeFox/wiki/en-|-Installation-|-Linux> for more info.

**Comment by temmokan** [comment]
I have copied that file as you mentioned.

The problem was that KeepAss2 must be restarted after the above file update, that step isn't explicitly described in upgarde notice (should be added, I think, otherwise KeeFox will just tell again and again to copy the file).

Thanks.
