### ISSUE TITLE
httpauth not working with autofill

### ISSUE THREAD

**Issue by prometheanfire** [luckyrat/KeeFox#588]
also doesn't show the dropdown
seems to work with normal sites (amazon works for instance)
Whether there's a port number in the url doesn't seem to matter

This is with firefox 42.0 (linux) keepass 2.30 and keefox 1.5.4

This stopped working a while ago but it's finally gotten annoying enough to warrant a bug

**Comment by dlech** [comment]
Can you give an example of a website that does not work. Also, could you post a screenshot of the password dialog that does not work.

**Comment by prometheanfire** [comment]
ok, I just tested in another firefox profile (no other addons) and it's working.  Gonna figure out which addon it is now.

**Comment by prometheanfire** [comment]
Looks like it was the Master Password+ addon, if you want to investigate.
