### ISSUE TITLE
Can't connect to Keepass after 1.5.4 update

### ISSUE THREAD

**Issue by fgianneschi** [luckyrat/KeeFox#590]
Firefox 43 (Mozilla Firefox for Ubuntu 14.04 LTS), Keepass 2.30 and KeePassRPC 2.0.15.26680.

Since I've updated to 1.5.4, KeeFox can't connect to Keepass and it continues to show the "Setup KeeFox" orange page. Version 1.5.3 seems to work well.

Looking at the DEBUG log, this is what I've found. I don't know where I can download the "version 66819" and where I can find the "KeePassRPC upgrade" that it demands at the last line...

Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: Notifying interested observers that the websocket has closed
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: Pausing KeeFox.
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: panel showSearchResults started
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: Removing all matched logins
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_ready start
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_install start
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: Setting widget status
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_install end
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_ready end
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setAllLogins start
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setAllLogins end
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_ready start
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_install start
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: Setting widget status
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_install end
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: setupButton_ready end
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):INFO: Disconnecting from RPC server
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):INFO: KeeFox paused.
Fri Dec 18 2015 00:03:06 GMT+0100 (CET):DEBUG: Websocket connection closed
Fri Dec 18 2015 00:03:08 GMT+0100 (CET):INFO: HTTP connection not refused. We will now cancel the connection, maintaining the existing status code.
Fri Dec 18 2015 00:03:08 GMT+0100 (CET):INFO: HTTP connection not refused. We will now attempt a web socket connection.
Fri Dec 18 2015 00:03:08 GMT+0100 (CET):DEBUG: Attempting to connect to RPC server webSocket.
Fri Dec 18 2015 00:03:08 GMT+0100 (CET):DEBUG: Trying to open a webSocket connection
Fri Dec 18 2015 00:03:08 GMT+0100 (CET):INFO: Websocket connection opened
Fri Dec 18 2015 00:03:08 GMT+0100 (CET):DEBUG: received message from web socket
Fri Dec 18 2015 00:03:08 GMT+0100 (CET):ERROR: You must downgrade to version 66819 or upgrade KeePassRPC to match your version of KeeFox. Going to initiate the upgrade wizard now.

**Comment by dlech** [comment]
Duplicate of #586?

**Comment by luckyrat** [comment]
The required version is included with KeeFox so if you follow the instructions on the setup page (copy the KeePassRPC.plgx file) it should work. If not, look at the troubleshooting page on the wiki.

**Comment by joachim-k** [comment]
Firefox 43 (Mozilla Firefox for LinuxMint 17.2), Keepass 2.30 and KeePassRPC 2.0.15.14078.

Same problem as fgianneschi.

Since I've updated to 1.5.4, KeeFox can't connect to Keepass and it continues to show the "Setup KeeFox" orange page. Version 1.5.3 works well.
The file KeePassRPC is from the latest version from KeeFox and I've copied it to the plugin-directory. But KeeFox can't connect to Keepass and it continues to show the "Setup KeeFox" orange page. I'am going back to V.1.5.3 and all works fine. What's wrong?

**Comment by joachim-k** [comment]
It seems to work well now. Its Important, to restart KeePass after copy the new KeePassRPC! Now its working with KeePassRPC 2.0.15.16660. Sorry for the trouble.

**Comment by fgianneschi** [comment]
I've solved the issue, and it wasn't caused by KeeFox. As stated on the troubleshooting page: "Make sure that you have exactly one KeePassRPC.plgx file in your KeePass program folder. KeeFox installs the plugin to a subfolder called "plugins" but KeePass will load any plugin it finds in either its own folder or any subfolder. "
I had an old version of the KeePassRPC.plgx file on another folder of my KeePass installation, and this duplication was the root cause of the problem.
So I'm closing this issue, thanks to all.
