### ISSUE TITLE
Keefox broken on Nightly again

### ISSUE THREAD

**Issue by hooloovoo79** [luckyrat/KeeFox#598]
Keefox stopped working with today's nightly. Error console says this:

SyntaxError: missing ] after element list
		<anonymous> kprpcClientLegacy.js:43
		<anonymous> kprpcClient.js:35
		<anonymous> jsonrpcClient.js:32
		<anonymous> KF.js:36
		<anonymous> keefoxWin.js:53
utils.js:589:51

ReferenceError: keefox_org is not defined
context.xul:7:4

Someone posted about another extension breaking and pointed to this bug about arrays/generators and it seems like it may be relevant:
https://bugzilla.mozilla.org/show_bug.cgi?id=1220564

**Comment by luckyrat** [comment]
Thanks. Looks like it's due to the removal of that array comprehension syntax. I'm working on a fix.

**Comment by luckyrat** [comment]
See https://github.com/luckyrat/KeeFox/releases/tag/v1.5.5b1

**Comment by Dimas-sc** [comment]
Thx, 1.5.5b1 is working (not with 1.6b1)
