### ISSUE TITLE
Increase minimum .NET requirement

### ISSUE THREAD

**Issue by luckyrat** [luckyrat/KeeFox#600]
It's about time we stop supporting .NET (C#) 2.

I expect to increase the minimum requirement to .NET 3.5 but might go as far as 4.0 if it's deployed widely enough among current users.

**Comment by dlech** [comment]
FWIW, I've been using a minimum of 4.0 on my KeeAgent plugin since 2012 with only a couple complaints from XP users.

**Comment by luckyrat** [comment]
Yeah it's definitely going to be easier to switch wholesale to CLR 4 and there are less than 0.5% of active users stuck on < .NET 4 so I think it's reasonable to up the requirement all the way to .NET 4.0.

FTR, .NET 2.0 usage is at about 0.01% and .NET 4.0 is at 3%

There's also a strong correlation between users that are on < .NET 4.0 and still stuck on very old KeePass versions (2.20±3); also a slight correlation between those same users and older KeeFox versions and older Firefox versions.

So I think the version bump is also justifiable from the perspective of encouraging these users to upgrade to a non-ancient version of their security software.

All these figures ignore non-Windows users. A brief look at Linux users doesn't reveal any that use Mono 2.6 or lower so we shouldn't be concerned with that either (given how many bugs there have been with KeePass on Mono in the past I guess this 100% migration into .NET 4.0 compatible versions is to be expected).

**Comment by luckyrat** [comment]
Still needs testing on various test VMs before it's ready for beta testing.
