### ISSUE TITLE
Keefox 1.5.4 broken in latest Nightly Firefox

### ISSUE THREAD

**Issue by Larusek** [luckyrat/KeeFox#602]
Hi.
Since few Nightly builds Keefox has been broken. Add-on loads but there aren't any options in right-click menu. The toolbar icon is also missing. Simply put the addon can't be used.

Can you confirm the problem?

**Comment by Larusek** [comment]
Now I see a new beta version. I can swear that as early as today morning the latest release was still 1.5.4 ;-) Definitely not 3 days ago :D

**Comment by luckyrat** [comment]
Well the beta is not actually on the official beta channel yet (only here on github) so maybe that's why you missed it this morning.

Duplicate of #598
