### ISSUE TITLE
KeeFox not working in Firefox Nightly 46.0a1

### ISSUE THREAD

**Issue by xilef6000** [luckyrat/KeeFox#604]
Hey dear developer(s),
KeeFox is not working anymore after the last Update for Firefox Nightly.

`Build-ID: 20160112030227`
`User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0`
`System: Windows 7 (SP1) x64`

The Icon (in the addonbar) is not showing up, the KeeFox entries in the right-klick-context-menu are not showing any text (See http://puu.sh/mufZ6/67482fecf3.jpg), autofill does not work.
It's like KeeFox is not installed. (It is installed, I've checked that already ;-) )

Felix

**Comment by db48x** [comment]
Incidentally, I went to poke at it with a debugger just now and found that I couldn't connect the debugger to Firefox. A little more digging and I found that it's actually KeeFox which is accidentally preventing this from working. I get this error in the browser console every time I try to accept the remote debugging connection:

    TypeError: keeFoxDialogManager is undefined

**Comment by luckyrat** [comment]
#598
