### ISSUE TITLE
KeePass asking to save credentials on every login, even when populating the fields

### ISSUE THREAD

**Issue by ajahart** [luckyrat/KeeFox#607]
If logging into a website, such as github, where the base url is the same (aka, https://github.com) but the uri is different (aka, "https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fluckyrat%2FKeeFox%2Fissues%2Fnew" as opposed to https://github.com/login) it will populate the login yet ask if i would like to save or overwrite.  I think keefox should assume since the base url is the same, the login creds are the same and no prompt is necessary.

This happens with almost all websites that redirect login to previous page, in other words 95% of websites (facebook, google, twitter, github, etc etc)

more specific info for issue#118 which was closed with no solution

**Comment by luckyrat** [comment]
Fixed in v1.6 - #570
