### ISSUE TITLE
KeeFox should NOT try to handle GET forms

### ISSUE THREAD

**Issue by BoffinbraiN** [luckyrat/KeeFox#611]
KeeFox doesn't consider the `method` attribute of a form, so it will happily do the following things:

- put login credentials into a GET form
- ask to save a new login if a GET form is submitted

**Comment by luckyrat** [comment]
This is exactly what KeeFox should do and is often useful behaviour.

**Comment by BoffinbraiN** [comment]
Surely this will encourage people to send sensitive information in ways that will be easily seen by others, or even result in them disclosing passwords by accident when they use a search form on a website where they have a saved login. KeeFox's entire purpose is for storing information securely. Firefox's regular form autofill is surely a better method for regular GET forms.

**Comment by luckyrat** [comment]
I don't think it directly encourages anything, it just allows KeeFox to work with more login forms (which should encourage more secure storage and selection of passwords in general). It would be good if all login forms were secure but it's not KeeFox's role to enforce that.

Accidental disclosure is a different issue (hopefully rare, but ultimately not limited to GET forms so the solution to any problem like that would reside elsewhere)

**Comment by BoffinbraiN** [comment]
Okay... But I still think this is a strange design choice. Making it optional would be nice, since getting prompts every time I use search forms is rather irritating.

**Comment by luckyrat** [comment]
You should not be getting prompts every time you use search forms. I suspect non-English users would suffer from that a bit more and it can't be completely eliminated but I've not come across any cases where this has happened to me in the past couple of years - maybe I'm just lucky with my choice of websites.

If there's a specific form that causes you trouble, you should look into whether it is sensible to add some relevant entries to the blacklists in the [site-specific config](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Tips-%7C-Site-Specific). If there are common entries that could be safely added to the default blacklists then let me know so everyone can benefit from the change in a future KeeFox version
