### ISSUE TITLE
KeeFox popup prompts should try to appear inside the window, not outside

### ISSUE THREAD

**Issue by BoffinbraiN** [luckyrat/KeeFox#615]
Minor issue. The popup that appears when pressing the KeeFox toolbar button appears to do the right thing, but password prompts will go outside the right edge of the window if there is room on the screen to do so.

![popupoutsidewindow](https://cloud.githubusercontent.com/assets/13255058/12920929/b379e30a-cf42-11e5-95ca-be02333965c2.png)

**Comment by luckyrat** [comment]
This is Firefox's behaviour. I know there have been quite a few bugs in this area over the years, especially on Linux and I think some have been around for a decade with little hope of Mozilla finding time to resolve them without a large-scale Firefox rewrite (that might happen in the next few years, although it's unclear whether this will also EOL KeeFox)

**Comment by BoffinbraiN** [comment]
That's odd, since Firefox's own popups always behave correctly for me on Windows - the main menu and bookmark menus on the right throw to the left, and the site info popup on the left throws to the right.

**Comment by luckyrat** [comment]
It depends on the contents of the panels - there are some bugs that can lead to incorrect sizes being calculated inside Firefox when complex UIs are needed inside the popups so perhaps that causes Firefox to choose the incorrect approach to dealing with the KeeFox panel.

**Comment by BoffinbraiN** [comment]
Does the popup bubble get shown after the prompt gets added to the contents, or is it shown first? Maybe it's briefly seeing an empty popup?

**Comment by luckyrat** [comment]
It should be already available when the popup is shown but you're right that there could be bugs which cause it to calculate the size/position based on an incomplete rendering of the popup contents.

**Comment by alexkaskasoli** [comment]
Just FYI, this issue makes KeeFox completely unusable in a Linux window tiling manager such as AwesomeWM or i3. It's not even possible to manually drag the window back within screen view. I'm unfortunately going to have to look for another solution because of this.

I have no experience in Firefox plugin development, but it looks like you guys are using custom HTML UI for your popup/dropdown menus instead of the standard looking menus my other Firefox plugins use. Could this be the source of your problem?

**Comment by Spheerys** [comment]
I'm in the same configuration than alx-k (Firefox/Linux under i3wm) and I confirm the problem with this popup : I had to moved it each time, with strange buggy interface...

But I have found a workaround by moving the KeeFox icon on the left, between the URL bar and the Search case. But It could be moved on the left of URL bar if needed.

**Comment by BoffinbraiN** [comment]
@luckyrat Any change you can look into this again? As you can see, several people are affected.

**Comment by fmartingr** [comment]
This is happening to me too on linux and even if I tried to give it custom properties (via i3wm for_window) it seems that is statically anchored to the icon. Maybe a preference to use a simple popup window? Not sure if possible though. Using @Spheerys workaround ATM.
