### ISSUE TITLE
Remove the KeeFox context menu entries or make it optional

### ISSUE THREAD

**Issue by BoffinbraiN** [luckyrat/KeeFox#618]
Too many Firefox addons automatically add clutter to the page context menu, and it ends up being ridiculously long. In the case of KeeFox, that would be the 'Generate new password' and 'Find matching logons'

For me, if I wanted to create a logon for a site, I would either type it, submit, and wait for the prompt, or explicitly press the KeeFox menu button and go from there. I would imagine most other users would do the same.

I don't think a context menu entry is necessary for KeeFox because of these methods of access already available, and also because the KeeFox menu item does not require any additional context i.e. it doesn't care what you are right-clicking on, unlike other commands such as copy, paste, inspect and so on. (The 'Find matching logons' option might actually be contextual, given that it only works on input fields, but the 'Generate new password' does not.)

**Comment by luckyrat** [comment]
#381
