### ISSUE TITLE
Does not properly set radio buttons which have a name but no id attribute

### ISSUE THREAD

**Issue by elgonzo** [luckyrat/KeeFox#620]
Certain web sites offer a log-in form having two radio buttons which allow a user to either log-in or register a new account.

It can happen that those radio button elements only have a name but no id defined. Something like this:
```
<input type="radio" name="action" value="register">
<input type="radio" name="action" value="login">
```
Note the order of the elements -- the radio button for registering a new account comes first, followed by the radio button for logging on with an existing user account.

Unfortunately, trying to select the login radio box through KeeFox like (JSON snippet from _KPRPC JSON_ string field)
```
{"name":"action","displayName":"action","value":"login","type":"FFTradio","id":"","page":1}
```
will not work in this case. As it seems, when no element id is defined KeeFox will simply search for the **first** Radio button with the given name ("action") while completely ignoring the value given in the JSON snippet, and thus falsely checking the register radio button.

What i think KeeFox should do if a radio button element without a defined id is to be set: Search for a radio button which has a matching name **AND** value. Only if both name and value are matched, select the radio button (i.e., set its checked property to true).

----
A real-life site using radio buttons like i described above: www.forum64.de/wbb4/
To open the log-in form, click the respective link in the upper left corner of the page.
_(FYI: With respect to this particular site, i could workaround this issue by deleting the radio button form field from the KeePass/KeeFox entry, because this site has the log-in radio button checked by default.)_

KeeFox 1.5.4
FireFox 44.0.1 x64
Windows 7 Pro x64, english

**Comment by luckyrat** [comment]
Yeah we should really be considering the value attribute too. Thanks for the clear explanation of the issue, I'll try to get it fixed soon.
