### ISSUE TITLE
Accessing groups/folders in Keepass fails

### ISSUE THREAD

**Issue by M1NDHUNT3R** [luckyrat/KeeFox#625]
Hi, first: thank you for this awesome Plugin, saves so much time for me.
But I have one problem for quite a long time: My KeeFox doesn't recognise the entries of my subfolders in my database.
My Keepass db looks like this:
.database          (mainfolder)
|-- general          (subfolder)
|-- social
|-- banking
|-- customers      (some logins for customers websites)
|--- customer1     (subfolder level 2)
|--- customer2
|--- ...

It seems that KeeFox only accesses entries from my 'general'-folder. Also the save dialogue only suggests me the folder 'general', if I register an new account for the first time.
Is it possible, that KeeFox can access also the subfolder-entries?

Looking forward to your answer!
Cheers Rob

**Comment by elgonzo** [comment]
Go into KeePass. Right-click on the root menu entry "Database" and select "Set as KeeFox start group". That should do it...

**Comment by M1NDHUNT3R** [comment]
Oh awesome, works, thanks a lot!
