### ISSUE TITLE
Random fieldname problem? 

### ISSUE THREAD

**Issue by victor-50** [luckyrat/KeeFox#628]
I posted this at zoho but it seems more active here so: 

I posted this at KeePass first but they say it types blind (however it doesn't type at all in this case), suggesting to post here.

Suddenly KeePass/Keefox stopped working logging into my bank account. Recreating an entry didn't help. I suspect because the bank is changing the fieldname of the loginfields at random. Here an example (replacing < with [ ):

[div id="gebruikersnaam" class="form_element"]
[label for="au5AhSBOaMClgljf1">Gebruikersnaam</label]
[ div class="tooltip-icon" ]
[/div]
[input type="text" class="" tabindex="1" name="au5AhSBOaMClgljf1"
id="au5AhSBOaMClgljf1" size="25"
maxlength="20"
value="" /]
[/div]
(gebruikersnaam = username)
Could there be any workaround?

**Comment by luckyrat** [comment]
Let's keep the discussion on Zoho unless we find a specific change that needs implementing in KeeFox: https://zohodiscussions.com/keefox/topic/random-fieldname-problem
