### ISSUE TITLE
"Setup KeeFox" page continues prompting despite being installed

### ISSUE THREAD

**Issue by squarepupil** [luckyrat/KeeFox#629]
Issue is as described. I've done this on two machines with Ubuntu 15.10 and neither will stop prompting me with the "Setup KeeFox" page when I open Firefox, despite the plugin being installed successfully (i.e., it works).

**Comment by dlech** [comment]
What are the settings on the KeePass tab of the KeeFox options in Firefox? Is the KeePassRPC plugin for KeePass the matching version for the KeeFox plugin for Firefox?

**Comment by squarepupil** [comment]
The KeePass directory was blank, so I changed it to /usr/bin/keepass2 (which is where the package installed via apt-get). It doesn't bring up the Setup KeeFox page anymore, so, success! I'm not sure why the plugin would work if that directory wasn't properly set. Anywho, it's working OK. The documentation for KeeFox is pretty good, as is, however, it's still a challenge for somebody who doesn't know their bins from their libs, etc.

**Comment by hackel** [comment]
I just experienced this as well doing a fresh install on FF50 with KeyFox 1.6.3.  Every time I restarted the browser, the "Setup KeyFox" page would be displayed, even though KeyFox was already working flawlessly.  While specifying the location is a nice work-around, this bug should still be fixed.  Especially if keepass2 is in one's path, it should just use that automatically.
