### ISSUE TITLE
KeeFox will still prompt to save a login even when the form was auto-filled by KeeFox

### ISSUE THREAD

**Issue by BoffinbraiN** [luckyrat/KeeFox#630]
I am able to reproduce this on several websites. It doesn't happen if I use the KeeFox menu to explicitly fill in a form using a KeePass entry. However, if a login form is auto-filled, KeeFox will prompt when it's submitted.

**Comment by luckyrat** [comment]
Please can you try out KeeFox 1.6 for a bit and then let me know of any specific examples of this problem? As it stands there isn't enough information here for me to even understand what the cause of the problem is, let alone investigate if it's possible to fix it.

**Comment by BoffinbraiN** [comment]
I've been testing on a few websites using 1.6, and looks like it's working better now. I'll let you know in a new ticket if I find something strange.
