### ISSUE TITLE
Keefox broken on Firefox 46 (Developer Edition)

### ISSUE THREAD

**Issue by hackel** [luckyrat/KeeFox#632]
I just installed Keefox (1.5.4) for the first time.  No toolbar icon appears, and this is what I get when I go to Keefox options:

![keefox screenshot from 2016-02-27 22-06-03](https://cloud.githubusercontent.com/assets/583677/13377387/6fb41f58-dd9f-11e5-9a58-daf25b929dfa.png)

In my Tools menu, I see this entry:
`%-KeeFox_Tools-Menu.options.label-%...`
Clicking this will also bring up the above dialogue.

Edit: I just confirmed this same behaviour in a new, clean profile.  Running the latest Firefox Developer Edition: 46.0a2 (2016-02-27).

Edit 2: Just confirmed that it works fine in FF 45.0b10.

**Comment by hackel** [comment]
Just discovered 1.6.0b1 on the developer channel.  Maybe add a note about this incompatibility to the add-on's description?

**Comment by ljani** [comment]
Firefox 46 has landed the beta channel (46.0b1) and I'm seeing the same problem. Installing 1.6.0b2 fixes the issue.

**Comment by tobybryans** [comment]
I can confirm this is happening in 46.0b2 too. The close window also affects the Master Password and HTTP authentication dialog boxes .
