### ISSUE TITLE
Fields won't fill in even though whitelisted and logfile seems to show them detected correctly

### ISSUE THREAD

**Issue by cecilkorik** [luckyrat/KeeFox#641]
Trying to have Keefox fill out the login form at [fullhost](https://manage.fullhost.com/clientarea.php). It is not working. I have added the appropriate fields to the whitelist in site-specific settings. I have also ensured the appropriate names and IDs are specified in the Keepass settings window under Keefox -> Form fields.

Nothing seems to work. Auto-fill does not work. Clicking the Keepass button does not work. There is a suspicious phrase in the log file, after everything looks like it has been successfully detected, the log file says, "Not auto-filling or auto-submiting this form. Not overwriting exsisting contents either." I don't know why it comes to that conclusion, and there is no obvious reason in the logfile, but perhaps this is the reason it's not working? 

Debug log is attached.

[log.txt](https://github.com/luckyrat/KeeFox/files/179035/log.txt)

**Comment by luckyrat** [comment]
Have you tried getting KeeFox to save the login for you? I just tried and it saved correctly and then filled again when I came back to the site. I'm sure we could eventually get to the bottom of why your whitelist configuration and KeePass entry configuration hasn't worked but I hope it will become academic if you just create the entry with KeeFox's save password feature.

**Comment by cecilkorik** [comment]
Confirming that does seem to resolve the issue for me as well, thanks.
