### ISSUE TITLE
Google calendar oauth broken in 1.6.0b3

### ISSUE THREAD

**Issue by dlech** [luckyrat/KeeFox#642]
The Google calendar oauth seems to be broken in 1.6.0b3. It gets stuck on "Loading passwords..."

![enter username and password for username](https://cloud.githubusercontent.com/assets/963645/13900227/4e56c2ee-edcf-11e5-8e9f-dcc86348b0d9.png)

**Comment by dlech** [comment]
It looks like nothing changed in KeeFox to break this, but rather Google has changed the oauth dialog.

**Comment by luckyrat** [comment]
This is in 1.6.1b1: https://addons.mozilla.org/en-US/firefox/addon/keefox/versions/beta
