### ISSUE TITLE
Refreshed profiles break keefox

### ISSUE THREAD

**Issue by robsonsobral** [luckyrat/KeeFox#645]
Hi!

I have two machines where KeeFox isn't running anymore. On one of them, I used Refresh Firefox, to rebuild the main profile. On other one, I synced the profile using the native sync function. Keefox is dead on both of them. Their settings look like this:

![keefox-bug](https://cloud.githubusercontent.com/assets/931642/13972426/6f01f78e-f077-11e5-97e5-165cc015d1b5.png)

Reinstall isn't enough to fix, even if I delete the extension folder.

Is there something else I should try?

Thank you!

**Comment by luckyrat** [comment]
What version of Firefox and KeeFox are you using? Do you have any other add-ons installed?

If you're going to sync a Firefox profile, I'd expect you would have to refresh in all synced locations and then re-setup the sync afterwards - otherwise you're potentially syncing the same problems back again and potentially making matters worse.

**Comment by robsonsobral** [comment]
No, no! I'm sorry for not make myself clear! The two cases are unrelated!

On one machine, the issues started after refresh the profile. It is a Windows 10 running Firefox Beta 46, keefox 1.5.4 and keepass 2.31.

The other case was that a different computer died so I installed Ubuntu on a third computer and synced the profile. The dead PC was a Windows 10 and the new one is a Ubuntu 15 running Firefox Developer Edition 47, Keefox 1.5.4 and Keepass 2.32 (dev).

In both cases, everything was fine until refresh/sync the profiles.

**Comment by luckyrat** [comment]
You need to be using the KeeFox beta version if you're running Firefox beta or developer edition. I don't know whether that is related to your problems but it is quite likely that a Firefox update occurred at the same time the problems began so keeping up to date with the latest version of KeeFox should help.

As it happens, KeeFox 1.6 has been released today which has support for Firefox 46+.

**Comment by robsonsobral** [comment]
Hi!

Thank you for your attention.

I never ha to use the beta version on Firefox beta or developer edition until now. But... After the last update, everything is working again! On Ubuntu and Windows 10!

Thank you again!
