### ISSUE TITLE
KeeFox 1.6 not working in Ubuntu

### ISSUE THREAD

**Issue by braderhart** [luckyrat/KeeFox#648]
Hello. I have tried installing the new KeeFox 1.6 in Ubuntu 14.04.4 LTS. The issue I have is that the plugin installs fine, but it never makes the connection to KeeFox. I've copied the plugin to the correct directory and it is able to launch KeePass from within Firefox, but it never actually connects. It just keeps asking me to launch.

**Comment by luckyrat** [comment]
Check that there aren't two KeePass installations or two KeePassRPC.plgx files on your system and then check the Tools/Plugins menu in KeePass to see if KeePassRPC 1.6.0 is listed.

Is this the first time you've installed KeeFox on this system or are you upgrading from an earlier version? If so, which one?

**Comment by braderhart** [comment]
I've confirmed that there is only one. The KeePassRPC plugin version is 2.0.19.26948.

I recently reinstalled, however I've had success with versions before this one. I haven't tried an older version yet to see if that is the issue, but I can try checking that now.

**Comment by braderhart** [comment]
Confirmed working fine in KeeFox 1.5.4

**Comment by braderhart** [comment]
I noticed that KeeFox is able to remember the plugin settings after I remove it and reinstall. Where are these stored?

**Comment by saierd** [comment]
I had the same problem. Firefox automatically updated KeeFox to 1.6. Then it could not connect to KeePass anymore (it did work before the update).

I could solve it manually by reinstalling KeeFox and copying `KeePassRPC.plgx` into the KeePass directory again.

**Comment by gesnaud** [comment]
Hello,

Same issue on a Debian 8.
I update keefox to 1.6
My keepass is 2.32.

I copy the plgx from my firefox profile to the keepass plugins dir.
When I click on launch keepass in Firefox i have a dialog box telling me that my plgx plugins is not compatible with my keepass version.


Thx

**Comment by dlech** [comment]
@gesnaud, "When I click on launch keepass in Firefox i have a dialog box telling me that my plgx plugins is not compatible" is not the same issue. Please run KeePass from the command line with `mono /path/to/KeePass.exe --debug`. Then open a new issue on GitHub and paste the results there. Most likely you are missing a dependency which can be solved with `sudo apt-get install mono-complete`.

**Comment by dlech** [comment]
> I noticed that KeeFox is able to remember the plugin settings after I remove it and reinstall. Where are these stored?

They are stored in your user preferences in your FireFox profile. You can type in `about:config` in the address bar in FireFox and search for "keefox" to see how the settings are stored.

**Comment by gesnaud** [comment]
> sudo apt-get install mono-complete
Sorry, I missed that... it dit the trick!

Thx & have a nice day!

**Comment by gregoiredx** [comment]
Like braderhart, I've been struggling with connection to keepass problems on Ubuntu 15.10 after an upgrade to keefox 1.6.0. I downgraded to keefox 1.5.4 and everything works again (after downgrading the keepass plugin too).
Could it be linked to the new .NET Framework 4 requirement (I'm running mono 3.2.8)?

**Comment by dlech** [comment]
It looks like `libmono-system-numerics4.0-cil` is needed in 1.6.x but was not before. See [this discussion](https://zohodiscussions.com/keefox/topic/fleck2-websocketexception-exception-of-type-fleck2-websocketexception-was-thrown#71684000000895065). You can know if the problem is the same by logging as seen in the link.

If you are installing from my ppa, then upgrade again. I have fixed the dependency. If not, try `sudo apt-get install libmono-system-numerics4.0-cil`.

**Comment by DigitalBrains1** [comment]
This fixed it for my Debian 8.3/jessie/stable i686.

**Comment by braderhart** [comment]
@dlech Thanks! That fixed it.

**Comment by braderhart** [comment]
I updated the wiki and am closing the issue.
