### ISSUE TITLE
No connection to KeePass since KeeFox-Update to 1.6

### ISSUE THREAD

**Issue by HannsDieter** [luckyrat/KeeFox#650]
I updated Keefox on my machines to 1.6. While it is working on my Windows machine, it isn't on my Ubuntu. 
I use Keefox in Firebird and Thunderbird and both are not getting a connection to KeePass anymore. They ask me to launch KeePass (while it is launched already). 

I removed the old RPC.plgx file from the KeePass directory and copied it again from the Thunderbird/Firebird location, but it doesn't work. 
I also tried to reinstall the update, but that doesn't do the trick either.

**Comment by dlech** [comment]
Duplicate of #648?

**Comment by HannsDieter** [comment]
Hey,

oh yes - it actually is. I did search for that issue, but didn't find it. Sorry for the duplicate!

Installing libmono-system-numerics4.0-cil did the trick.
Thanks for the help!
