### ISSUE TITLE
KeePassRPC.plgx incompatible with Keepass 2.32?

### ISSUE THREAD

**Issue by kyriog** [luckyrat/KeeFox#657]
Hi everyone,

I recently upgraded my Ubuntu from 15.10 to 16.04.

Since I restarted my computer, when I start Keepass, a popup says me:

> The following plugin is incompatible with the current KeePass version:
> /usr/lib/keepass2/plugins/KeePassRPC.plgx
>
> Have a look at the plugin's website for an appropriate version.

According to Firefox, I'm using KeeFox 1.6.0. I already tried to remove the plugin from KeePass and copy it again from Keefox directory, but I still have the same message.
About KeePass says I have "Version 2.32 (Dev)", with 3 components:
* KeePass: 2.32
* XSL Stylesheets for KDBX XML: Installed
* KeePassLibC (1.x File Support): Not installed

I also have 2 another plugins for better integration with Ubuntu:
* KeebuntuAppIndicator, version 0.4.7.0
* KeebuntuAppMenu, version 0.2.14.0

What can I do to get back my KeeFox working on Firefox?

Thanks for your help! :)

**Comment by Eagle-SK** [comment]
I agree with kyriog. After installing the new version of Ubuntu Xenial, the plugin KeePassRPC.plgx stopped working.
KeePass: 2.32
KeeFox: 1.6.0
I also tried the beta version of plugin which it also did not work.
![keepassrpc plgx](https://cloud.githubusercontent.com/assets/18661469/14786516/9a7e0a68-0aff-11e6-91c2-a8bdad2aa990.png)

**Comment by dlech** [comment]
Duplicate of #648?

If not a duplicate, what is the output of running `keepass2 --debug` from the command line?

By the way, the same ppa as the Ubuntu integration plugins has `keepass2-plugin-rpc` which is working on my 16.04 system.

**Comment by Eagle-SK** [comment]
No, it is not the same error.
Command "keepass2 --debug" opened two windows. Screenshots are in the 
attachment.

But there is a good news. When I installed your new deb package from the 
source 
"https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins/+files/keepass2-plugin-rpc_1.6.0-2_all.deb", 
everything began work.

With the "keepass2-plugin-rpc_1.6.0-2_all.deb" were installed few "mono" 
packages, called "libmono-csharp4.0c-cil, 
libmono-microsoft-csharp4.0-cil, mono-dmcs, mono-mcs". This is probably 
the reason why it was not functional.

In the Ubuntu 15.10 I had installed (copied) plugin, which was a part of 
the Mozilla KeeFox extension, complete mono library, and it works.

Thank you for your help.



Dňa 25.04.2016 o 18:51 David Lechner napísal(a):

**Comment by kyriog** [comment]
Confirmed here, it's a different error than #648.

I tried to install those 4 packages with keeping my KeePassRPC.plgx, but it still not working.
But if I try to install the plugin using apt-get, two other packages were requested:
* libmono-system-configuration-install4.0-cil
* libmono-system-management4.0-cil

I installed both manually and plugin compiled successfully.

To make things easier, I installed the plugin using the Ubuntu package, it should prevent things getting bad.

**Comment by mikolak-net** [comment]
@kyriog : I've taken the liberty to add your workaround to the installation instructions:
https://github.com/luckyrat/KeeFox/wiki/en-%7C-Installation-%7C-Linux#install-additional-plugin-dependencies-ubuntu-1604-only

Thanks for diagnosing the problem, by the way :).

**Comment by abumalick** [comment]
installing the deb package : 
 "https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins/+files/keepass2-plugin-rpc_1.6.0-2_all.deb", everything began work.
And then flushing the plugin cache worked for me.
Thanks@Eagle-SK

**Comment by tyndouf** [comment]
Thank you **dlech**, the command line `keepass2 --debug` was the right solution for me.

**Comment by leoboiko** [comment]
I had this issue on Debian stretch (as of today, on freeze status as testing).  The additional dependencies cited above "for Ubuntu 16.04 only" solved it.
