### ISSUE TITLE
KeeFox offers to save login on http://www.opera.com/download/guide/

### ISSUE THREAD

**Issue by anewuser** [luckyrat/KeeFox#662]
I'm using KeeFox 1.6.0 on Firefox 46.0.1 for Windows.

Open http://www.opera.com/download/guide/?os=windows&ver=12.18&local=y and click on "download".

Result: KeeFox offers to save a login.

Expected behavior: KeeFox shouldn't show any popup, since that page doesn't have login forms.

When you have time, please also take a look at the forum threads that haven't been replied to yet: https://zohodiscussions.com/keefox#home

**Comment by luckyrat** [comment]
The button is part of a form which could be a login form. This can only be prevented by stopping KeeFox from detecting some legitimate login forms which I won't do since this is just a small inconvenience in comparison.

**Comment by anewuser** [comment]
Are legitimate login forms that don't require the user to enter any info common?
