### ISSUE TITLE
Firefox update and dont work

### ISSUE THREAD

**Issue by trujillostm** [luckyrat/KeeFox#675]
I updated to Firefox 47.0
Plugin keefox (1.6.0) dont work.
KeePass 2.34
Windows 7 x64.

**Comment by dlech** [comment]
Can you be more specific? What exactly is not working?

**Comment by trujillostm** [comment]
Hello David.
The plugin cant connect with KeePass.
I push the button: Open KeePass, then open, I enter the master password,
and I can see my passwords.
But plugin dont work, I can see all the tiome the button "Open keepass".
I was trying with tcp port, but nothing occurs.
Thank you.

2016-06-14 17:12 GMT+02:00 David Lechner <notifications@github.com>:

**Comment by dlech** [comment]
Is there anything useful to you here? https://github.com/luckyrat/KeeFox/wiki/en-%7C-Troubleshooting

**Comment by trujillostm** [comment]
Hello. Now I can launch keepass. thank you.
