### ISSUE TITLE
Nighly v50 dialog box logins not working

### ISSUE THREAD

**Issue by tleepa** [luckyrat/KeeFox#677]
Hi,

I know it happens on Nightly v50 versions of Firefox, so it may not be the priority, but just to let you know: the form logins work fine but the ones with a dialog box do not. The form does not get populated and there is no KeeFox dropdown added.

Screenshots:
Aurora (v49) - working fine
![aurora](https://cloud.githubusercontent.com/assets/7734919/16349182/8c3376fa-3a57-11e6-800c-55908043eebf.png)
Nightly (v50) - not working
![nightly](https://cloud.githubusercontent.com/assets/7734919/16349183/8c368160-3a57-11e6-8c8e-3072c4c67b32.png)

KeeFox v1.6.1b1
KeePass v2.34

**Comment by luckyrat** [comment]
Thanks for letting me know. 1.6.2b1 should fix it. It's on the releases page now but I'll do more testing before pushing it to all beta users.

https://github.com/luckyrat/KeeFox/releases/tag/v1.6.2b1
