### ISSUE TITLE
List of logins = empty

### ISSUE THREAD

**Issue by jvollme** [luckyrat/KeeFox#681]
I am using KeeFox in Firefox 47.0 under linux ubuntu 14.04 (LTS). My KeePass version is 2.25
KeeFox worked fine at the beginning, but now the list of logins always show up as "empty" (even though I am connected to the correct Keepass2 database, Keepass2 is launched and the database is unlocked).
So now i have to fill out the forms manually by copy pasting from keepass2, rendering keefox basically useless for me at the moment.
What could be the problem?

**Comment by dlech** [comment]
You have to have something in the URL fields otherwise entries are ignored:

![selection_009](https://cloud.githubusercontent.com/assets/963645/16813266/68be3374-48f6-11e6-9034-a71643f21e65.png)

**Comment by jvollme** [comment]
thanks, but yes, I have the URL fields filled out in KeePass. In fact, that is how I currently navigate to most sites requiring login now anyway:
as I now need to copy the usernames and passwords directly from KeePass anyway, I just directly click on the respective Keepass entry, click "open url" and then copy and paste my credentials).

I also guess that otherwise Keefox would't have worked in the beginning. The first time i used KeeFox it recognized all my entries and the respective URLs. It just stopped doing that now for some reason.
i have tried manually setting the respective Keepass database in "options"-->"advanced"-->"When opening or logging to KeePass, use this database file:" but nothing changed.

**Comment by luckyrat** [comment]
Try changing the KeeFox home group in KeePass.

**Comment by jvollme** [comment]
Thanks, that helped. No Idea how, when and why the KeeFox home group changed, though. Works again.
