### ISSUE TITLE
Upgrade to 1.6.3b1 from 1.6.1b1 caused passwords not filling in ThunderBird

### ISSUE THREAD

**Issue by farkass** [luckyrat/KeeFox#684]
Hi I had the automatic update turned on, so this morning received update to 1.6.3b1.
Unfortunatelly the passwords were not filled in ThunderBird 45.2 anymore. The Launch button activates the KeePass window.
So reinstalled 1.6.1b1 and turned off the automatic update.

**Comment by dlech** [comment]
You must also upgrade the KeePassRPC plugin in KeePass

**Comment by farkass** [comment]
But in Firefox I have version 1.6.0. will it work with new version of plugin?

**Comment by dlech** [comment]
You will need to upgrade Firefox to KeeFox 1.6.3b1 as well.
