### ISSUE TITLE
installing the beta in thunderbird

### ISSUE THREAD

**Issue by downtownHippie** [luckyrat/KeeFox#695]
I want to install the beta in thunderbird - but I can't figure out how...

**Comment by downtownHippie** [comment]
Well, I got it installed, saved the file from the download page.  I had to uninstall it, reinstall the normal one, then install this, still doesn't fill passwords, but it will open keepass and I can get my passwords.  love the work

**Comment by dlech** [comment]
Can this issue be closed? There are several other issues about thunderbird not working that might be duplicates.
