### ISSUE TITLE
After upgrade to 1.6.3 KeePassRPC.plgx won't compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by Fake51** [luckyrat/KeeFox#698]
Running keepass2 with --debug I get the following dialog boxes (yes, twice)

![keefox1](https://cloud.githubusercontent.com/assets/124474/17881569/d5083c70-6906-11e6-8bcc-ca968ea2df83.png)
![keefox2](https://cloud.githubusercontent.com/assets/124474/17881589/f547d072-6906-11e6-9728-0f288c97f85b.png)

I've gone through https://github.com/luckyrat/KeeFox/wiki/en-%7C-Installation-%7C-Linux#install-additional-plugin-dependencies-ubuntu-1604-only to install the additional dependencies and cleared the plugin cache. No dice.

**Comment by Fake51** [comment]
Never mind, nothing to see here.

Problem fixed with installing mono-complete. My bad for assuming I had already done this. Apologies for the noise.

**Comment by brozkeff** [comment]
Had the same issue, installing mono-complete indeed helped. Strange that for a few years it worked for me nicely without that.
