### ISSUE TITLE
Security connection documentation is not accurate when running under Mono

### ISSUE THREAD

**Issue by lhernanz** [luckyrat/KeeFox#717]
Hi,

in https://github.com/luckyrat/KeeFox/wiki/en-%7C-Technical-%7C-KeePassRPC-detail#connection-security, you can read that using "Medium" security, the secret key in the keepass side is encrypted using the user password. 

This is not the case in Mono where a new key is created for the user but it is stored in the filesystem in plain text with no confidentiality warranties (see https://github.com/mono/mono/blob/mono-4.2.0-branch/mcs/class/Mono.Security/Mono.Security.Cryptography/KeyPairPersistence.cs). 

Probably, a warning for Mono users should be included to make them aware of the situation.

Regards

**Comment by luckyrat** [comment]
Thanks; good idea. I've updated the docs and posted an update to users to make them aware: http://keefox.org/news/detail/2016/10/18/security-documentation-update

Interesting aside from the comment in that file: "The ACL is also checked when a key is accessed (so totally public keys won't be used)". This could be part of the explanation for some occasional problems Unix users have had that get resolved by blowing away and recreating key store folders or reinstalling mono packages.
