### ISSUE TITLE
Does Keyfox generate passwords with characters/symbols like *,$,_,{, etc

### ISSUE THREAD

**Issue by pintobuck** [luckyrat/KeeFox#721]
I notice that Keypass can be set to automatically generate "custom" passwords that include various sets of symbols which make the passwords much more secure.  However, KeyFox generates passwords with only numbers and lower case letters.  Is it possible for KeyFox to auto generate passwords with upper case letters and various symbols / characters?

**Comment by bdurrer** [comment]
Yes it works. You have to use a generator profile which has those characters activated. You might want to create your own in KeePass, after that you can use it in KF.

**Comment by pintobuck** [comment]
Thank you for replying. I figured out than I can generate custom passwords with symbols in Keypass, and then Keyfox will use the password that I assign it to a particular login.   

Keyfox has a nice feature in the drop down menu that will generate its own new passwords when I'm creating a whole new login.  I have been unable to get the Keyfox drop down menu to generate passwords on its own that contain capital letters and/or symbols.

**Comment by xchs** [comment]
BTW @pintobuck The add-on is called KeeFox and not KeyFox (the same applies to KeePass / Keypass).

**Comment by luckyrat** [comment]
As bdurrer says, you need to use KeePass password profiles: http://keepass.info/help/base/pwgenerator.html#profiles
