### ISSUE TITLE
No admin privileges 

### ISSUE THREAD

**Issue by ikc666** [luckyrat/KeeFox#726]
I try to install Keefox on a FireFox 49.02 Portable using a Keepass Portable 2.34 on windows 7 without admin rights. Is there a way to do so (I couldn't find solution in ticket #649 nor in #84)?

**Comment by dlech** [comment]
Does this help: <https://github.com/luckyrat/KeeFox/wiki/en-%7C-Portable-KeeFox>?

**Comment by ikc666** [comment]
Works fine. It did the job. Thx a lot.
