### ISSUE TITLE
Regression: HTTP auth entry is not prioritized when the realm string is set

### ISSUE THREAD

**Issue by dessant** [luckyrat/KeeFox#731]
With KeeFox 1.6.4 on Firefox 49 you can prioritize an entry by setting the `HTTP Auth Realm` string, this setting does not seem to have any effect on Firefox 50.

**Comment by dlech** [comment]
Can you post screenshots of the dialogs for both versions (49 and 50)?

**Comment by dessant** [comment]
On 50 it looks like the dialog posted here: https://github.com/luckyrat/KeeFox/issues/732#issue-190652745.
`HTTP Auth Realm` is set to `Private Area`, but a different matching entry is auto filled instead.

On 49 the desired HTTP auth entry is selected and auto-filled, and the dialog looks like this:
![untitled-1](https://cloud.githubusercontent.com/assets/7513068/20504695/887a49f6-b051-11e6-8893-07c9e8ea2eb3.png)

**Comment by dlech** [comment]
You can try [logging sensitive data](https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options-%7C-Logging-%7C-Sensitive) to see if KeeFox is actually picking up the realm and sending it to KeePass.

Unfortunately, I don't see anything obviously wrong here.

**Comment by dessant** [comment]
@dlech, you're right, it looks like the realm is not sent to KeePass:

```
Sending a JSON-RPC request: {"params":[["https://example.com"],null,"","LSTnoRealms",false,null,"",null,""],"method":"FindLogins","id":9}
```

**Comment by dessant** [comment]
It works as expected with Firefox 51.
