### ISSUE TITLE
Pale Moon 27 and KeeFox 

### ISSUE THREAD

**Issue by justxm4** [luckyrat/KeeFox#734]
Welcome everyone. 
I would like to ask about the KeeFox future. Today was released Pale Moon in the new version 27, this version has a lot of changes. Here, one of them: developers have ended up support for the SDK extensions (JetPack extensions), which means KeeFox is incompatible with this version.

**Release notes:**
https://forum.palemoon.org/viewtopic.php?f=1&t=13717

> **Removed support for Add-on SDK extensions (JetPack extensions),** considering the Mozilla/Gecko SDK is no longer compatible with our combination of application and platform code.

> We will continue to fully support the following:

  

>   **NPAPI plugins**
>     Extensions with binary/XPCOM components
>     XUL/Overlay and bootstrapped extensions
>     Complete themes
>     Unsigned and author-signed extensions
>     The Camellia encryption cipher (also in GCM mode)
>     Graphite font shaping
>     Sync 1.1 (albeit without support for syncing add-ons)
>     Full customization of the UI as before

And here comes my question. Are you planning adapt KeeFox to  the NPAPI standard ?
I love this extension and I would continue to use them. Best regards.

**Comment by luckyrat** [comment]
KeeFox doesn't use the SDK so if it's stopped working it'll be for a different reason. KeeFox is a "XUL/Overlay" extension.

NPAPI plugins are unrelated to browser add-ons. They don't do the same thing and have been deprecated for many years due to the security risk they pose.
