### ISSUE TITLE
Fields not recognized with 1.6.4 on Thunderbird 45.5.0

### ISSUE THREAD

**Issue by crazy-max** [luckyrat/KeeFox#735]
Hi,

With the latest KeeFox addon (1.6.4) the fields are not filled on Thunderbird 45.5.0 (french).
Ok when going back to 1.6.3.

**Comment by dlech** [comment]
This probably has to do with the [url matching security update]()http://keefox.org/news/detail/2016/11/21/security-update-released.

**Comment by crazy-max** [comment]
Indeed!

I forgot to install the latest KeepassRPC
