### ISSUE TITLE
Keefox and Kaspersky

### ISSUE THREAD

**Issue by jorgegaspar** [luckyrat/KeeFox#740]
I'm a long timer user of Keefox and today I switched my anti-virus from ESET to Kaspersky Internet Security, but now I have an issue. Keefox can't connect to Keepass, everytime I click on the "login to keepass" the keepass window opens but nothing happens. I wonder if this is a reported issue, since Kaspersky is a well know anti-virus.

This is weird because even if I turn all the protections on Kaspersky (including firewall, web protection, file protection, application protection and all the others) the problem still happens, but if I completely close the Kaspersky on the tray bar (right click -> exit) the keefox connects as usual with keepass. Also this thing is only happening on the Keefox for Firefox, I also use it on Thunderbird but I have no issues there with Kaspersky running.

Any help will be highly appreciated.

**Comment by anewuser** [comment]
You should be reporting this to Kaspersky instead of posting here.

**Comment by jorgegaspar** [comment]
Funny, because they said that I should report that to Keefox since it was the only thing that was not working! No biggy, actually I figured it out the problem, it wasn't related with keefox or kaspersky but with the build of the windows insider (and I know, bla bla bla "you shouldn't use those, they are buggy and such") downgraded and now keefox is working fine with kaspersky
