### ISSUE TITLE
KeeFox not longer fill htaccess form

### ISSUE THREAD

**Issue by kregielpl** [luckyrat/KeeFox#744]
Hi,

I don't know why but I noticed that KeeFox not longer support filling htaccess form on the website.
Anyone know why?

Thanks for reply,
Best Reagrds

**Comment by dlech** [comment]
What KeeFox version? What FireFox version? What FireFox language? Can you post a screen shot?

**Comment by kregielpl** [comment]
KeeFox: 1.6.4
FireFox: 50.0.2

What should I include to screenshot?

**Comment by dlech** [comment]
The htaccess form.

**Comment by dlech** [comment]
If you are using [one of these languages](https://github.com/luckyrat/KeeFox/issues/736#issuecomment-262499242), then this is a duplicate of #736.

**Comment by kregielpl** [comment]
Yes, this is a duplicate.
