### ISSUE TITLE
KeePassRPC is already listening for connections (ubuntu)

### ISSUE THREAD

**Issue by anwfr** [luckyrat/KeeFox#755]
Hello,
I can't get KeeFox working since upgrade to ubuntu xenial.
* Launching Firefox, I click the "launch keepass" menu from KeeFox
* I get the following error from KeeFox plugin: "KeePassRPC is already listening for connections"
* KeeFox menu turns to "install keefox"

I made sure plugin is in correct "plugins" directory, also created symlink to "Plugins" (#745)
Before launching keepass2 I made sure that nothing is listening to KeePassRPC port (with netstat -lnp). **Nothing is listening to this port** before launching keepass (after getting error message, "cli" is listening to this port).
It looks like KeePassRPC tries to open 2 connexions successively

Tried reinstalling keepass2 and keefox, clearing plugin cache... plugin is found.

- Keepass2 version 2.35+dfsg-1~ubuntu16.04~ppa1 (from ppa jtaylor-ubuntu-keepass)
- KeeFox version 1.6.4
- KeePassRPC plugin version 1.6.2.0

Any idea?

**Comment by dlech** [comment]
Hmm... I wonder if this symlik is bad advice. It could be that KeePass is looking it both directories and is loading KeePassRPC.plgx twice.

**Comment by anwfr** [comment]
oh yes, could have been this :)
Unfortunately deleting the "Plugins" directory and moving it to "plugins", then clearing plugins cache leads to the same error.

**Comment by dlech** [comment]
Perhaps you have another copy of KeePassRPC.plgx hiding somewhere? Try this.

    $ find /usr/lib/keepass2/ -name KeePassRPC.plgx

**Comment by anwfr** [comment]
`$ find /usr/lib/keepass2/ -name KeePassRPC.plgx
/usr/lib/keepass2/KeePassRPC.plgx
/usr/lib/keepass2/plugins/KeePassRPC.plgx
`

Wow!!! No idea how this copy ended here :)
Thank you so much! KeeFox working again, woot woot! :+1:
