### ISSUE TITLE
Anonymous stats DNS queries, even though sending anoymous stats is disabled

### ISSUE THREAD

**Issue by GeINeSiiS** [luckyrat/KeeFox#760]
My Setup:
Firefox 51.0.1 with Keefox 1.6.4
Thunderbird 45.7.1 with Keefox 1.6.4b1

In both Plugin settings "send anonymous data" is disabled.

I just setup Pi Hole for my network and noticed that it blocks DNS queries to anonymousstats.keefox.org every couple seconds.(see screenshots attached)

![block2](https://cloud.githubusercontent.com/assets/20794964/23103319/d1ce1746-f6b9-11e6-9d4b-76e504652c43.JPG)
![blocks1](https://cloud.githubusercontent.com/assets/20794964/23103320/d1cf1614-f6b9-11e6-911d-2ee40a503f5d.JPG)

The plugin should not resolv this with the option disabled.

**Comment by dlech** [comment]
Duplicate of #663?

**Comment by GeINeSiiS** [comment]
Yes. Didn't check properly. Closed.
