### ISSUE TITLE
Multiple instance problem

### ISSUE THREAD

**Issue by TrueXakeP** [luckyrat/KeeFox#764]
First thank you for this great addon.
Second sorry for my English.
I have a problem with multiple instances of keepass and firefox. I have a PC with multiple user accounts with keepass and keefox installed. And when I switch from one account to another leaving keepass or firefox running then keefox tries to connect to different keepass. When this happens a confirmation request appears (from keepass or keefox) and I can't such easy copy the auth code between PC's users so I reject the request. First problem is that the confirmation request continue to appear again and again until I relogin and close firefox (or keepas) in another account. Second is that the correct links between keefox and keepass with one owner after that are lost and must be restored by entering security key (for each correctly connected FF). And this two things are very annoying when it's happens.

**Comment by dlech** [comment]
You can change the settings of one of the instances so that it uses a different TCP port.

https://github.com/luckyrat/KeeFox/wiki/en-%7C-Options-%7C-KPRPC-Port

**Comment by TrueXakeP** [comment]
Yes, it worked. Thank you.
